# # #

name: tmlmobilidade-go-controller-staging

secrets:
  ociprivatekey:
    file: ./secrets/oci-private-key.pem

services:

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  watchtower:
    image: nickfedor/watchtower
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
      resources:
        limits:
          memory: 1gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=10
      - WATCHTOWER_CLEANUP=TRUE
      - WATCHTOWER_REMOVE_VOLUMES=TRUE
      - WATCHTOWER_INCLUDE_RESTARTING=TRUE
      - WATCHTOWER_INCLUDE_STOPPED=TRUE
      - WATCHTOWER_REVIVE_STOPPED=TRUE
      - WATCHTOWER_TIMEOUT=120s
      - WATCHTOWER_ROLLING_RESTART=TRUE

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  bridgedb:
    image: postgres:alpine
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 4gb
    ports:
      - 27027:5432
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  nginx:
    image: ghcr.io/tmlmobilidade/go-controller-nginx:staging
    labels:
      com.centurylinklabs.watchtower.enable: true
      com.centurylinklabs.watchtower.depends-on: 'frontend,api'
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 1gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    ports:
      - 80:80

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  api:
    image: ghcr.io/tmlmobilidade/go-controller-api:staging
    labels:
      com.centurylinklabs.watchtower.enable: true
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 4gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env
    volumes:
      - ./secrets/go-ssh-tunnel-key:/ssh-keys/go-ssh-tunnel-key:ro
    extra_hosts:
      - "go-prd-mongodb-1.tmlmobilidade.pt:10.81.101.161"
      - "go-prd-mongodb-2.tmlmobilidade.pt:10.81.101.162"
      - "go-prd-mongodb-3.tmlmobilidade.pt:10.81.101.163"

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  coordinator:
    image: ghcr.io/tmlmobilidade/go-controller-coordinator:staging
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 4gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  frontend:
    image: ghcr.io/tmlmobilidade/go-controller-frontend:staging
    labels:
      com.centurylinklabs.watchtower.enable: true
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 4gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  rides-acceptor:
    image: ghcr.io/tmlmobilidade/go-controller-rides-acceptor:staging
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 4gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  rides-bridge:
    image: ghcr.io/tmlmobilidade/go-controller-rides-bridge:staging
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 4gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  rides-cleaner:
    image: ghcr.io/tmlmobilidade/go-controller-rides-cleaner:staging
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 4gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  rides-examiner:
    image: ghcr.io/tmlmobilidade/go-controller-rides-examiner:staging
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 4gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  rides-feeder:
    image: ghcr.io/tmlmobilidade/go-controller-rides-feeder:staging
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 4gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env
    secrets:
      - ociprivatekey

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  rides-locker:
    image: ghcr.io/tmlmobilidade/go-controller-rides-locker:staging
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 4gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  sams-examiner:
    image: ghcr.io/tmlmobilidade/go-controller-sams-examiner:staging
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 4gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  sams-feeder:
    image: ghcr.io/tmlmobilidade/go-controller-sams-feeder:staging
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 4gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env