# # #

name: tmlmobilidade-sae-controller

services:

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  watchtower:
    image: containrrr/watchtower
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 100mb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=10
      - WATCHTOWER_CLEANUP=TRUE
      - WATCHTOWER_INCLUDE_STOPPED=TRUE
      - WATCHTOWER_REVIVE_STOPPED=TRUE
      - WATCHTOWER_ROLLING_RESTART=TRUE

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  bridgedb:
    image: postgres:alpine
    deploy:
      restart_policy:
        condition: any
        delay: 30s
    ports:
      - 27027:5432
    volumes:
      - ./bridge-db-data:/var/lib/postgresql/data
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  cleaner:
    image: ghcr.io/tmlmobilidade/sae-controller-cleaner:production
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 4gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  coordinator:
    image: ghcr.io/tmlmobilidade/sae-controller-coordinator:production
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 2gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  rides-bridge:
    image: ghcr.io/tmlmobilidade/sae-controller-rides-bridge:production
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 2gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  rides-examiner:
    image: ghcr.io/tmlmobilidade/sae-controller-rides-examiner:production
    deploy:
      mode: replicated
      replicas: 4
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 2gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  rides-feeder:
    image: ghcr.io/tmlmobilidade/sae-controller-rides-feeder:production
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 4gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  sams-feeder:
    image: ghcr.io/tmlmobilidade/sae-controller-sams-feeder:production
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 4gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  sams-examiner:
    image: ghcr.io/tmlmobilidade/sae-controller-sams-examiner:production
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 2gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env