/* * */

export const PublicFeedbackReasons = [
	{
		entity_type: 'line',
		values: [
			'early',
			'late',
			'detour',
			'long_headway',
			'too_crowded',
			'cancelled_departure',
			'long_queue',
			'interrupted',
			'inaccurate_realtime',
			'wrong_panel_information',
			'did_not_pass',
			'route_changed_without_notice',
			'skipped_stop',
			'damaged',
			'dirty',
			'missing_safety_equipment',
			'door_issue',
			'climate_control_issue',
			'validator_issue',
			'accessibility_issue',
			'lighting_issue',
			'lack_of_passenger_support',
			'rude_staff',
			'driver_bad_conduct',
			'disorganized_boarding',
			'display_issue',
			'inadequate_service',
			'unsafe_speed',
			'traffic_law_violation',
			'audio_announcement_issue',
			'safety_incident',
			'insufficient_capacity',
			'excessive_travel_time',
			'other',
		],
	},
	{
		entity_type: 'stop',
		values: [
			'no_bench',
			'no_shelter',
			'lighting_issue',
			'missing_line_information',
			'dirty',
			'wrong_panel_information',
			'ticket_machine_issue',
			'disorganized_boarding',
			'accessibility_issue',
			'validator_issue',
			'confusing_signage',
			'audio_announcement_issue',
			'display_issue',
			'damaged_bench',
			'shelter_issue',
			'safety_incident',
			'elevator_escalator_issue',
			'sidewalk_issue',
			'no_trash_bin',
			'weather_exposure_issue',
			'other',
		],
	},
] as const;
