# # #

name: tmlmobilidade-go-dev

services:

  database:
    image: mongo
    deploy:
      restart_policy:
        condition: any
        delay: 30s
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    ports:
      - 37000:27017
    volumes:
      - ./replica.key:/data/replica.key
      - ./mock.dump:/dump/db.dump
      - ./local-setup.sh:/docker-entrypoint-initdb.d/setup.sh
    entrypoint:
      - /bin/bash
      - -c
      - |
        chmod 400 /data/replica.key
        chown 999:999 /data/replica.key
        exec docker-entrypoint.sh $$@
    command: mongod --bind_ip_all --auth --replSet rs0 --keyFile /data/replica.key --port 27017