# # #

name: tmlmobilidade-go-replicator-production

services:

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  wud:
    image: getwud/wud
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 100mb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WUD_TRIGGER_DOCKER_DEFAULT_PRUNE=true
      - WUD_WATCHER_LOCAL_WATCHALL=true
      - WUD_WATCHER_LOCAL_CRON=* * * * *

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  enrich:
    image: ghcr.io/tmlmobilidade/go-replicator-enrich:production
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 2gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  stream:
    image: ghcr.io/tmlmobilidade/go-replicator-stream:production
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 2gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  sync-apex-locations:
    image: ghcr.io/tmlmobilidade/go-replicator-sync-apex-locations:production
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 2gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  sync-apex-on-board-refunds:
    image: ghcr.io/tmlmobilidade/go-replicator-sync-apex-on-board-refunds:production
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 2gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  sync-apex-on-board-sales:
    image: ghcr.io/tmlmobilidade/go-replicator-sync-apex-on-board-sales:production
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 2gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  sync-apex-validations:
    image: ghcr.io/tmlmobilidade/go-replicator-sync-apex-validations:production
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 2gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  sync-vehicle-events:
    image: ghcr.io/tmlmobilidade/go-replicator-sync-vehicle-events:production
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 2gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env