# # #
# Fill in all values before applying.
# Apply with: kubectl apply -f manifests/locations/secret.yaml
# WARNING: Do not commit this file with real values.

apiVersion: v1
kind: Secret
metadata:
  name: locations-secret
  namespace: go-locations
type: Opaque
stringData:
  ENVIRONMENT: "k8s"

  ## DATABASE
  DATABASE_URI: ""
