apiVersion: v1
kind: Service
metadata:
  name: locations-nginx
  namespace: go-locations
  labels:
    app: locations-nginx
    app.kubernetes.io/name: locations-nginx
    app.kubernetes.io/part-of: go-locations
spec:
  type: NodePort
  selector:
    app: locations-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30085
      protocol: TCP
