/* * */

export const originalStopFromGoV1 = {
	__v: 1,
	_id: {
		$oid: '6476b095424adb51586dffa7',
	},
	code: '010015',
	createdAt: {
		$date: '2024-03-21T01:15:32.928Z',
	},
	docking_bay_type: '',
	has_abusive_parking: 'UNKNOWN',
	has_audio_stop_info: '',
	has_bench: 'UNKNOWN',
	has_cover: 'UNKNOWN',
	has_crossing: 'UNKNOWN',
	has_crosswalk: '',
	has_electricity: '',
	has_flag: 'UNKNOWN',
	has_flat_access: 'UNKNOWN',
	has_h2oa_signage: '',
	has_lighting: '',
	has_mupi: '',
	has_network_map: '',
	has_pip_audio: 'UNKNOWN',
	has_pip_real_time: '',
	has_pip_realtime: 'UNKNOWN',
	has_pip_static: 'UNKNOWN',
	has_pole: '0',
	has_pole_frame: '',
	has_schedules: '',
	has_shelter: 'UNKNOWN',
	has_sidewalk: '',
	has_stop_sign: '',
	has_tactile_access: 'UNKNOWN',
	has_tactile_pavement: '',
	has_tactile_schedules: '',
	has_trash_bin: 'UNKNOWN',
	has_wide_access: 'UNKNOWN',
	is_locked: false,
	jurisdiction: '',
	last_accessibility_check: '',
	last_infrastructure_check: null,
	last_infrastructure_maintenance: null,
	last_schedules_check: '',
	last_schedules_maintenance: '',
	last_stop_sign_check: '',
	last_stop_sign_maintenance: '',
	latitude: 38.7487576,
	locality: 'Alcochete',
	longitude: -8.9671055,
	media: [],
	municipality: {
		$oid: '6450539f8f71c3c98f1fbed0',
	},
	name: 'ALCOCHETE (R LIBERDADE) ESCOLA VALBOM',
	name_new: 'Escola Básica n.º 2 de Alcochete (Valbom)',
	near_airport: false,
	near_bike_parking: false,
	near_bike_sharing: false,
	near_boat: false,
	near_car_parking: false,
	near_fire_station: false,
	near_health_clinic: false,
	near_historic_building: false,
	near_hospital: false,
	near_light_rail: false,
	near_police_station: false,
	near_school: true,
	near_shopping: false,
	near_subway: false,
	near_train: false,
	near_transit_office: false,
	near_university: false,
	notes: '',
	operational_status: 'ACTIVE',
	parent_station: '',
	pip_real_time_code: '',
	platform_code: '',
	road_type: 'UNKNOWN',
	shelter_code: '',
	shelter_frame_area_cm: '',
	shelter_maintainer: '',
	short_name: 'Escola Básica n.º 2 de Alcochete (Valbom)',
	short_name_auto: true,
	sidewalk_type: '',
	stop_access_type: '',
	stop_sign_maintainer: '',
	tts_name: 'Alcochete ( Rua Liberdade ) Escola Valbom',
	updatedAt: {
		$date: '2024-06-05T12:07:35.985Z',
	},
	wheelchair_boarding: '',
	zones: [
		{
			$oid: '64911309b0c69c6cc5eac7dc',
		},
		{
			$oid: '64996d1bf45d37f8e1c5dcea',
		},
	],
};

/* * */

export type OriginalStopType = typeof originalStopFromGoV1;
