apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-api
  namespace: go-fleet
  labels:
    app: fleet-api
    app.kubernetes.io/name: fleet-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: go-fleet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleet-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: fleet-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values: [fleet-api]
                topologyKey: kubernetes.io/hostname
      containers:
        - name: api
          image: ghcr.io/tmlmobilidade/go-fleet-api:k8s
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5050
              protocol: TCP
          envFrom:
            - secretRef:
                name: fleet-secret
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
