/**
 * This file is auto-generated by the generate-routes.sh script.
 * Do not edit this file manually.
 */

import { getModuleConfig } from './app-configs.js';

/* * */

export const PAGE_ROUTES = Object.freeze({
	/* * */
	/* ALERTS */
	alerts: {
		// BASE
		BASE: `${getModuleConfig('alerts', 'frontend_url')}`,

		// ALERTS
		ALERTS_DETAIL: (id: string) => `${getModuleConfig('alerts', 'frontend_url')}/${id}`,
		ALERTS_LIST: `${getModuleConfig('alerts', 'frontend_url')}`,
	},

	/* * */
	/* AUTH */
	auth: {
		// BASE
		BASE: `${getModuleConfig('auth', 'frontend_url')}`,

		// AGENCIES
		AGENCIES_DETAIL: (id: string) => `${getModuleConfig('auth', 'frontend_url')}/agencies/${id}`,
		AGENCIES_LIST: `${getModuleConfig('auth', 'frontend_url')}/agencies`,

		// CHANGE_PASSWORD
		CHANGE_PASSWORD_LIST: `${getModuleConfig('auth', 'frontend_url')}/change-password`,

		// HOME
		HOME_DETAIL: (id: string) => `${getModuleConfig('auth', 'frontend_url')}/home/${id}`,
		HOME_LIST: `${getModuleConfig('auth', 'frontend_url')}/home`,

		// LOGIN
		LOGIN_LIST: `${getModuleConfig('auth', 'frontend_url')}/login`,

		// ORGANIZATIONS
		ORGANIZATIONS_DETAIL: (id: string) => `${getModuleConfig('auth', 'frontend_url')}/organizations/${id}`,
		ORGANIZATIONS_LIST: `${getModuleConfig('auth', 'frontend_url')}/organizations`,

		// RESET_PASSWORD
		RESET_PASSWORD_LIST: `${getModuleConfig('auth', 'frontend_url')}/reset-password`,

		// ROLES
		ROLES_DETAIL: (id: string) => `${getModuleConfig('auth', 'frontend_url')}/roles/${id}`,
		ROLES_LIST: `${getModuleConfig('auth', 'frontend_url')}/roles`,

		// USERS
		USERS_DETAIL: (id: string) => `${getModuleConfig('auth', 'frontend_url')}/users/${id}`,
		USERS_LIST: `${getModuleConfig('auth', 'frontend_url')}/users`,
	},

	/* * */
	/* CONTROLLER */
	controller: {
		// BASE
		BASE: `${getModuleConfig('controller', 'frontend_url')}`,

		// RIDES
		RIDES_DETAIL: (id: string) => `${getModuleConfig('controller', 'frontend_url')}/rides/${id}`,
		RIDES_LIST: `${getModuleConfig('controller', 'frontend_url')}/rides`,
	},

	/* * */
	/* DATES */
	dates: {
		// BASE
		BASE: `${getModuleConfig('dates', 'frontend_url')}`,

		// ANNOTATIONS
		ANNOTATIONS_DETAIL: (id: string) => `${getModuleConfig('dates', 'frontend_url')}/annotations/${id}`,
		ANNOTATIONS_LIST: `${getModuleConfig('dates', 'frontend_url')}/annotations`,

		// CALENDAR
		CALENDAR_LIST: `${getModuleConfig('dates', 'frontend_url')}/calendar`,

		// EVENTS
		EVENTS_DETAIL: (id: string) => `${getModuleConfig('dates', 'frontend_url')}/events/${id}`,
		EVENTS_LIST: `${getModuleConfig('dates', 'frontend_url')}/events`,

		// HOLIDAYS
		HOLIDAYS_DETAIL: (id: string) => `${getModuleConfig('dates', 'frontend_url')}/holidays/${id}`,
		HOLIDAYS_LIST: `${getModuleConfig('dates', 'frontend_url')}/holidays`,

		// YEAR_PERIODS
		YEAR_PERIODS_DETAIL: (id: string) => `${getModuleConfig('dates', 'frontend_url')}/year-periods/${id}`,
		YEAR_PERIODS_LIST: `${getModuleConfig('dates', 'frontend_url')}/year-periods`,
	},

	/* * */
	/* FLEET */
	fleet: {
		// BASE
		BASE: `${getModuleConfig('fleet', 'frontend_url')}`,

		// VEHICLES
		VEHICLES_DETAIL: (id: string) => `${getModuleConfig('fleet', 'frontend_url')}/vehicles/${id}`,
		VEHICLES_LIST: `${getModuleConfig('fleet', 'frontend_url')}/vehicles`,
	},

	/* * */
	/* OFFER */
	offer: {
		// BASE
		BASE: `${getModuleConfig('offer', 'frontend_url')}`,

		// FARES
		FARES_DETAIL: (id: string) => `${getModuleConfig('offer', 'frontend_url')}/fares/${id}`,
		FARES_LIST: `${getModuleConfig('offer', 'frontend_url')}/fares`,

		// LINES
		LINES_DETAIL: (id: string) => `${getModuleConfig('offer', 'frontend_url')}/lines/${id}`,
		LINES_LIST: `${getModuleConfig('offer', 'frontend_url')}/lines`,

		// PATTERN
		PATTERN_DETAIL: (id: string, patternId: string, routeId: string) => `${getModuleConfig('offer', 'frontend_url')}/lines/${id}/${routeId}/${patternId}`,

		// ROUTE
		ROUTE_DETAIL: (id: string, routeId: string) => `${getModuleConfig('offer', 'frontend_url')}/lines/${id}/${routeId}`,

		// TYPOLOGIES
		TYPOLOGIES_DETAIL: (id: string) => `${getModuleConfig('offer', 'frontend_url')}/typologies/${id}`,
		TYPOLOGIES_LIST: `${getModuleConfig('offer', 'frontend_url')}/typologies`,

		// ZONES
		ZONES_DETAIL: (id: string) => `${getModuleConfig('offer', 'frontend_url')}/zones/${id}`,
		ZONES_LIST: `${getModuleConfig('offer', 'frontend_url')}/zones`,
	},

	/* * */
	/* PERFORMANCE */
	performance: {
		// BASE
		BASE: `${getModuleConfig('performance', 'frontend_url')}`,

		// AREAS_1
		AREAS_1_LIST: `${getModuleConfig('performance', 'frontend_url')}/areas/1`,

		// AREAS_2
		AREAS_2_LIST: `${getModuleConfig('performance', 'frontend_url')}/areas/2`,

		// DEMAND_DEMAND_BY
		DEMAND_DEMAND_BY_LIST: `${getModuleConfig('performance', 'frontend_url')}/demand/demand-by`,

		// DEMAND
		DEMAND_LIST: `${getModuleConfig('performance', 'frontend_url')}/demand`,

		// SUPPLY
		SUPPLY_LIST: `${getModuleConfig('performance', 'frontend_url')}/supply`,
	},

	/* * */
	/* PLANS */
	plans: {
		// BASE
		BASE: `${getModuleConfig('plans', 'frontend_url')}`,

		// APPROVED
		APPROVED_DETAIL: (id: string) => `${getModuleConfig('plans', 'frontend_url')}/approved/${id}`,
		APPROVED_LIST: `${getModuleConfig('plans', 'frontend_url')}/approved`,

		// VALIDATIONS
		VALIDATIONS_DETAIL: (id: string) => `${getModuleConfig('plans', 'frontend_url')}/validations/${id}`,
		VALIDATIONS_LIST: `${getModuleConfig('plans', 'frontend_url')}/validations`,
	},

	/* * */
	/* STOPS */
	stops: {
		// BASE
		BASE: `${getModuleConfig('stops', 'frontend_url')}`,

		// STOPS
		STOPS_DETAIL: (id: string) => `${getModuleConfig('stops', 'frontend_url')}/${id}`,
		STOPS_LIST: `${getModuleConfig('stops', 'frontend_url')}`,
	},
} as const);

export const API_ROUTES = Object.freeze({
	/* * */
	/* ALERTS */
	alerts: {
		// BASE
		BASE: `${getModuleConfig('alerts', 'api_url')}`,

		// ALERTS
		ALERTS_DETAIL: (id: string) => `${getModuleConfig('alerts', 'api_url')}/alerts/${id}`,
		ALERTS_DETAIL_IMAGE: (id: string) => `${getModuleConfig('alerts', 'api_url')}/alerts/${id}/image`,
		ALERTS_DETAIL_LOCK: (id: string) => `${getModuleConfig('alerts', 'api_url')}/alerts/${id}/lock`,
		ALERTS_LIST: `${getModuleConfig('alerts', 'api_url')}/alerts`,
		ALERTS_RSS: `${getModuleConfig('alerts', 'api_url')}/alerts.rss`,

		// GTFS
		GTFS_CARRIS_METROPOLITANA: `${getModuleConfig('alerts', 'api_url')}/gtfs/carris-metropolitana`,

		// HASHED_TRIPS
		HASHED_TRIPS_DETAIL: (id: string) => `${getModuleConfig('alerts', 'api_url')}/hashed-trips/${id}`,
		HASHED_TRIPS_LIST: `${getModuleConfig('alerts', 'api_url')}/hashed-trips`,

		// LINES
		LINES_HASHED_TRIPS: `${getModuleConfig('alerts', 'api_url')}/lines/hashed-trips`,
		LINES_LIST: `${getModuleConfig('alerts', 'api_url')}/lines`,

		// RIDES
		RIDES_DETAIL_RIDE: (id: string) => `${getModuleConfig('alerts', 'api_url')}/rides/${id}/ride`,
		RIDES_LIST: `${getModuleConfig('alerts', 'api_url')}/rides`,
		RIDES_WS: `${getModuleConfig('alerts', 'api_url')}/rides/ws`,

		// STOPS
		STOPS_BATCH: `${getModuleConfig('alerts', 'api_url')}/stops/batch`,
		STOPS_DETAIL: (id: string) => `${getModuleConfig('alerts', 'api_url')}/stops/${id}`,
		STOPS_LIST: `${getModuleConfig('alerts', 'api_url')}/stops`,
		// RIDES
		RIDES_DETAIL_RIDE: (id: string) => `${getAppConfig('alerts', 'api_url')}/rides/${id}/ride`,
		RIDES_LIST: `${getAppConfig('alerts', 'api_url')}/rides`,
		RIDES_WS: `${getAppConfig('alerts', 'api_url')}/rides/ws`,
	},

	/* * */
	/* AUTH */
	auth: {
		// BASE
		BASE: `${getModuleConfig('auth', 'api_url')}`,

		// AGENCIES
		AGENCIES_DETAIL: (id: string) => `${getModuleConfig('auth', 'api_url')}/agencies/${id}`,
		AGENCIES_DETAIL_LOCK: (id: string) => `${getModuleConfig('auth', 'api_url')}/agencies/${id}/lock`,
		AGENCIES_LIST: `${getModuleConfig('auth', 'api_url')}/agencies`,

		// AUTH
		AUTH_CHANGE_PASSWORD: `${getModuleConfig('auth', 'api_url')}/auth/change-password`,
		AUTH_LOGIN: `${getModuleConfig('auth', 'api_url')}/auth/login`,
		AUTH_LOGOUT: `${getModuleConfig('auth', 'api_url')}/auth/logout`,
		AUTH_SEND_PASSWORD_RESET_EMAIL: `${getModuleConfig('auth', 'api_url')}/auth/send-password-reset-email`,

		// NOTIFICATIONS
		NOTIFICATIONS_DETAIL: (id: string) => `${getModuleConfig('auth', 'api_url')}/notifications/${id}`,
		NOTIFICATIONS_DETAIL_MARK_AS_READ: (id: string) => `${getModuleConfig('auth', 'api_url')}/notifications/${id}/mark-as-read`,
		NOTIFICATIONS_LIST: `${getModuleConfig('auth', 'api_url')}/notifications`,

		// ORGANIZATIONS
		ORGANIZATIONS_DETAIL: (id: string) => `${getModuleConfig('auth', 'api_url')}/organizations/${id}`,
		ORGANIZATIONS_DETAIL_IMAGE: (id: string) => `${getModuleConfig('auth', 'api_url')}/organizations/${id}/image`,
		ORGANIZATIONS_DETAIL_LOCK: (id: string) => `${getModuleConfig('auth', 'api_url')}/organizations/${id}/lock`,
		ORGANIZATIONS_DETAIL_LOGO: (id: string) => `${getModuleConfig('auth', 'api_url')}/organizations/${id}/logo`,
		ORGANIZATIONS_DETAIL_VAR_IMAGE: (id: string, theme: string) => `${getModuleConfig('auth', 'api_url')}/organizations/${id}/${theme}/image`,
		ORGANIZATIONS_LIST: `${getModuleConfig('auth', 'api_url')}/organizations`,

		// PROPOSED-CHANGES
		PROPOSED_CHANGES_DETAIL: (id: string) => `${getModuleConfig('auth', 'api_url')}/proposed-changes/${id}`,
		PROPOSED_CHANGES_LIST: `${getModuleConfig('auth', 'api_url')}/proposed-changes`,

		// ROLES
		ROLES_DETAIL: (id: string) => `${getModuleConfig('auth', 'api_url')}/roles/${id}`,
		ROLES_DETAIL_LOCK: (id: string) => `${getModuleConfig('auth', 'api_url')}/roles/${id}/lock`,
		ROLES_LIST: `${getModuleConfig('auth', 'api_url')}/roles`,

		// USERS
		USERS_DETAIL: (id: string) => `${getModuleConfig('auth', 'api_url')}/users/${id}`,
		USERS_DETAIL_LOCK: (id: string) => `${getModuleConfig('auth', 'api_url')}/users/${id}/lock`,
		USERS_DETAIL_SIMPLIFIED: (id: string) => `${getModuleConfig('auth', 'api_url')}/users/${id}/simplified`,
		USERS_LIST: `${getModuleConfig('auth', 'api_url')}/users`,
		USERS_ME: `${getModuleConfig('auth', 'api_url')}/users/me`,

		// WIKI
		WIKI_DETAIL: (id: string) => `${getModuleConfig('auth', 'api_url')}/wiki/${id}`,
		WIKI_LIST: `${getModuleConfig('auth', 'api_url')}/wiki`,
	},

	/* * */
	/* CONTROLLER */
	controller: {
		// BASE
		BASE: `${getModuleConfig('controller', 'api_url')}`,

		// RIDE-ACCEPTANCE
		ACCEPTANCE_CHANGE_STATUS: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${id}/acceptance/change-status`,
		ACCEPTANCE_COMMENT: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${id}/acceptance/comment`,
		ACCEPTANCE_DETAIL: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${id}/acceptance`,
		ACCEPTANCE_JUSTIFY: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${id}/acceptance/justify`,
		ACCEPTANCE_LOCK: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${id}/acceptance/lock`,

		// RIDES
		RIDES_DETAIL_HASHED_SHAPE: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${id}/hashed-shape`,
		RIDES_DETAIL_HASHED_TRIP: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${id}/hashed-trip`,
		RIDES_DETAIL_REPROCESS: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${id}/reprocess`,
		RIDES_DETAIL_RIDE: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${id}/ride`,
		RIDES_DETAIL_SIMPLIFIED_APEX_LOCATIONS: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${id}/simplified-apex-locations`,
		RIDES_DETAIL_SIMPLIFIED_APEX_ON_BOARD_REFUNDS: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${id}/simplified-apex-on-board-refunds`,
		RIDES_DETAIL_SIMPLIFIED_APEX_ON_BOARD_SALES: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${id}/simplified-apex-on-board-sales`,
		RIDES_DETAIL_SIMPLIFIED_APEX_VALIDATIONS: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${id}/simplified-apex-validations`,
		RIDES_DETAIL_VEHICLE_EVENTS: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${id}/vehicle-events`,
		RIDES_FAVORITES: `${getModuleConfig('controller', 'api_url')}/rides/favorites`,
		RIDES_LIST: `${getModuleConfig('controller', 'api_url')}/rides`,
		RIDES_WS: `${getModuleConfig('controller', 'api_url')}/rides/ws`,
	},

	/* * */
	/* DATES */
	dates: {
		// BASE
		BASE: `${getModuleConfig('dates', 'api_url')}`,

		// ANNOTATIONS
		ANNOTATIONS_DETAIL: (id: string) => `${getModuleConfig('dates', 'api_url')}/annotations/${id}`,
		ANNOTATIONS_DETAIL_LOCK: (id: string) => `${getModuleConfig('dates', 'api_url')}/annotations/${id}/lock`,
		ANNOTATIONS_LIST: `${getModuleConfig('dates', 'api_url')}/annotations`,

		// EVENTS
		EVENTS_DETAIL: (id: string) => `${getModuleConfig('dates', 'api_url')}/events/${id}`,
		EVENTS_DETAIL_LOCK: (id: string) => `${getModuleConfig('dates', 'api_url')}/events/${id}/lock`,
		EVENTS_LIST: `${getModuleConfig('dates', 'api_url')}/events`,

		// HOLIDAYS
		HOLIDAYS_DETAIL: (id: string) => `${getModuleConfig('dates', 'api_url')}/holidays/${id}`,
		HOLIDAYS_DETAIL_LOCK: (id: string) => `${getModuleConfig('dates', 'api_url')}/holidays/${id}/lock`,
		HOLIDAYS_LIST: `${getModuleConfig('dates', 'api_url')}/holidays`,

		// YEAR-PERIODS
		YEAR_PERIODS_CHECK_CONFLICTS: `${getModuleConfig('dates', 'api_url')}/year-periods/check-conflicts`,
		YEAR_PERIODS_DETAIL: (id: string) => `${getModuleConfig('dates', 'api_url')}/year-periods/${id}`,
		YEAR_PERIODS_DETAIL_LOCK: (id: string) => `${getModuleConfig('dates', 'api_url')}/year-periods/${id}/lock`,
		YEAR_PERIODS_LIST: `${getModuleConfig('dates', 'api_url')}/year-periods`,
	},

	/* * */
	/* EXPORTER */
	exporter: {
		// BASE
		BASE: `${getModuleConfig('exporter', 'api_url')}`,

		// EXPORTER
		EXPORTER_DETAIL_DOWNLOAD: (id: string) => `${getModuleConfig('exporter', 'api_url')}/exporter/${id}/download`,
		EXPORTER_LIST: `${getModuleConfig('exporter', 'api_url')}/exporter`,

		// GTFS-MERGED
		GTFS_MERGED_DOWNLOAD: `${getModuleConfig('exporter', 'api_url')}/gtfs-merged/download`,
	},

	/* * */
	/* FLEET */
	fleet: {
		// BASE
		BASE: `${getModuleConfig('fleet', 'api_url')}`,

		// VEHICLES
		VEHICLES_DETAIL: (id: string) => `${getModuleConfig('fleet', 'api_url')}/vehicles/${id}`,
		VEHICLES_DETAIL_LAST_EVENT: (id: string) => `${getModuleConfig('fleet', 'api_url')}/vehicles/${id}/last-event`,
		VEHICLES_DETAIL_LOCK: (id: string) => `${getModuleConfig('fleet', 'api_url')}/vehicles/${id}/lock`,
		VEHICLES_LIST: `${getModuleConfig('fleet', 'api_url')}/vehicles`,
		VEHICLES_POSITIONS: `${getModuleConfig('fleet', 'api_url')}/vehicles/positions`,
	},

	/* * */
	/* LOCATIONS */
	locations: {
		// BASE
		BASE: `${getModuleConfig('locations', 'api_url')}`,

		// LOCATIONS
		LOCATIONS_COORDINATES: `${getModuleConfig('locations', 'api_url')}/locations/coordinates`,
		LOCATIONS_DISTRICTS: `${getModuleConfig('locations', 'api_url')}/locations/districts`,
		LOCATIONS_LOCALITIES: `${getModuleConfig('locations', 'api_url')}/locations/localities`,
		LOCATIONS_MUNICIPALITIES: `${getModuleConfig('locations', 'api_url')}/locations/municipalities`,
		LOCATIONS_PARISHES: `${getModuleConfig('locations', 'api_url')}/locations/parishes`,
	},

	/* * */
	/* OFFER */
	offer: {
		// BASE
		BASE: `${getModuleConfig('offer', 'api_url')}`,

		// FARES
		FARES_DETAIL: (id: string) => `${getModuleConfig('offer', 'api_url')}/fares/${id}`,
		FARES_DETAIL_LOCK: (id: string) => `${getModuleConfig('offer', 'api_url')}/fares/${id}/lock`,
		FARES_LIST: `${getModuleConfig('offer', 'api_url')}/fares`,

		// GTFS
		GTFS_CREATE_EXPORT: `${getModuleConfig('offer', 'api_url')}/gtfs/create-export`,
		GTFS_PARSE: `${getModuleConfig('offer', 'api_url')}/gtfs/parse`,

		// LINES
		LINES_DETAIL: (id: string) => `${getModuleConfig('offer', 'api_url')}/lines/${id}`,
		LINES_DETAIL_LOCK: (id: string) => `${getModuleConfig('offer', 'api_url')}/lines/${id}/lock`,
		LINES_LIST: `${getModuleConfig('offer', 'api_url')}/lines`,

		// PATTERNS
		PATTERNS_DETAIL: (id: string) => `${getModuleConfig('offer', 'api_url')}/patterns/${id}`,
		PATTERNS_DETAIL_COMMENT: (id: string) => `${getModuleConfig('offer', 'api_url')}/patterns/${id}/comment`,
		PATTERNS_DETAIL_IMPORT_GTFS: (id: string) => `${getModuleConfig('offer', 'api_url')}/patterns/${id}/import-gtfs`,
		PATTERNS_DETAIL_LOCK: (id: string) => `${getModuleConfig('offer', 'api_url')}/patterns/${id}/lock`,
		PATTERNS_LIST: `${getModuleConfig('offer', 'api_url')}/patterns`,

		// ROUTES
		ROUTES_DETAIL: (id: string) => `${getModuleConfig('offer', 'api_url')}/routes/${id}`,
		ROUTES_DETAIL_LOCK: (id: string) => `${getModuleConfig('offer', 'api_url')}/routes/${id}/lock`,
		ROUTES_LIST: `${getModuleConfig('offer', 'api_url')}/routes`,

		// TYPOLOGIES
		TYPOLOGIES_DETAIL: (id: string) => `${getModuleConfig('offer', 'api_url')}/typologies/${id}`,
		TYPOLOGIES_DETAIL_LOCK: (id: string) => `${getModuleConfig('offer', 'api_url')}/typologies/${id}/lock`,
		TYPOLOGIES_LIST: `${getModuleConfig('offer', 'api_url')}/typologies`,

		// ZONES
		ZONES_DETAIL: (id: string) => `${getModuleConfig('offer', 'api_url')}/zones/${id}`,
		ZONES_DETAIL_LOCK: (id: string) => `${getModuleConfig('offer', 'api_url')}/zones/${id}/lock`,
		ZONES_LIST: `${getModuleConfig('offer', 'api_url')}/zones`,
	},

	/* * */
	/* PERFORMANCE */
	performance: {
		// BASE
		BASE: `${getModuleConfig('performance', 'api_url')}`,

		// DATES
		DATES_LIST: `${getModuleConfig('performance', 'api_url')}/dates`,

		// METRICS
		METRICS_DETAIL: (id: string) => `${getModuleConfig('performance', 'api_url')}/metrics/${id}`,

		// NETWORK
		NETWORK_LINES: `${getModuleConfig('performance', 'api_url')}/network/lines`,
		NETWORK_PATTERNS: `${getModuleConfig('performance', 'api_url')}/network/patterns`,
	},

	/* * */
	/* PLANS */
	plans: {
		// BASE
		BASE: `${getModuleConfig('plans', 'api_url')}`,

		// PLANS
		PLANS_APPROVED: `${getModuleConfig('plans', 'api_url')}/plans/approved`,
		PLANS_DETAIL: (id: string) => `${getModuleConfig('plans', 'api_url')}/plans/${id}`,
		PLANS_DETAIL_CHANGE_GTFS: (id: string) => `${getModuleConfig('plans', 'api_url')}/plans/${id}/change-gtfs`,
		PLANS_DETAIL_CONTROLLER_REPROCESS: (id: string) => `${getModuleConfig('plans', 'api_url')}/plans/${id}/controller-reprocess`,
		PLANS_DETAIL_LOCK: (id: string) => `${getModuleConfig('plans', 'api_url')}/plans/${id}/lock`,
		PLANS_DETAIL_OPERATION_FILE: (id: string) => `${getModuleConfig('plans', 'api_url')}/plans/${id}/operation-file`,
		PLANS_DETAIL_OPERATION_FILE_DOWNLOAD: (id: string) => `${getModuleConfig('plans', 'api_url')}/plans/${id}/operation-file/download`,
		PLANS_DRT_MODEL: (id: string) => `${getModuleConfig('plans', 'api_url')}/plans/drt-model/${id}`,
		PLANS_LIST: `${getModuleConfig('plans', 'api_url')}/plans`,

		// VALIDATIONS
		VALIDATIONS_DETAIL: (id: string) => `${getModuleConfig('plans', 'api_url')}/validations/${id}`,
		VALIDATIONS_DETAIL_FILE: (id: string) => `${getModuleConfig('plans', 'api_url')}/validations/${id}/file`,
		VALIDATIONS_DETAIL_FILE_DOWNLOAD: (id: string) => `${getModuleConfig('plans', 'api_url')}/validations/${id}/file/download`,
		VALIDATIONS_DETAIL_LOCK: (id: string) => `${getModuleConfig('plans', 'api_url')}/validations/${id}/lock`,
		VALIDATIONS_DETAIL_PROCESSING_STATUS: (id: string) => `${getModuleConfig('plans', 'api_url')}/validations/${id}/processing-status`,
		VALIDATIONS_DETAIL_REQUEST_APPROVAL: (id: string) => `${getModuleConfig('plans', 'api_url')}/validations/${id}/request-approval`,
		VALIDATIONS_LIST: `${getModuleConfig('plans', 'api_url')}/validations`,
	},

	/* * */
	/* STOPS */
	stops: {
		// BASE
		BASE: `${getModuleConfig('stops', 'api_url')}`,

		// STOPS
		STOPS_DETAIL: (id: string) => `${getModuleConfig('stops', 'api_url')}/stops/${id}`,
		STOPS_DETAIL_LOCK: (id: string) => `${getModuleConfig('stops', 'api_url')}/stops/${id}/lock`,
		STOPS_LIST: `${getModuleConfig('stops', 'api_url')}/stops`,
	},
} as const);
