/**
 * This file is auto-generated by the generate-routes.sh script.
 * Do not edit this file manually.
 */

import { getAppConfig } from './app-configs.js';

/* * */

export const PAGE_ROUTES = Object.freeze({
	/* * */
	/* ALERTS */
	alerts: {
		// BASE
		BASE: `${getAppConfig('alerts', 'frontend_url')}`,

		// REALTIME
		REALTIME_DETAIL: (id: string) => `${getAppConfig('alerts', 'frontend_url')}/realtime/${id}`,
		REALTIME_LIST: `${getAppConfig('alerts', 'frontend_url')}/realtime`,

		// SCHEDULED
		SCHEDULED_DETAIL: (id: string) => `${getAppConfig('alerts', 'frontend_url')}/scheduled/${id}`,
		SCHEDULED_LIST: `${getAppConfig('alerts', 'frontend_url')}/scheduled`,
	},

	/* * */
	/* AUTH */
	auth: {
		// BASE
		BASE: `${getAppConfig('auth', 'frontend_url')}`,

		// AGENCIES
		AGENCIES_DETAIL: (id: string) => `${getAppConfig('auth', 'frontend_url')}/agencies/${id}`,
		AGENCIES_LIST: `${getAppConfig('auth', 'frontend_url')}/agencies`,

		// CHANGE_PASSWORD
		CHANGE_PASSWORD_LIST: `${getAppConfig('auth', 'frontend_url')}/change-password`,

		// HOME
		HOME_DETAIL: (id: string) => `${getAppConfig('auth', 'frontend_url')}/home/${id}`,
		HOME_LIST: `${getAppConfig('auth', 'frontend_url')}/home`,

		// LOGIN
		LOGIN_LIST: `${getAppConfig('auth', 'frontend_url')}/login`,

		// ORGANIZATIONS
		ORGANIZATIONS_DETAIL: (id: string) => `${getAppConfig('auth', 'frontend_url')}/organizations/${id}`,
		ORGANIZATIONS_LIST: `${getAppConfig('auth', 'frontend_url')}/organizations`,

		// RESET_PASSWORD
		RESET_PASSWORD_LIST: `${getAppConfig('auth', 'frontend_url')}/reset-password`,

		// ROLES
		ROLES_DETAIL: (id: string) => `${getAppConfig('auth', 'frontend_url')}/roles/${id}`,
		ROLES_LIST: `${getAppConfig('auth', 'frontend_url')}/roles`,

		// USERS
		USERS_DETAIL: (id: string) => `${getAppConfig('auth', 'frontend_url')}/users/${id}`,
		USERS_LIST: `${getAppConfig('auth', 'frontend_url')}/users`,
	},

	/* * */
	/* CONTROLLER */
	controller: {
		// BASE
		BASE: `${getAppConfig('controller', 'frontend_url')}`,

		// RIDES
		RIDES_DETAIL: (id: string) => `${getAppConfig('controller', 'frontend_url')}/rides/${id}`,
		RIDES_LIST: `${getAppConfig('controller', 'frontend_url')}/rides`,
	},

	/* * */
	/* DATES */
	dates: {
		// BASE
		BASE: `${getAppConfig('dates', 'frontend_url')}`,

		// ANNOTATIONS
		ANNOTATIONS_DETAIL: (id: string) => `${getAppConfig('dates', 'frontend_url')}/annotations/${id}`,
		ANNOTATIONS_LIST: `${getAppConfig('dates', 'frontend_url')}/annotations`,
	},

	/* * */
	/* PERFORMANCE */
	performance: {
		// BASE
		BASE: `${getAppConfig('performance', 'frontend_url')}`,

		// AREAS_1
		AREAS_1_LIST: `${getAppConfig('performance', 'frontend_url')}/areas/1`,

		// AREAS_2
		AREAS_2_LIST: `${getAppConfig('performance', 'frontend_url')}/areas/2`,

		// DEMAND_DEMAND_BY
		DEMAND_DEMAND_BY_LIST: `${getAppConfig('performance', 'frontend_url')}/demand/demand-by`,

		// DEMAND
		DEMAND_LIST: `${getAppConfig('performance', 'frontend_url')}/demand`,

		// SUPPLY
		SUPPLY_LIST: `${getAppConfig('performance', 'frontend_url')}/supply`,
	},

	/* * */
	/* PLANS */
	plans: {
		// BASE
		BASE: `${getAppConfig('plans', 'frontend_url')}`,

		// APPROVED
		APPROVED_DETAIL: (id: string) => `${getAppConfig('plans', 'frontend_url')}/approved/${id}`,
		APPROVED_LIST: `${getAppConfig('plans', 'frontend_url')}/approved`,

		// VALIDATIONS
		VALIDATIONS_DETAIL: (id: string) => `${getAppConfig('plans', 'frontend_url')}/validations/${id}`,
		VALIDATIONS_LIST: `${getAppConfig('plans', 'frontend_url')}/validations`,
	},

	/* * */
	/* STOPS */
	stops: {
		// BASE
		BASE: `${getAppConfig('stops', 'frontend_url')}`,

		// STOPS
		STOPS_DETAIL: (id: string) => `${getAppConfig('stops', 'frontend_url')}/${id}`,
		STOPS_LIST: `${getAppConfig('stops', 'frontend_url')}`,
	},
} as const);

export const API_ROUTES = Object.freeze({
	/* * */
	/* ALERTS */
	alerts: {
		// BASE
		BASE: `${getAppConfig('alerts', 'api_url')}`,

		// ALERTS
		ALERTS_DETAIL: (id: string) => `${getAppConfig('alerts', 'api_url')}/alerts/${id}`,
		ALERTS_DETAIL_IMAGE: (id: string) => `${getAppConfig('alerts', 'api_url')}/alerts/${id}/image`,
		ALERTS_GTFS: `${getAppConfig('alerts', 'api_url')}/alerts/gtfs`,
		ALERTS_LIST: `${getAppConfig('alerts', 'api_url')}/alerts`,

		// RIDES
		RIDES_LIST: `${getAppConfig('alerts', 'api_url')}/rides`,
		RIDES_SELECTED: `${getAppConfig('alerts', 'api_url')}/rides/selected`,
	},

	/* * */
	/* AUTH */
	auth: {
		// BASE
		BASE: `${getAppConfig('auth', 'api_url')}`,

		// AGENCIES
		AGENCIES_DETAIL: (id: string) => `${getAppConfig('auth', 'api_url')}/agencies/${id}`,
		AGENCIES_LIST: `${getAppConfig('auth', 'api_url')}/agencies`,

		// AUTH
		AUTH_CHANGE_PASSWORD: `${getAppConfig('auth', 'api_url')}/auth/change-password`,
		AUTH_LOGIN: `${getAppConfig('auth', 'api_url')}/auth/login`,
		AUTH_LOGOUT: `${getAppConfig('auth', 'api_url')}/auth/logout`,
		AUTH_SEND_PASSWORD_RESET_EMAIL: `${getAppConfig('auth', 'api_url')}/auth/send-password-reset-email`,

		// NOTIFICATIONS
		NOTIFICATIONS_DETAIL: (id: string) => `${getAppConfig('auth', 'api_url')}/notifications/${id}`,
		NOTIFICATIONS_DETAIL_MARK_AS_READ: (id: string) => `${getAppConfig('auth', 'api_url')}/notifications/${id}/mark-as-read`,
		NOTIFICATIONS_LIST: `${getAppConfig('auth', 'api_url')}/notifications`,

		// ORGANIZATIONS
		ORGANIZATIONS_DETAIL: (id: string) => `${getAppConfig('auth', 'api_url')}/organizations/${id}`,
		ORGANIZATIONS_DETAIL_IMAGE: (id: string) => `${getAppConfig('auth', 'api_url')}/organizations/${id}/image`,
		ORGANIZATIONS_DETAIL_LOGO: (id: string) => `${getAppConfig('auth', 'api_url')}/organizations/${id}/logo`,
		ORGANIZATIONS_DETAIL_VAR_IMAGE: (id: string, theme: string) => `${getAppConfig('auth', 'api_url')}/organizations/${id}/${theme}/image`,
		ORGANIZATIONS_LIST: `${getAppConfig('auth', 'api_url')}/organizations`,

		// PROPOSED-CHANGES
		PROPOSED_CHANGES_DETAIL: (id: string) => `${getAppConfig('auth', 'api_url')}/proposed-changes/${id}`,
		PROPOSED_CHANGES_LIST: `${getAppConfig('auth', 'api_url')}/proposed-changes`,

		// ROLES
		ROLES_DETAIL: (id: string) => `${getAppConfig('auth', 'api_url')}/roles/${id}`,
		ROLES_LIST: `${getAppConfig('auth', 'api_url')}/roles`,

		// USERS
		USERS_DETAIL: (id: string) => `${getAppConfig('auth', 'api_url')}/users/${id}`,
		USERS_DETAIL_LOCK: (id: string) => `${getAppConfig('auth', 'api_url')}/users/${id}/lock`,
		USERS_LIST: `${getAppConfig('auth', 'api_url')}/users`,
		USERS_ME: `${getAppConfig('auth', 'api_url')}/users/me`,

		// WIKI
		WIKI_DETAIL: (id: string) => `${getAppConfig('auth', 'api_url')}/wiki/${id}`,
		WIKI_LIST: `${getAppConfig('auth', 'api_url')}/wiki`,
	},

	/* * */
	/* CONTROLLER */
	controller: {
		// BASE
		BASE: `${getAppConfig('controller', 'api_url')}`,

		// RIDE-ACCEPTANCE
		ACCEPTANCE_CHANGE_STATUS: (id: string) => `${getAppConfig('controller', 'api_url')}/rides/${id}/acceptance/change-status`,
		ACCEPTANCE_COMMENT: (id: string) => `${getAppConfig('controller', 'api_url')}/rides/${id}/acceptance/comment`,
		ACCEPTANCE_DETAIL: (id: string) => `${getAppConfig('controller', 'api_url')}/rides/${id}/acceptance`,
		ACCEPTANCE_JUSTIFY: (id: string) => `${getAppConfig('controller', 'api_url')}/rides/${id}/acceptance/justify`,
		ACCEPTANCE_LOCK: (id: string) => `${getAppConfig('controller', 'api_url')}/rides/${id}/acceptance/lock`,

		// RIDES
		RIDES_DETAIL_HASHED_SHAPE: (id: string) => `${getAppConfig('controller', 'api_url')}/rides/${id}/hashed-shape`,
		RIDES_DETAIL_HASHED_TRIP: (id: string) => `${getAppConfig('controller', 'api_url')}/rides/${id}/hashed-trip`,
		RIDES_DETAIL_REPROCESS: (id: string) => `${getAppConfig('controller', 'api_url')}/rides/${id}/reprocess`,
		RIDES_DETAIL_RIDE: (id: string) => `${getAppConfig('controller', 'api_url')}/rides/${id}/ride`,
		RIDES_DETAIL_SIMPLIFIED_APEX_LOCATIONS: (id: string) => `${getAppConfig('controller', 'api_url')}/rides/${id}/simplified-apex-locations`,
		RIDES_DETAIL_SIMPLIFIED_APEX_ON_BOARD_REFUNDS: (id: string) => `${getAppConfig('controller', 'api_url')}/rides/${id}/simplified-apex-on-board-refunds`,
		RIDES_DETAIL_SIMPLIFIED_APEX_ON_BOARD_SALES: (id: string) => `${getAppConfig('controller', 'api_url')}/rides/${id}/simplified-apex-on-board-sales`,
		RIDES_DETAIL_SIMPLIFIED_APEX_VALIDATIONS: (id: string) => `${getAppConfig('controller', 'api_url')}/rides/${id}/simplified-apex-validations`,
		RIDES_DETAIL_VEHICLE_EVENTS: (id: string) => `${getAppConfig('controller', 'api_url')}/rides/${id}/vehicle-events`,
		RIDES_LIST: `${getAppConfig('controller', 'api_url')}/rides`,
		RIDES_WS: `${getAppConfig('controller', 'api_url')}/rides/ws`,
	},

	/* * */
	/* DATES */
	dates: {
		// BASE
		BASE: `${getAppConfig('dates', 'api_url')}`,

		// ANNOTATIONS
		ANNOTATIONS_DETAIL: (id: string) => `${getAppConfig('dates', 'api_url')}/annotations/${id}`,
		ANNOTATIONS_DETAIL_TOGGLE_LOCK: (id: string) => `${getAppConfig('dates', 'api_url')}/annotations/${id}/toggle-lock`,
		ANNOTATIONS_LIST: `${getAppConfig('dates', 'api_url')}/annotations`,
	},

	/* * */
	/* EXPORTER */
	exporter: {
		// BASE
		BASE: `${getAppConfig('exporter', 'api_url')}`,

		// EXPORTER
		EXPORTER_DETAIL_DOWNLOAD: (id: string) => `${getAppConfig('exporter', 'api_url')}/exporter/${id}/download`,
		EXPORTER_LIST: `${getAppConfig('exporter', 'api_url')}/exporter`,

		// GTFS-MERGED
		GTFS_MERGED_DOWNLOAD: `${getAppConfig('exporter', 'api_url')}/gtfs-merged/download`,
	},

	/* * */
	/* LOCATIONS */
	locations: {
		// BASE
		BASE: `${getAppConfig('locations', 'api_url')}`,

		// LOCATIONS
		LOCATIONS_COORDINATES: `${getAppConfig('locations', 'api_url')}/locations/coordinates`,
		LOCATIONS_DISTRICTS: `${getAppConfig('locations', 'api_url')}/locations/districts`,
		LOCATIONS_LOCALITIES: `${getAppConfig('locations', 'api_url')}/locations/localities`,
		LOCATIONS_MUNICIPALITIES: `${getAppConfig('locations', 'api_url')}/locations/municipalities`,
		LOCATIONS_PARISHES: `${getAppConfig('locations', 'api_url')}/locations/parishes`,
	},

	/* * */
	/* PERFORMANCE */
	performance: {
		// BASE
		BASE: `${getAppConfig('performance', 'api_url')}`,

		// DATES
		DATES_LIST: `${getAppConfig('performance', 'api_url')}/dates`,

		// METRICS
		METRICS_DETAIL: (id: string) => `${getAppConfig('performance', 'api_url')}/metrics/${id}`,

		// NETWORK
		NETWORK_LINES: `${getAppConfig('performance', 'api_url')}/network/lines`,
		NETWORK_PATTERNS: `${getAppConfig('performance', 'api_url')}/network/patterns`,
	},

	/* * */
	/* PLANS */
	plans: {
		// BASE
		BASE: `${getAppConfig('plans', 'api_url')}`,

		// PLANS
		PLANS_APPROVED: `${getAppConfig('plans', 'api_url')}/plans/approved`,
		PLANS_DETAIL: (id: string) => `${getAppConfig('plans', 'api_url')}/plans/${id}`,
		PLANS_DETAIL_CHANGE_GTFS: (id: string) => `${getAppConfig('plans', 'api_url')}/plans/${id}/change-gtfs`,
		PLANS_DETAIL_CONTROLLER_REPROCESS: (id: string) => `${getAppConfig('plans', 'api_url')}/plans/${id}/controller-reprocess`,
		PLANS_DETAIL_OPERATION_FILE: (id: string) => `${getAppConfig('plans', 'api_url')}/plans/${id}/operation-file`,
		PLANS_DETAIL_TOGGLE_LOCK: (id: string) => `${getAppConfig('plans', 'api_url')}/plans/${id}/toggle-lock`,
		PLANS_DRT_MODEL_: (id: string) => `${getAppConfig('plans', 'api_url')}/ID:/plans/api/plans/drt-model/${id}`,
		PLANS_LIST: `${getAppConfig('plans', 'api_url')}/plans`,

		// VALIDATIONS
		VALIDATIONS_DETAIL: (id: string) => `${getAppConfig('plans', 'api_url')}/validations/${id}`,
		VALIDATIONS_DETAIL_FILE: (id: string) => `${getAppConfig('plans', 'api_url')}/validations/${id}/file`,
		VALIDATIONS_DETAIL_REQUEST_APPROVAL: (id: string) => `${getAppConfig('plans', 'api_url')}/validations/${id}/request-approval`,
		VALIDATIONS_LIST: `${getAppConfig('plans', 'api_url')}/validations`,
	},

	/* * */
	/* STOPS */
	stops: {
		// BASE
		BASE: `${getAppConfig('stops', 'api_url')}`,

		// STOPS
		STOPS_DETAIL: (id: string) => `${getAppConfig('stops', 'api_url')}/stops/${id}`,
		STOPS_DETAIL_LOCK: (id: string) => `${getAppConfig('stops', 'api_url')}/stops/${id}/lock`,
		STOPS_LIST: `${getAppConfig('stops', 'api_url')}/stops`,
	},
} as const);
