/**
 * This file is auto-generated by the generate-routes.sh script.
 * Do not edit this file manually.
 */

import { getModuleConfig } from './app-configs.js';

/* * */

export const PAGE_ROUTES = Object.freeze({

	alerts: {
		// BASE
		BASE: `${getModuleConfig('alerts', 'frontend_url')}`,

		// ALERTS
		ALERTS_DETAIL: (alertId: string) => `${getModuleConfig('alerts', 'frontend_url')}/${encodeURIComponent(alertId)}`,
		ALERTS_LIST: `${getModuleConfig('alerts', 'frontend_url')}`,
	},

	controller: {
		// BASE
		BASE: `${getModuleConfig('controller', 'frontend_url')}`,

		// RIDES
		RIDES_DETAIL: (rideId: string) => `${getModuleConfig('controller', 'frontend_url')}/rides/${encodeURIComponent(rideId)}`,
		RIDES_LIST: `${getModuleConfig('controller', 'frontend_url')}/rides`,

		// SAMS
		SAMS_DETAIL: (id: string) => `${getModuleConfig('controller', 'frontend_url')}/sams/${encodeURIComponent(id)}`,
		SAMS_LIST: `${getModuleConfig('controller', 'frontend_url')}/sams`,
	},

	core: {
		// BASE
		BASE: `${getModuleConfig('core', 'frontend_url')}`,

		// AGENCIES
		AGENCIES_DETAIL: (agencyId: string) => `${getModuleConfig('core', 'frontend_url')}/agencies/${encodeURIComponent(agencyId)}`,
		AGENCIES_LIST: `${getModuleConfig('core', 'frontend_url')}/agencies`,

		// CHANGE_PASSWORD
		CHANGE_PASSWORD_LIST: `${getModuleConfig('core', 'frontend_url')}/change-password`,

		// HOME
		HOME_LIST: `${getModuleConfig('core', 'frontend_url')}/home`,

		// LOGIN
		LOGIN_LIST: `${getModuleConfig('core', 'frontend_url')}/login`,

		// ORGANIZATIONS
		ORGANIZATIONS_DETAIL: (organizationId: string) => `${getModuleConfig('core', 'frontend_url')}/organizations/${encodeURIComponent(organizationId)}`,
		ORGANIZATIONS_LIST: `${getModuleConfig('core', 'frontend_url')}/organizations`,

		// RESET_PASSWORD
		RESET_PASSWORD_LIST: `${getModuleConfig('core', 'frontend_url')}/reset-password`,

		// ROLES
		ROLES_DETAIL: (roleId: string) => `${getModuleConfig('core', 'frontend_url')}/roles/${encodeURIComponent(roleId)}`,
		ROLES_LIST: `${getModuleConfig('core', 'frontend_url')}/roles`,

		// USERS
		USERS_DETAIL: (userId: string) => `${getModuleConfig('core', 'frontend_url')}/users/${encodeURIComponent(userId)}`,
		USERS_LIST: `${getModuleConfig('core', 'frontend_url')}/users`,
	},

	dates: {
		// BASE
		BASE: `${getModuleConfig('dates', 'frontend_url')}`,

		// ANNOTATIONS
		ANNOTATIONS_DETAIL: (id: string) => `${getModuleConfig('dates', 'frontend_url')}/annotations/${encodeURIComponent(id)}`,
		ANNOTATIONS_LIST: `${getModuleConfig('dates', 'frontend_url')}/annotations`,

		// CALENDAR
		CALENDAR_LIST: `${getModuleConfig('dates', 'frontend_url')}/calendar`,

		// EVENTS
		EVENTS_DETAIL: (id: string) => `${getModuleConfig('dates', 'frontend_url')}/events/${encodeURIComponent(id)}`,
		EVENTS_LIST: `${getModuleConfig('dates', 'frontend_url')}/events`,

		// HOLIDAYS
		HOLIDAYS_DETAIL: (id: string) => `${getModuleConfig('dates', 'frontend_url')}/holidays/${encodeURIComponent(id)}`,
		HOLIDAYS_LIST: `${getModuleConfig('dates', 'frontend_url')}/holidays`,

		// YEAR_PERIODS
		YEAR_PERIODS_DETAIL: (id: string) => `${getModuleConfig('dates', 'frontend_url')}/year-periods/${encodeURIComponent(id)}`,
		YEAR_PERIODS_LIST: `${getModuleConfig('dates', 'frontend_url')}/year-periods`,
	},

	fleet: {
		// BASE
		BASE: `${getModuleConfig('fleet', 'frontend_url')}`,

		// VEHICLES
		VEHICLES_DETAIL: (id: string) => `${getModuleConfig('fleet', 'frontend_url')}/vehicles/${encodeURIComponent(id)}`,
		VEHICLES_LIST: `${getModuleConfig('fleet', 'frontend_url')}/vehicles`,
	},

	infrastructure: {
		// BASE
		BASE: `${getModuleConfig('infrastructure', 'frontend_url')}`,

		// INFRASTRUCTURE
		INFRASTRUCTURE_DETAIL: (id: string) => `${getModuleConfig('infrastructure', 'frontend_url')}/${encodeURIComponent(id)}`,
		INFRASTRUCTURE_LIST: `${getModuleConfig('infrastructure', 'frontend_url')}`,
	},

	offer: {
		// BASE
		BASE: `${getModuleConfig('offer', 'frontend_url')}`,

		// FARES
		FARES_DETAIL: (id: string) => `${getModuleConfig('offer', 'frontend_url')}/fares/${encodeURIComponent(id)}`,
		FARES_LIST: `${getModuleConfig('offer', 'frontend_url')}/fares`,

		// LINES
		LINES_DETAIL: (id: string) => `${getModuleConfig('offer', 'frontend_url')}/lines/${encodeURIComponent(id)}`,
		LINES_LIST: `${getModuleConfig('offer', 'frontend_url')}/lines`,

		// PATTERN
		PATTERN_DETAIL: (id: string, patternId: string, routeId: string) => `${getModuleConfig('offer', 'frontend_url')}/lines/${encodeURIComponent(id)}/${encodeURIComponent(routeId)}/${encodeURIComponent(patternId)}`,

		// ROUTE
		ROUTE_DETAIL: (id: string, routeId: string) => `${getModuleConfig('offer', 'frontend_url')}/lines/${encodeURIComponent(id)}/${encodeURIComponent(routeId)}`,

		// TYPOLOGIES
		TYPOLOGIES_DETAIL: (id: string) => `${getModuleConfig('offer', 'frontend_url')}/typologies/${encodeURIComponent(id)}`,
		TYPOLOGIES_LIST: `${getModuleConfig('offer', 'frontend_url')}/typologies`,

		// ZONES
		ZONES_DETAIL: (id: string) => `${getModuleConfig('offer', 'frontend_url')}/zones/${encodeURIComponent(id)}`,
		ZONES_LIST: `${getModuleConfig('offer', 'frontend_url')}/zones`,
	},

	performance: {
		// BASE
		BASE: `${getModuleConfig('performance', 'frontend_url')}`,

		// AREAS_1
		AREAS_1_LIST: `${getModuleConfig('performance', 'frontend_url')}/areas/1`,

		// AREAS_2
		AREAS_2_LIST: `${getModuleConfig('performance', 'frontend_url')}/areas/2`,

		// DEMAND_DEMAND_BY
		DEMAND_DEMAND_BY_LIST: `${getModuleConfig('performance', 'frontend_url')}/demand/demand-by`,

		// DEMAND
		DEMAND_LIST: `${getModuleConfig('performance', 'frontend_url')}/demand`,

		// SUPPLY
		SUPPLY_LIST: `${getModuleConfig('performance', 'frontend_url')}/supply`,
	},

	plans: {
		// BASE
		BASE: `${getModuleConfig('plans', 'frontend_url')}`,

		// APPROVED
		APPROVED_DETAIL: (id: string) => `${getModuleConfig('plans', 'frontend_url')}/approved/${encodeURIComponent(id)}`,
		APPROVED_LIST: `${getModuleConfig('plans', 'frontend_url')}/approved`,

		// VALIDATIONS
		VALIDATIONS_DETAIL: (id: string) => `${getModuleConfig('plans', 'frontend_url')}/validations/${encodeURIComponent(id)}`,
		VALIDATIONS_LIST: `${getModuleConfig('plans', 'frontend_url')}/validations`,
	},

	root: {
		// BASE
		BASE: `${getModuleConfig('root', 'frontend_url')}`,

		// REFERENCE
		REFERENCE_LIST: `${getModuleConfig('root', 'frontend_url')}/reference`,
	},
} as const);

export const API_ROUTES = Object.freeze({

	alerts: {
		// BASE
		BASE: `${getModuleConfig('alerts', 'api_url')}`,

		// ALERTS
		ALERTS_COMPOSE: `${getModuleConfig('alerts', 'api_url')}/alerts/compose`,
		ALERTS_CREATE: `${getModuleConfig('alerts', 'api_url')}/alerts/create`,
		ALERTS_DETAIL: (id: string) => `${getModuleConfig('alerts', 'api_url')}/alerts/${encodeURIComponent(id)}`,
		ALERTS_DETAIL_DUPLICATE: (id: string) => `${getModuleConfig('alerts', 'api_url')}/alerts/${encodeURIComponent(id)}/duplicate`,
		ALERTS_DETAIL_IMAGE: (id: string) => `${getModuleConfig('alerts', 'api_url')}/alerts/${encodeURIComponent(id)}/image`,
		ALERTS_DETAIL_LOCK: (id: string) => `${getModuleConfig('alerts', 'api_url')}/alerts/${encodeURIComponent(id)}/lock`,
		ALERTS_LIST: `${getModuleConfig('alerts', 'api_url')}/alerts/list`,
		ALERTS_LIST_AGENCIES: `${getModuleConfig('alerts', 'api_url')}/alerts/list-agencies`,

		// OPERATION
		OPERATION_LINES: `${getModuleConfig('alerts', 'api_url')}/operation/lines`,
		OPERATION_RIDES: `${getModuleConfig('alerts', 'api_url')}/operation/rides`,
		OPERATION_STOPS: `${getModuleConfig('alerts', 'api_url')}/operation/stops`,
	},

	controller: {
		// BASE
		BASE: `${getModuleConfig('controller', 'api_url')}`,

		// RIDE-ACCEPTANCE
		ACCEPTANCE_CHANGE_STATUS: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${encodeURIComponent(id)}/acceptance/change-status`,
		ACCEPTANCE_COMMENT: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${encodeURIComponent(id)}/acceptance/comment`,
		ACCEPTANCE_DETAIL: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${encodeURIComponent(id)}/acceptance`,
		ACCEPTANCE_JUSTIFY: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${encodeURIComponent(id)}/acceptance/justify`,
		ACCEPTANCE_LOCK: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${encodeURIComponent(id)}/acceptance/lock`,

		// RIDES
		RIDES_DETAIL_ANALYSES: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${encodeURIComponent(id)}/analyses`,
		RIDES_DETAIL_APEX_BANKING_TAPS: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${encodeURIComponent(id)}/apex-banking-taps`,
		RIDES_DETAIL_APEX_LOCATIONS: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${encodeURIComponent(id)}/apex-locations`,
		RIDES_DETAIL_APEX_REFUNDS: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${encodeURIComponent(id)}/apex-refunds`,
		RIDES_DETAIL_APEX_SALES: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${encodeURIComponent(id)}/apex-sales`,
		RIDES_DETAIL_APEX_VALIDATIONS: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${encodeURIComponent(id)}/apex-validations`,
		RIDES_DETAIL_HASHED_TRIP: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${encodeURIComponent(id)}/hashed-trip`,
		RIDES_DETAIL_REPROCESS: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${encodeURIComponent(id)}/reprocess`,
		RIDES_DETAIL_RIDE: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${encodeURIComponent(id)}/ride`,
		RIDES_DETAIL_VEHICLE_EVENTS: (id: string) => `${getModuleConfig('controller', 'api_url')}/rides/${encodeURIComponent(id)}/vehicle-events`,
		RIDES_FAVORITES: `${getModuleConfig('controller', 'api_url')}/rides/favorites`,
		RIDES_LIST: `${getModuleConfig('controller', 'api_url')}/rides/list`,

		// SAMS
		SAMS_APEX_VERSIONS: `${getModuleConfig('controller', 'api_url')}/sams/apex-versions`,
		SAMS_BASE: `${getModuleConfig('controller', 'api_url')}/sams/base`,
		SAMS_DETAIL: (id: string) => `${getModuleConfig('controller', 'api_url')}/sams/${encodeURIComponent(id)}`,
		SAMS_EXPORT_ANALYSIS: `${getModuleConfig('controller', 'api_url')}/sams/export/analysis`,
		SAMS_FAVORITES: `${getModuleConfig('controller', 'api_url')}/sams/favorites`,
		SAMS_LIST: `${getModuleConfig('controller', 'api_url')}/sams`,
		SAMS_TIMELINE_SUMMARY: `${getModuleConfig('controller', 'api_url')}/sams/timeline-summary`,
	},

	core: {
		// BASE
		BASE: `${getModuleConfig('core', 'api_url')}`,

		// AGENCIES
		AGENCIES_DETAIL: (id: string) => `${getModuleConfig('core', 'api_url')}/agencies/${encodeURIComponent(id)}`,
		AGENCIES_DETAIL_LOCK: (id: string) => `${getModuleConfig('core', 'api_url')}/agencies/${encodeURIComponent(id)}/lock`,
		AGENCIES_LIST: `${getModuleConfig('core', 'api_url')}/agencies`,

		// APP-CONFIGS
		APP_CONFIGS_APP_BANNER: `${getModuleConfig('core', 'api_url')}/app-configs/app-banner`,

		// AUTH
		AUTH_CHANGE_PASSWORD: `${getModuleConfig('core', 'api_url')}/auth/change-password`,
		AUTH_LOGIN: `${getModuleConfig('core', 'api_url')}/auth/login`,
		AUTH_LOGOUT: `${getModuleConfig('core', 'api_url')}/auth/logout`,
		AUTH_SEND_PASSWORD_RESET_EMAIL: `${getModuleConfig('core', 'api_url')}/auth/send-password-reset-email`,

		// HOME
		HOME_QUICK_LINKS: `${getModuleConfig('core', 'api_url')}/home/quick-links`,

		// ORGANIZATIONS
		ORGANIZATIONS_CREATE: `${getModuleConfig('core', 'api_url')}/organizations/create`,
		ORGANIZATIONS_DETAIL_DELETE: (id: string) => `${getModuleConfig('core', 'api_url')}/organizations/${encodeURIComponent(id)}/delete`,
		ORGANIZATIONS_DETAIL_DELETE_IMAGE_VAR: (id: string, theme: string) => `${getModuleConfig('core', 'api_url')}/organizations/${encodeURIComponent(id)}/delete/image/${encodeURIComponent(theme)}`,
		ORGANIZATIONS_DETAIL_DETAIL: (id: string) => `${getModuleConfig('core', 'api_url')}/organizations/${encodeURIComponent(id)}/detail`,
		ORGANIZATIONS_DETAIL_DETAIL_IMAGE_VAR: (id: string, theme: string) => `${getModuleConfig('core', 'api_url')}/organizations/${encodeURIComponent(id)}/detail/image/${encodeURIComponent(theme)}`,
		ORGANIZATIONS_DETAIL_LOCK: (id: string) => `${getModuleConfig('core', 'api_url')}/organizations/${encodeURIComponent(id)}/lock`,
		ORGANIZATIONS_DETAIL_UPDATE: (id: string) => `${getModuleConfig('core', 'api_url')}/organizations/${encodeURIComponent(id)}/update`,
		ORGANIZATIONS_DETAIL_UPDATE_IMAGE: (id: string) => `${getModuleConfig('core', 'api_url')}/organizations/${encodeURIComponent(id)}/update/image`,
		ORGANIZATIONS_LIST: `${getModuleConfig('core', 'api_url')}/organizations/list`,

		// PLATFORM
		PLATFORM_AGENCIES: `${getModuleConfig('core', 'api_url')}/platform/agencies`,
		PLATFORM_DOWNLOADS: `${getModuleConfig('core', 'api_url')}/platform/downloads`,
		PLATFORM_ME: `${getModuleConfig('core', 'api_url')}/platform/me`,
		PLATFORM_NOTIFICATIONS: `${getModuleConfig('core', 'api_url')}/platform/notifications`,
		PLATFORM_SIDEBAR_LOGO: `${getModuleConfig('core', 'api_url')}/platform/sidebar-logo`,

		// ROLES
		ROLES_CREATE: `${getModuleConfig('core', 'api_url')}/roles/create`,
		ROLES_DELETE: (id: string) => `${getModuleConfig('core', 'api_url')}/roles/delete/${encodeURIComponent(id)}`,
		ROLES_DETAIL: (id: string) => `${getModuleConfig('core', 'api_url')}/roles/${encodeURIComponent(id)}`,
		ROLES_LIST: `${getModuleConfig('core', 'api_url')}/roles/list`,
		ROLES_LIST_AGENCIES: `${getModuleConfig('core', 'api_url')}/roles/list-agencies`,
		ROLES_LOCK: (id: string) => `${getModuleConfig('core', 'api_url')}/roles/lock/${encodeURIComponent(id)}`,
		ROLES_UPDATE: (id: string) => `${getModuleConfig('core', 'api_url')}/roles/update/${encodeURIComponent(id)}`,

		// USERS
		USERS_CREATE: `${getModuleConfig('core', 'api_url')}/users/create`,
		USERS_DELETE: (id: string) => `${getModuleConfig('core', 'api_url')}/users/delete/${encodeURIComponent(id)}`,
		USERS_DETAIL: (id: string) => `${getModuleConfig('core', 'api_url')}/users/${encodeURIComponent(id)}`,
		USERS_DETAIL_SIMPLIFIED: (id: string) => `${getModuleConfig('core', 'api_url')}/users/${encodeURIComponent(id)}/simplified`,
		USERS_LIST: `${getModuleConfig('core', 'api_url')}/users/list`,
		USERS_LIST_AGENCIES: `${getModuleConfig('core', 'api_url')}/users/list-agencies`,
		USERS_LIST_ORGANIZATIONS: `${getModuleConfig('core', 'api_url')}/users/list-organizations`,
		USERS_LIST_ROLES: `${getModuleConfig('core', 'api_url')}/users/list-roles`,
		USERS_LOCK: (id: string) => `${getModuleConfig('core', 'api_url')}/users/lock/${encodeURIComponent(id)}`,
		USERS_UPDATE: (id: string) => `${getModuleConfig('core', 'api_url')}/users/update/${encodeURIComponent(id)}`,
	},

	dates: {
		// BASE
		BASE: `${getModuleConfig('dates', 'api_url')}`,

		// ANNOTATIONS
		ANNOTATIONS_DETAIL: (id: string) => `${getModuleConfig('dates', 'api_url')}/annotations/${encodeURIComponent(id)}`,
		ANNOTATIONS_DETAIL_LOCK: (id: string) => `${getModuleConfig('dates', 'api_url')}/annotations/${encodeURIComponent(id)}/lock`,
		ANNOTATIONS_LIST: `${getModuleConfig('dates', 'api_url')}/annotations/list`,
		ANNOTATIONS_LIST_AGENCIES: `${getModuleConfig('dates', 'api_url')}/annotations/list-agencies`,

		// EVENTS
		EVENTS_DETAIL: (id: string) => `${getModuleConfig('dates', 'api_url')}/events/${encodeURIComponent(id)}`,
		EVENTS_DETAIL_LOCK: (id: string) => `${getModuleConfig('dates', 'api_url')}/events/${encodeURIComponent(id)}/lock`,
		EVENTS_LIST: `${getModuleConfig('dates', 'api_url')}/events`,

		// HOLIDAYS
		HOLIDAYS_DETAIL: (id: string) => `${getModuleConfig('dates', 'api_url')}/holidays/${encodeURIComponent(id)}`,
		HOLIDAYS_DETAIL_LOCK: (id: string) => `${getModuleConfig('dates', 'api_url')}/holidays/${encodeURIComponent(id)}/lock`,
		HOLIDAYS_LIST: `${getModuleConfig('dates', 'api_url')}/holidays`,

		// YEAR-PERIODS
		YEAR_PERIODS_CHECK_CONFLICTS: `${getModuleConfig('dates', 'api_url')}/year-periods/check-conflicts`,
		YEAR_PERIODS_DETAIL: (id: string) => `${getModuleConfig('dates', 'api_url')}/year-periods/${encodeURIComponent(id)}`,
		YEAR_PERIODS_DETAIL_LOCK: (id: string) => `${getModuleConfig('dates', 'api_url')}/year-periods/${encodeURIComponent(id)}/lock`,
		YEAR_PERIODS_LIST: `${getModuleConfig('dates', 'api_url')}/year-periods`,
	},

	exporter: {
		// BASE
		BASE: `${getModuleConfig('exporter', 'api_url')}`,

		// EXPORTER
		EXPORTER_DETAIL_DOWNLOAD: (id: string) => `${getModuleConfig('exporter', 'api_url')}/exporter/${encodeURIComponent(id)}/download`,
		EXPORTER_LIST: `${getModuleConfig('exporter', 'api_url')}/exporter`,
	},

	fleet: {
		// BASE
		BASE: `${getModuleConfig('fleet', 'api_url')}`,

		// VEHICLES
		VEHICLES_DETAIL: (id: string) => `${getModuleConfig('fleet', 'api_url')}/vehicles/${encodeURIComponent(id)}`,
		VEHICLES_DETAIL_LAST_EVENT: (id: string) => `${getModuleConfig('fleet', 'api_url')}/vehicles/${encodeURIComponent(id)}/last-event`,
		VEHICLES_DETAIL_LOCK: (id: string) => `${getModuleConfig('fleet', 'api_url')}/vehicles/${encodeURIComponent(id)}/lock`,
		VEHICLES_LIST: `${getModuleConfig('fleet', 'api_url')}/vehicles`,
	},

	hub: {
		// BASE
		BASE: `${getModuleConfig('hub', 'api_url')}`,

		// ALERTS
		ALERTS_GTFS: `${getModuleConfig('hub', 'api_url')}/v1/alerts/gtfs`,
		ALERTS_GTFS_CM: `${getModuleConfig('hub', 'api_url')}/v1/alerts/gtfs-cm`,
		ALERTS_GTFS_PB: `${getModuleConfig('hub', 'api_url')}/v1/alerts/gtfs.pb`,
		ALERTS_LIST: `${getModuleConfig('hub', 'api_url')}/v1/alerts`,
		ALERTS_RSS: `${getModuleConfig('hub', 'api_url')}/v1/alerts.rss`,

		// DEBUG
		DEBUG_TIME: `${getModuleConfig('hub', 'api_url')}/v1/debug/time`,

		// METRICS
		METRICS_DEMAND_BY_AGENCY_BY_OPERATIONAL_DATE: `${getModuleConfig('hub', 'api_url')}/v1/metrics/demand-by-agency-by-operational-date`,

		// NETWORK
		NETWORK_LINES: `${getModuleConfig('hub', 'api_url')}/v1/network/lines`,
		NETWORK_PATTERNS: (id: string) => `${getModuleConfig('hub', 'api_url')}/v1/network/patterns/${encodeURIComponent(id)}`,
		NETWORK_ROUTES: `${getModuleConfig('hub', 'api_url')}/v1/network/routes`,
		NETWORK_SHAPES: (id: string) => `${getModuleConfig('hub', 'api_url')}/v1/network/shapes/${encodeURIComponent(id)}`,
		NETWORK_STOPS: `${getModuleConfig('hub', 'api_url')}/v1/network/stops`,

		// PLANS
		PLANS_GTFS: `${getModuleConfig('hub', 'api_url')}/v1/plans/gtfs`,
		PLANS_GTFS_CM: `${getModuleConfig('hub', 'api_url')}/v1/plans/gtfs/cm`,
		PLANS_LIST: `${getModuleConfig('hub', 'api_url')}/v1/plans`,

		// REALTIME
		REALTIME_ETA: `${getModuleConfig('hub', 'api_url')}/v1/realtime/eta`,
		REALTIME_ETA_BY_STOP: (id: string) => `${getModuleConfig('hub', 'api_url')}/v1/realtime/eta/by-stop/${encodeURIComponent(id)}`,
		REALTIME_ETA_BY_STOP_GTFS: (id: string) => `${getModuleConfig('hub', 'api_url')}/v1/realtime/eta/by-stop/${encodeURIComponent(id)}/gtfs`,
		REALTIME_ETA_BY_STOP_GTFS_PB: (id: string) => `${getModuleConfig('hub', 'api_url')}/v1/realtime/eta/by-stop/${encodeURIComponent(id)}/gtfs.pb`,
		REALTIME_ETA_BY_TRIP: (id: string) => `${getModuleConfig('hub', 'api_url')}/v1/realtime/eta/by-trip/${encodeURIComponent(id)}`,
		REALTIME_ETA_BY_TRIP_GTFS: (id: string) => `${getModuleConfig('hub', 'api_url')}/v1/realtime/eta/by-trip/${encodeURIComponent(id)}/gtfs`,
		REALTIME_ETA_BY_TRIP_GTFS_PB: (id: string) => `${getModuleConfig('hub', 'api_url')}/v1/realtime/eta/by-trip/${encodeURIComponent(id)}/gtfs.pb`,
		REALTIME_ETA_GTFS: `${getModuleConfig('hub', 'api_url')}/v1/realtime/eta/gtfs`,
		REALTIME_ETA_GTFS_PB: `${getModuleConfig('hub', 'api_url')}/v1/realtime/eta/gtfs.pb`,
		REALTIME_VEHICLES_METADATA: `${getModuleConfig('hub', 'api_url')}/v1/realtime/vehicles/metadata`,
		REALTIME_VEHICLES_POSITIONS: `${getModuleConfig('hub', 'api_url')}/v1/realtime/vehicles/positions`,
		REALTIME_VEHICLES_POSITIONS_GTFS: `${getModuleConfig('hub', 'api_url')}/v1/realtime/vehicles/positions/gtfs`,
		REALTIME_VEHICLES_POSITIONS_GTFS_PB: `${getModuleConfig('hub', 'api_url')}/v1/realtime/vehicles/positions/gtfs.pb`,
	},

	infrastructure: {
		// BASE
		BASE: `${getModuleConfig('infrastructure', 'api_url')}`,

		// STOPS
		STOPS_DETAIL: (id: string) => `${getModuleConfig('infrastructure', 'api_url')}/stops/${encodeURIComponent(id)}`,
		STOPS_DETAIL_LOCK: (id: string) => `${getModuleConfig('infrastructure', 'api_url')}/stops/${encodeURIComponent(id)}/lock`,
		STOPS_LIST: `${getModuleConfig('infrastructure', 'api_url')}/stops`,
		STOPS_TTS: (id: string) => `${getModuleConfig('infrastructure', 'api_url')}/stops/tts/${encodeURIComponent(id)}`,
		STOPS_VALID_ID: `${getModuleConfig('infrastructure', 'api_url')}/stops/valid-id`,
	},

	locations: {
		// BASE
		BASE: `${getModuleConfig('locations', 'api_url')}`,

		// LOCATIONS
		LOCATIONS_DISTRICTS: `${getModuleConfig('locations', 'api_url')}/locations/districts`,
		LOCATIONS_DISTRICTS_DETAIL: (id: string) => `${getModuleConfig('locations', 'api_url')}/locations/districts/${encodeURIComponent(id)}`,
		LOCATIONS_LOCALITIES: `${getModuleConfig('locations', 'api_url')}/locations/localities`,
		LOCATIONS_LOCALITIES_DETAIL: (id: string) => `${getModuleConfig('locations', 'api_url')}/locations/localities/${encodeURIComponent(id)}`,
		LOCATIONS_LOCATION: `${getModuleConfig('locations', 'api_url')}/locations/location`,
		LOCATIONS_MUNICIPALITIES: `${getModuleConfig('locations', 'api_url')}/locations/municipalities`,
		LOCATIONS_MUNICIPALITIES_DETAIL: (id: string) => `${getModuleConfig('locations', 'api_url')}/locations/municipalities/${encodeURIComponent(id)}`,
		LOCATIONS_PARISHES: `${getModuleConfig('locations', 'api_url')}/locations/parishes`,
		LOCATIONS_PARISHES_DETAIL: (id: string) => `${getModuleConfig('locations', 'api_url')}/locations/parishes/${encodeURIComponent(id)}`,
	},

	offer: {
		// BASE
		BASE: `${getModuleConfig('offer', 'api_url')}`,

		// AGENCIES
		AGENCIES_LIST: `${getModuleConfig('offer', 'api_url')}/agencies`,

		// FARES
		FARES_DETAIL: (id: string) => `${getModuleConfig('offer', 'api_url')}/fares/${encodeURIComponent(id)}`,
		FARES_DETAIL_LOCK: (id: string) => `${getModuleConfig('offer', 'api_url')}/fares/${encodeURIComponent(id)}/lock`,
		FARES_LIST: `${getModuleConfig('offer', 'api_url')}/fares`,

		// GTFS
		GTFS_CREATE_EXPORT: `${getModuleConfig('offer', 'api_url')}/gtfs/create-export`,
		GTFS_PARSE: `${getModuleConfig('offer', 'api_url')}/gtfs/parse`,

		// LINES
		LINES_DETAIL: (id: string) => `${getModuleConfig('offer', 'api_url')}/lines/${encodeURIComponent(id)}`,
		LINES_DETAIL_LOCK: (id: string) => `${getModuleConfig('offer', 'api_url')}/lines/${encodeURIComponent(id)}/lock`,
		LINES_LIST: `${getModuleConfig('offer', 'api_url')}/lines`,

		// PATTERNS
		PATTERNS_DETAIL: (id: string) => `${getModuleConfig('offer', 'api_url')}/patterns/${encodeURIComponent(id)}`,
		PATTERNS_DETAIL_COMMENT: (id: string) => `${getModuleConfig('offer', 'api_url')}/patterns/${encodeURIComponent(id)}/comment`,
		PATTERNS_DETAIL_IMPORT_GTFS: (id: string) => `${getModuleConfig('offer', 'api_url')}/patterns/${encodeURIComponent(id)}/import-gtfs`,
		PATTERNS_DETAIL_LOCK: (id: string) => `${getModuleConfig('offer', 'api_url')}/patterns/${encodeURIComponent(id)}/lock`,
		PATTERNS_LIST: `${getModuleConfig('offer', 'api_url')}/patterns`,
		PATTERNS_SHAPES: `${getModuleConfig('offer', 'api_url')}/patterns/shapes`,

		// ROUTES
		ROUTES_DETAIL: (id: string) => `${getModuleConfig('offer', 'api_url')}/routes/${encodeURIComponent(id)}`,
		ROUTES_DETAIL_LOCK: (id: string) => `${getModuleConfig('offer', 'api_url')}/routes/${encodeURIComponent(id)}/lock`,
		ROUTES_LIST: `${getModuleConfig('offer', 'api_url')}/routes`,

		// SHAPES
		SHAPES_ROUTE_PREVIEW: `${getModuleConfig('offer', 'api_url')}/shapes/route-preview`,

		// TYPOLOGIES
		TYPOLOGIES_DETAIL: (id: string) => `${getModuleConfig('offer', 'api_url')}/typologies/${encodeURIComponent(id)}`,
		TYPOLOGIES_DETAIL_LOCK: (id: string) => `${getModuleConfig('offer', 'api_url')}/typologies/${encodeURIComponent(id)}/lock`,
		TYPOLOGIES_LIST: `${getModuleConfig('offer', 'api_url')}/typologies`,

		// VKM
		VKM_CALCULATE: `${getModuleConfig('offer', 'api_url')}/vkm/calculate`,

		// ZONES
		ZONES_DETAIL: (id: string) => `${getModuleConfig('offer', 'api_url')}/zones/${encodeURIComponent(id)}`,
		ZONES_DETAIL_LOCK: (id: string) => `${getModuleConfig('offer', 'api_url')}/zones/${encodeURIComponent(id)}/lock`,
		ZONES_LIST: `${getModuleConfig('offer', 'api_url')}/zones`,
	},

	performance: {
		// BASE
		BASE: `${getModuleConfig('performance', 'api_url')}`,

		// DATES
		DATES_LIST: `${getModuleConfig('performance', 'api_url')}/dates`,

		// METRICS
		METRICS_DETAIL: (id: string) => `${getModuleConfig('performance', 'api_url')}/metrics/${encodeURIComponent(id)}`,

		// NETWORK
		NETWORK_LINES: `${getModuleConfig('performance', 'api_url')}/network/lines`,
		NETWORK_PATTERNS: `${getModuleConfig('performance', 'api_url')}/network/patterns`,
	},

	plans: {
		// BASE
		BASE: `${getModuleConfig('plans', 'api_url')}`,

		// PLANS
		PLANS_CREATE: `${getModuleConfig('plans', 'api_url')}/plans/create`,
		PLANS_DETAIL: (id: string) => `${getModuleConfig('plans', 'api_url')}/plans/${encodeURIComponent(id)}`,
		PLANS_DETAIL_APEX_FILE: (id: string) => `${getModuleConfig('plans', 'api_url')}/plans/${encodeURIComponent(id)}/apex-file`,
		PLANS_DETAIL_APEX_FILE_DOWNLOAD: (id: string) => `${getModuleConfig('plans', 'api_url')}/plans/${encodeURIComponent(id)}/apex-file/download`,
		PLANS_DETAIL_APEX_FILE_SEND_NOTIFICATION: (id: string) => `${getModuleConfig('plans', 'api_url')}/plans/${encodeURIComponent(id)}/apex-file/send-notification`,
		PLANS_DETAIL_CHANGE_GTFS: (id: string) => `${getModuleConfig('plans', 'api_url')}/plans/${encodeURIComponent(id)}/change-gtfs`,
		PLANS_DETAIL_CONTROLLER_REPROCESS: (id: string) => `${getModuleConfig('plans', 'api_url')}/plans/${encodeURIComponent(id)}/controller-reprocess`,
		PLANS_DETAIL_LOCK: (id: string) => `${getModuleConfig('plans', 'api_url')}/plans/${encodeURIComponent(id)}/lock`,
		PLANS_DETAIL_OPERATION_FILE: (id: string) => `${getModuleConfig('plans', 'api_url')}/plans/${encodeURIComponent(id)}/operation-file`,
		PLANS_DETAIL_OPERATION_FILE_DOWNLOAD: (id: string) => `${getModuleConfig('plans', 'api_url')}/plans/${encodeURIComponent(id)}/operation-file/download`,
		PLANS_DRT_MODEL: (id: string) => `${getModuleConfig('plans', 'api_url')}/plans/drt-model/${encodeURIComponent(id)}`,
		PLANS_LIST: `${getModuleConfig('plans', 'api_url')}/plans/list`,

		// VALIDATIONS
		VALIDATIONS_CREATE: `${getModuleConfig('plans', 'api_url')}/validations/create`,
		VALIDATIONS_DETAIL: (id: string) => `${getModuleConfig('plans', 'api_url')}/validations/${encodeURIComponent(id)}`,
		VALIDATIONS_DETAIL_FILE: (id: string) => `${getModuleConfig('plans', 'api_url')}/validations/${encodeURIComponent(id)}/file`,
		VALIDATIONS_DETAIL_FILE_DOWNLOAD: (id: string) => `${getModuleConfig('plans', 'api_url')}/validations/${encodeURIComponent(id)}/file/download`,
		VALIDATIONS_DETAIL_LOCK: (id: string) => `${getModuleConfig('plans', 'api_url')}/validations/${encodeURIComponent(id)}/lock`,
		VALIDATIONS_DETAIL_PROCESSING_STATUS: (id: string) => `${getModuleConfig('plans', 'api_url')}/validations/${encodeURIComponent(id)}/processing-status`,
		VALIDATIONS_DETAIL_REQUEST_APPROVAL: (id: string) => `${getModuleConfig('plans', 'api_url')}/validations/${encodeURIComponent(id)}/request-approval`,
		VALIDATIONS_LIST: `${getModuleConfig('plans', 'api_url')}/validations/list`,
	},
} as const);
