apiVersion: apps/v1
kind: Deployment
metadata:
  name: replicator-sync-apex-on-board-refunds
  namespace: go-replicator
  labels:
    app: replicator-sync-apex-on-board-refunds
    app.kubernetes.io/name: replicator-sync-apex-on-board-refunds
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: go-replicator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: replicator-sync-apex-on-board-refunds
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: replicator-sync-apex-on-board-refunds
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: sync-apex-on-board-refunds
          image: ghcr.io/tmlmobilidade/go-replicator-sync-apex-on-board-refunds:k8s
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: replicator-secret
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
