apiVersion: apps/v1
kind: Deployment
metadata:
  name: exporter-export-gtfs-merged
  namespace: go-exporter
  labels:
    app: exporter-export-gtfs-merged
    app.kubernetes.io/name: exporter-export-gtfs-merged
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: go-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exporter-export-gtfs-merged
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: exporter-export-gtfs-merged
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: oci-private-key
          secret:
            secretName: oci-private-key
            items:
              - key: ociprivatekey
                path: ociprivatekey
      containers:
        - name: export-gtfs-merged
          image: ghcr.io/tmlmobilidade/go-exporter-export-gtfs-merged:k8s
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: exporter-secret
          volumeMounts:
            - name: oci-private-key
              mountPath: /run/secrets/ociprivatekey
              subPath: ociprivatekey
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
