apiVersion: apps/v1
kind: Deployment
metadata:
  name: exporter-export-drt
  namespace: go-exporter
  labels:
    app: exporter-export-drt
    app.kubernetes.io/name: exporter-export-drt
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: go-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exporter-export-drt
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: exporter-export-drt
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: export-drt
          image: ghcr.io/tmlmobilidade/go-exporter-export-drt:k8s
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: exporter-secret
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
