import { z } from 'zod';

import { RuleConfigWithCompareDefaultsSchema, RuleConfigWithDefaultsSchema, RuleConfigWithOptionsDefaultsSchema } from './rule-config.js';
import { RulesSeverityEnumSchema } from './severity.js';

export const GtfsRulesSchema = z.object({
	agency: z.object({
		_file: RulesSeverityEnumSchema,
		agency_email_valid_address: RuleConfigWithDefaultsSchema,
		agency_fare_url_valid_url: RuleConfigWithDefaultsSchema,
		agency_id_matched_with_agency_name: RuleConfigWithCompareDefaultsSchema,
		agency_id_unique: RuleConfigWithOptionsDefaultsSchema,
		agency_lang_valid_language_tag: RuleConfigWithDefaultsSchema,
		agency_name_present: RuleConfigWithOptionsDefaultsSchema,
		agency_phone_valid_phone_number: RuleConfigWithDefaultsSchema,
		agency_timezone_valid_id: RuleConfigWithDefaultsSchema,
		agency_url_valid_url: RuleConfigWithDefaultsSchema,
	}),
	attributions: z.object({
		_file: RulesSeverityEnumSchema,
		agency_id: RuleConfigWithDefaultsSchema,
		attribution_email: RuleConfigWithDefaultsSchema,
		attribution_id: RuleConfigWithDefaultsSchema,
		attribution_phone: RuleConfigWithDefaultsSchema,
		attribution_url: RuleConfigWithDefaultsSchema,
		is_authority: RuleConfigWithDefaultsSchema,
		is_operator: RuleConfigWithDefaultsSchema,
		is_producer: RuleConfigWithDefaultsSchema,
		organization_name: RuleConfigWithDefaultsSchema,
		route_id: RuleConfigWithDefaultsSchema,
		trip_id: RuleConfigWithDefaultsSchema,
	}),
	calendar: z.object({
		_file: RulesSeverityEnumSchema,
		calendar_end_date_valid_yyyymmdd: RuleConfigWithDefaultsSchema,
		calendar_service_id_unique_non_empty: RuleConfigWithDefaultsSchema,
		calendar_start_date_valid_yyyymmdd: RuleConfigWithDefaultsSchema,
		friday: RuleConfigWithDefaultsSchema,
		monday: RuleConfigWithDefaultsSchema,
		saturday: RuleConfigWithDefaultsSchema,
		sunday: RuleConfigWithDefaultsSchema,
		thursday: RuleConfigWithDefaultsSchema,
		tuesday: RuleConfigWithDefaultsSchema,
		wednesday: RuleConfigWithDefaultsSchema,
	}),
	calendar_dates: z.object({
		_file: RulesSeverityEnumSchema,
		calendar_dates_service_id_references_calendar: RuleConfigWithDefaultsSchema,
		day_type: RuleConfigWithOptionsDefaultsSchema,
		exception_date_valid_yyyymmdd: RuleConfigWithDefaultsSchema,
		exception_type_add_or_remove_service: RuleConfigWithDefaultsSchema,
		holiday: RuleConfigWithOptionsDefaultsSchema,
		period: RuleConfigWithOptionsDefaultsSchema,
	}),
	fare_attributes: z.object({
		_file: RulesSeverityEnumSchema,
		currency_type_valid: RuleConfigWithOptionsDefaultsSchema,
		fare_attributes_agency_id_references_agency_table: RuleConfigWithDefaultsSchema,
		fare_id_unique: RuleConfigWithDefaultsSchema,
		fare_price_valid_non_negative_decimal: RuleConfigWithDefaultsSchema,
		payment_method_valid_gtfs_enum: RuleConfigWithOptionsDefaultsSchema,
		transfer_duration_valid_seconds_range: RuleConfigWithDefaultsSchema,
		transfers_valid_gtfs_enum: RuleConfigWithOptionsDefaultsSchema,
	}),
	fare_media: z.object({
		_file: RulesSeverityEnumSchema,
		fare_media_id_unique: RuleConfigWithDefaultsSchema,
		fare_media_name_non_empty: RuleConfigWithDefaultsSchema,
		fare_media_type_valid: RuleConfigWithOptionsDefaultsSchema,
	}),
	fare_rules: z.object({
		_file: RulesSeverityEnumSchema,
		fare_rule_contains_id_references_zones_stops: RuleConfigWithDefaultsSchema,
		fare_rule_destination_id_references_zones_stops: RuleConfigWithDefaultsSchema,
		fare_rule_fare_id_references_fare_attributes: RuleConfigWithDefaultsSchema,
		fare_rule_origin_id_references_zones_stops: RuleConfigWithDefaultsSchema,
		fare_rule_route_id_references_routes: RuleConfigWithDefaultsSchema,
	}),
	feed_info: z.object({
		_file: RulesSeverityEnumSchema,
		default_lang_matches_feed_lang_when_present: RuleConfigWithDefaultsSchema,
		feed_contact_email_valid_address: RuleConfigWithDefaultsSchema,
		feed_contact_url_valid_http_url: RuleConfigWithDefaultsSchema,
		feed_end_date_valid_yyyymmdd_not_before_start: RuleConfigWithDefaultsSchema,
		feed_lang_valid_tag: RuleConfigWithOptionsDefaultsSchema,
		feed_publisher_name_non_empty: RuleConfigWithDefaultsSchema,
		feed_publisher_url_valid_http_url: RuleConfigWithDefaultsSchema,
		feed_remarks: RuleConfigWithDefaultsSchema,
		feed_start_date_valid_yyyymmdd: RuleConfigWithDefaultsSchema,
		feed_type: RuleConfigWithOptionsDefaultsSchema,
		feed_version_valid_identifier: RuleConfigWithDefaultsSchema,
	}),
	file_validation: z.object({
		_file: RulesSeverityEnumSchema,
		gtfs_feed_file_presence_and_integrity_rule: RuleConfigWithDefaultsSchema,
	}),
	frequencies: z.object({
		_file: RulesSeverityEnumSchema,
		exact_times_zero_when_timed_trip_uses_frequencies: RuleConfigWithDefaultsSchema,
		frequencies_trip_id_references_trips_table: RuleConfigWithDefaultsSchema,
		frequency_end_time_valid: RuleConfigWithDefaultsSchema,
		frequency_start_time_valid: RuleConfigWithDefaultsSchema,
		headway_secs_positive_and_aligns_trip: RuleConfigWithDefaultsSchema,
	}),
	levels: z.object({
		_file: RulesSeverityEnumSchema,
		level_id: RuleConfigWithDefaultsSchema,
		level_index: RuleConfigWithDefaultsSchema,
		level_name: RuleConfigWithDefaultsSchema,
	}),
	pathways: z.object({
		_file: RulesSeverityEnumSchema,
		from_stop_id: RuleConfigWithDefaultsSchema,
		is_bidirectional: RuleConfigWithDefaultsSchema,
		length: RuleConfigWithDefaultsSchema,
		max_slope: RuleConfigWithDefaultsSchema,
		min_width: RuleConfigWithDefaultsSchema,
		pathway_id: RuleConfigWithDefaultsSchema,
		pathway_mode: RuleConfigWithDefaultsSchema,
		reversed_signposted_as: RuleConfigWithDefaultsSchema,
		signposted_as: RuleConfigWithDefaultsSchema,
		stair_count: RuleConfigWithDefaultsSchema,
		to_stop_id: RuleConfigWithDefaultsSchema,
		traversal_time: RuleConfigWithDefaultsSchema,
	}),
	rider_categories: z.object({
		_file: RulesSeverityEnumSchema,
		at_most_one_default_fare_category: RuleConfigWithDefaultsSchema,
		eligibility_url_valid_http_url: RuleConfigWithDefaultsSchema,
		rider_category_id_unique: RuleConfigWithDefaultsSchema,
		rider_category_name_non_empty: RuleConfigWithDefaultsSchema,
	}),
	routes: z.object({
		_file: RulesSeverityEnumSchema,
		circular: RuleConfigWithOptionsDefaultsSchema,
		continuous_drop_off_valid_gtfs_enum: RuleConfigWithOptionsDefaultsSchema,
		continuous_pickup_valid_gtfs_enum: RuleConfigWithOptionsDefaultsSchema,
		line_id: RuleConfigWithDefaultsSchema,
		line_long_name: RuleConfigWithDefaultsSchema,
		line_short_name: RuleConfigWithDefaultsSchema,
		network_id_references_networks_table: RuleConfigWithDefaultsSchema,
		path_type_valid_enum: RuleConfigWithOptionsDefaultsSchema,
		route_agency_id_references_agency_table: RuleConfigWithDefaultsSchema,
		route_color_valid_hex_string: RuleConfigWithDefaultsSchema,
		route_desc_per_severity_and_content_rules: RuleConfigWithDefaultsSchema,
		route_id_unique: RuleConfigWithDefaultsSchema,
		route_long_name_or_short_name_present: RuleConfigWithDefaultsSchema,
		route_remarks: RuleConfigWithDefaultsSchema,
		route_short_name_or_long_name_present: RuleConfigWithDefaultsSchema,
		route_sort_order_non_negative_integer: RuleConfigWithDefaultsSchema,
		route_text_color_valid_hex_contrast: RuleConfigWithDefaultsSchema,
		route_type_valid_gtfs_enum: RuleConfigWithOptionsDefaultsSchema,
		route_url_valid_http_url: RuleConfigWithDefaultsSchema,
		school: RuleConfigWithOptionsDefaultsSchema,
	}),
	shapes: z.object({
		_file: RulesSeverityEnumSchema,
		shape_block_distance_rows_aggregated: RuleConfigWithOptionsDefaultsSchema,
		shape_dist_traveled_delta_mismatches_haversine_block: RuleConfigWithOptionsDefaultsSchema,
		shape_dist_traveled_delta_mismatches_haversine_segment: RuleConfigWithOptionsDefaultsSchema,
		shape_dist_traveled_non_decreasing_with_sequence: RuleConfigWithDefaultsSchema,
		shape_dist_traveled_non_negative_monotonic: RuleConfigWithDefaultsSchema,
		shape_id_and_point_sequence_required: RuleConfigWithDefaultsSchema,
		shape_id_required: RuleConfigWithDefaultsSchema,
		shape_pt_lat_valid_latitude: RuleConfigWithDefaultsSchema,
		shape_pt_lon_valid_longitude: RuleConfigWithDefaultsSchema,
		shape_pt_sequence_not_repeated_within_shape: RuleConfigWithDefaultsSchema,
		shape_pt_sequence_strictly_increasing: RuleConfigWithDefaultsSchema,
		shape_sequence_position_mismatches_cumulative_traveled_distance: RuleConfigWithDefaultsSchema,
	}),
	stop_times: z.object({
		_file: RulesSeverityEnumSchema,
		arrival_time_ordering_with_departure_and_frequencies: RuleConfigWithDefaultsSchema,
		departure_time_ordering_with_arrival_and_timepoint: RuleConfigWithDefaultsSchema,
		drop_off_booking_rule_id_references_booking_rules_or_empty: RuleConfigWithDefaultsSchema,
		drop_off_type_valid_gtfs_enum: RuleConfigWithDefaultsSchema,
		end_pickup_drop_off_window_valid: RuleConfigWithDefaultsSchema,
		location_group_id_consistent_with_trip_id_and_stops: RuleConfigWithDefaultsSchema,
		pickup_booking_rule_id_references_booking_rules: RuleConfigWithDefaultsSchema,
		pickup_type_valid_gtfs_enum: RuleConfigWithDefaultsSchema,
		start_pickup_drop_off_window_valid: RuleConfigWithDefaultsSchema,
		stop_headsign_present: RuleConfigWithDefaultsSchema,
		stop_times_continuous_drop_off_valid_gtfs_enum: RuleConfigWithDefaultsSchema,
		stop_times_continuous_pickup_valid_gtfs_enum: RuleConfigWithDefaultsSchema,
		stop_times_shape_dist_traveled_non_decreasing_on_trip: RuleConfigWithDefaultsSchema,
		stop_times_stop_id_references_stops_table: RuleConfigWithDefaultsSchema,
		stop_times_trip_id_references_trips_table: RuleConfigWithDefaultsSchema,
		timepoint_valid_gtfs_enum: RuleConfigWithDefaultsSchema,
	}),
	stops: z.object({
		_file: RulesSeverityEnumSchema,
		has_bench_valid_enum: RuleConfigWithOptionsDefaultsSchema,
		has_network_map_valid_enum: RuleConfigWithOptionsDefaultsSchema,
		has_pip_real_time_valid_enum: RuleConfigWithOptionsDefaultsSchema,
		has_schedules_valid_enum: RuleConfigWithOptionsDefaultsSchema,
		has_shelter_valid_enum: RuleConfigWithOptionsDefaultsSchema,
		has_stop_sign_valid_enum: RuleConfigWithOptionsDefaultsSchema,
		has_tariffs_information_valid_enum: RuleConfigWithDefaultsSchema,
		level_id_valid_id: RuleConfigWithDefaultsSchema,
		location_type_valid_enum: RuleConfigWithDefaultsSchema,
		municipality_id_valid: RuleConfigWithOptionsDefaultsSchema,
		parent_station_id_valid_for_stop_hierarchy: RuleConfigWithDefaultsSchema,
		parish_id_valid: RuleConfigWithDefaultsSchema,
		platform_code_valid: RuleConfigWithDefaultsSchema,
		public_visible_valid_enum: RuleConfigWithDefaultsSchema,
		region_id_valid: RuleConfigWithOptionsDefaultsSchema,
		shelter_code_valid: RuleConfigWithDefaultsSchema,
		shelter_maintainer_valid: RuleConfigWithDefaultsSchema,
		stop_code_valid: RuleConfigWithDefaultsSchema,
		stop_desc_valid: RuleConfigWithDefaultsSchema,
		stop_id_unique: RuleConfigWithDefaultsSchema,
		stop_lat_valid_latitude_range: RuleConfigWithDefaultsSchema,
		stop_lon_valid_longitude_range: RuleConfigWithDefaultsSchema,
		stop_name_required_by_location_type: RuleConfigWithDefaultsSchema,
		stop_short_name_valid: RuleConfigWithDefaultsSchema,
		stop_timezone_valid: RuleConfigWithDefaultsSchema,
		stop_url_valid_url: RuleConfigWithDefaultsSchema,
		tts_stop_name_valid: RuleConfigWithDefaultsSchema,
		wheelchair_boarding_valid_enum: RuleConfigWithOptionsDefaultsSchema,
		zone_id_valid: RuleConfigWithDefaultsSchema,
	}),
	transfers: z.object({
		_file: RulesSeverityEnumSchema,
		from_stop_id: RuleConfigWithDefaultsSchema,
		min_transfer_time: RuleConfigWithDefaultsSchema,
		to_stop_id: RuleConfigWithDefaultsSchema,
		transfer_type: RuleConfigWithDefaultsSchema,
	}),
	translations: z.object({
		_file: RulesSeverityEnumSchema,
		field_name: RuleConfigWithDefaultsSchema,
		field_value: RuleConfigWithDefaultsSchema,
		language: RuleConfigWithDefaultsSchema,
		record_id: RuleConfigWithDefaultsSchema,
		record_sub_id: RuleConfigWithDefaultsSchema,
		table_name: RuleConfigWithDefaultsSchema,
		translation: RuleConfigWithDefaultsSchema,
	}),
	trips: z.object({
		_file: RulesSeverityEnumSchema,
		bikes_allowed_valid_gtfs_enum: RuleConfigWithDefaultsSchema,
		block_id_in_allowed_set: RuleConfigWithDefaultsSchema,
		direction_id_consistent_for_all_patterns_in_trips: RuleConfigWithDefaultsSchema,
		direction_id_matches_feed_pattern_direction: RuleConfigWithDefaultsSchema,
		direction_id_valid_enum: RuleConfigWithDefaultsSchema,
		one_pattern_id_per_shape_id_group: RuleConfigWithDefaultsSchema,
		one_shape_id_per_pattern_id_group: RuleConfigWithDefaultsSchema,
		pattern_id_matches_feed_pattern_id_syntax: RuleConfigWithOptionsDefaultsSchema,
		pattern_id_present_and_references_consistent: RuleConfigWithDefaultsSchema,
		pattern_id_single_trip_signature_per_pattern: RuleConfigWithDefaultsSchema,
		pattern_id_trip_has_required_fields_for_grouping: RuleConfigWithDefaultsSchema,
		route_id_consistent_for_all_patterns_in_trips: RuleConfigWithDefaultsSchema,
		route_id_references_routes_table: RuleConfigWithDefaultsSchema,
		service_id_references_calendar_service: RuleConfigWithDefaultsSchema,
		shape_id_needs_to_be_the_same_as_pattern_id: RuleConfigWithDefaultsSchema,
		shape_id_references_shapes_table_when_present: RuleConfigWithDefaultsSchema,
		stop_sequence_increasing_by_one_along_trip: RuleConfigWithDefaultsSchema,
		trip_headsign_consistent_for_all_patterns_in_trips: RuleConfigWithDefaultsSchema,
		trip_headsign_present_when_short_name_absent: RuleConfigWithDefaultsSchema,
		trip_id_limit_max_length: RuleConfigWithDefaultsSchema,
		trip_id_unique: RuleConfigWithDefaultsSchema,
		trip_path_stop_coordinates_referenced_from_stops: RuleConfigWithDefaultsSchema,
		trip_short_name_exclusivity: RuleConfigWithDefaultsSchema,
		wheelchair_accessible_valid_gtfs_enum: RuleConfigWithDefaultsSchema,
	}),
	vehicles: z.object({
		_file: RulesSeverityEnumSchema,
		available_seats_non_negative: RuleConfigWithDefaultsSchema,
		available_standing_non_negative: RuleConfigWithDefaultsSchema,
		bicycles_rack_count_non_negative: RuleConfigWithOptionsDefaultsSchema,
		climatization_valid_enum: RuleConfigWithOptionsDefaultsSchema,
		consumption_meter_valid_format: RuleConfigWithOptionsDefaultsSchema,
		emission_code_valid_for_propulsion_type: RuleConfigWithOptionsDefaultsSchema,
		external_sound_valid_enum: RuleConfigWithOptionsDefaultsSchema,
		front_display_valid_enum: RuleConfigWithOptionsDefaultsSchema,
		internal_sound_level_valid_enum: RuleConfigWithOptionsDefaultsSchema,
		kneeling_valid_enum: RuleConfigWithOptionsDefaultsSchema,
		license_plate_format_per_market_rules: RuleConfigWithDefaultsSchema,
		lowered_floor_valid_enum: RuleConfigWithOptionsDefaultsSchema,
		onboard_monitor_valid_enum: RuleConfigWithOptionsDefaultsSchema,
		passenger_counting_valid_enum: RuleConfigWithOptionsDefaultsSchema,
		propulsion_type_valid_enum: RuleConfigWithOptionsDefaultsSchema,
		ramp_valid_enum: RuleConfigWithOptionsDefaultsSchema,
		rear_display_valid_enum: RuleConfigWithOptionsDefaultsSchema,
		registration_date_valid_day_granularity: RuleConfigWithDefaultsSchema,
		side_display_valid_enum: RuleConfigWithOptionsDefaultsSchema,
		static_information_valid_enum: RuleConfigWithOptionsDefaultsSchema,
		typology_in_allowed_vehicle_types: RuleConfigWithOptionsDefaultsSchema,
		vehicle_agency_id_references_agency_table: RuleConfigWithDefaultsSchema,
		vehicle_id_unique: RuleConfigWithDefaultsSchema,
		vehicle_make_required: RuleConfigWithDefaultsSchema,
		vehicle_model_required: RuleConfigWithDefaultsSchema,
		vehicle_owner_required: RuleConfigWithDefaultsSchema,
		video_surveillance_valid_enum: RuleConfigWithOptionsDefaultsSchema,
		wheelchair_spots_valid_enum: RuleConfigWithOptionsDefaultsSchema,
	}),
});

export type GtfsRules = z.infer<typeof GtfsRulesSchema>;
export type GtfsRule = keyof GtfsRules;
