package rules

import (
	"bytes"
	"fmt"
	"main/types"
	"reflect"
	"slices"
	"sort"
	"strings"
)

// TypeScriptHeader explains where the generated contract comes from.
const TypeScriptHeader = `/**
 * This file is auto-generated by the rules-catalogue command of the Go validator.
 * Do not edit this file manually. Run ` + "`npm run repo:validator-rules`" + ` to regenerate.
 *
 * Source: types.GtfsRules, types.RuleConfig and rules.Catalogue() in
 * modules/operation/apps/validator/validator/src
 *
 * Configuration types describe what the Go decoder produces. The *Input types
 * describe what it accepts: every key may be omitted (Go fills the default),
 * and null is allowed where Go ignores it or decodes it to nil. Severities,
 * sections and rule objects reject null, as rules.DecodeConfig does.
 * These are compile-time types only. They do not validate anything at runtime.
 */
`

var severityType = reflect.TypeOf(types.Severity(""))

// TypeScript renders the shared TypeScript contract for the validation rules.
func TypeScript() (map[string][]byte, error) {
	if err := ValidateDependencyContract(); err != nil {
		return nil, err
	}
	return renderTypeScript(reflect.TypeOf(types.GtfsRules{}), Catalogue())
}

type tsField struct {
	name      string
	omitEmpty bool
	fieldType reflect.Type
}

type tsGroup struct {
	name     string
	typeName string
	keys     []string
	fields   []tsField
}

type tsWriter struct {
	buf     bytes.Buffer
	structs map[string]reflect.Type
}

func (w *tsWriter) line(format string, args ...any) {
	fmt.Fprintf(&w.buf, format, args...)
	w.buf.WriteByte('\n')
}

func renderTypeScript(root reflect.Type, catalogue []CatalogueEntry) (map[string][]byte, error) {
	if root.Kind() != reflect.Struct {
		return nil, fmt.Errorf("rules root %s is not a struct", root)
	}
	groups, err := collectGroups(root)
	if err != nil {
		return nil, err
	}
	if err := checkCatalogue(groups, catalogue); err != nil {
		return nil, err
	}

	w := &tsWriter{structs: map[string]reflect.Type{}}
	for _, group := range groups {
		for _, field := range group.fields {
			if field.fieldType != severityType {
				if err := w.collectStructs(field.fieldType, group.name+"."+field.name); err != nil {
					return nil, err
				}
			}
		}
	}

	files := map[string][]byte{}
	startFile := func(imports ...string) {
		w.buf.Reset()
		w.buf.WriteString(TypeScriptHeader)
		w.line("")
		for _, declaration := range imports {
			w.line("%s", declaration)
		}
		if len(imports) > 0 {
			w.line("")
		}
		w.line("/* * */")
		w.line("")
	}
	saveFile := func(name string) {
		files[name] = []byte(strings.TrimSpace(w.buf.String()) + "\n")
	}

	startFile()
	w.writeSeverities()
	saveFile("rules-severities.ts")

	startFile()
	w.writeGroups(groups)
	saveFile("rules-groups.ts")

	startFile()
	w.writeIDs(catalogue)
	saveFile("rules-ids.ts")

	for _, input := range []bool{false, true} {
		startFile("import { type RuleSeverity } from './rules-severities.js';")
		if err := w.writeStructs(input); err != nil {
			return nil, err
		}
		if err := w.writeGroupTypes(root, groups, input); err != nil {
			return nil, err
		}
		if input {
			saveFile("rules-inputs.ts")
		} else {
			saveFile("rules-config.ts")
		}
	}

	startFile(
		"import { type RuleConfigKey, type RuleGroup } from './rules-groups.js';",
		"import { type RuleId, type RuleOutputId } from './rules-ids.js';",
		"import { type RuleSeverity } from './rules-severities.js';",
	)
	w.writeCatalogueTypes()
	w.writeCatalogue(catalogue)
	saveFile("rules-catalogue.ts")
	return files, nil
}

// collectGroups reads the file sections of the root struct, keeping the Go
// declaration order for keys and sorting sections by their JSON name.
func collectGroups(root reflect.Type) ([]tsGroup, error) {
	groups := []tsGroup{}
	for i := range root.NumField() {
		field := root.Field(i)
		name, _, err := jsonName(field)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", root.Name(), err)
		}
		if field.Type.Kind() != reflect.Struct {
			return nil, fmt.Errorf("section %s has unsupported type %s", name, field.Type)
		}
		group := tsGroup{name: name, typeName: field.Type.Name()}
		for j := range field.Type.NumField() {
			member := field.Type.Field(j)
			key, omitEmpty, err := jsonName(member)
			if err != nil {
				return nil, fmt.Errorf("%s: %w", name, err)
			}
			if member.Type != severityType && member.Type != ruleConfigType {
				return nil, fmt.Errorf("%s.%s has unsupported type %s: only types.Severity and types.RuleConfig are allowed in a section", name, key, member.Type)
			}
			group.keys = append(group.keys, key)
			group.fields = append(group.fields, tsField{name: key, omitEmpty: omitEmpty, fieldType: member.Type})
		}
		groups = append(groups, group)
	}
	sort.Slice(groups, func(i, j int) bool { return groups[i].name < groups[j].name })
	return groups, nil
}

// checkCatalogue fails when an entry points at a section or key that the
// configuration struct does not have, so the TypeScript never lies about it.
func checkCatalogue(groups []tsGroup, catalogue []CatalogueEntry) error {
	keys := map[string][]string{}
	for _, group := range groups {
		keys[group.name] = group.keys
	}
	ids := map[string]bool{}
	for _, entry := range catalogue {
		groupKeys, ok := keys[entry.Group]
		if !ok {
			return fmt.Errorf("catalogue entry %s uses unknown section %s", entry.ID, entry.Group)
		}
		if ids[entry.ID] {
			return fmt.Errorf("catalogue entry id %s is duplicated", entry.ID)
		}
		ids[entry.ID] = true
		if entry.Editable {
			if !slices.Contains(groupKeys, entry.ConfigKey) {
				return fmt.Errorf("catalogue entry %s uses unknown key %s.%s", entry.ID, entry.Group, entry.ConfigKey)
			}
			if entry.Severity != "" || len(entry.Severities) > 0 {
				return fmt.Errorf("editable catalogue entry %s must not have a fixed severity", entry.ID)
			}
			continue
		}
		if entry.ConfigKey != "" || len(entry.OutputIDs) > 0 || entry.MessageField != "" {
			return fmt.Errorf("fixed catalogue entry %s must not have a key, output ids or message field", entry.ID)
		}
		if (entry.Severity == "") == (len(entry.Severities) == 0) {
			return fmt.Errorf("fixed catalogue entry %s needs exactly one of severity or severities", entry.ID)
		}
		for _, severity := range append([]types.Severity{entry.Severity}, entry.Severities...) {
			if severity != "" && !slices.Contains(Severities, severity) {
				return fmt.Errorf("fixed catalogue entry %s has unknown severity %q", entry.ID, severity)
			}
		}
	}
	return nil
}

func jsonName(field reflect.StructField) (string, bool, error) {
	tag, ok := field.Tag.Lookup("json")
	if !ok {
		return "", false, fmt.Errorf("field %s has no json tag", field.Name)
	}
	name, options, _ := strings.Cut(tag, ",")
	if name == "" || name == "-" {
		return "", false, fmt.Errorf("field %s has unsupported json tag %q", field.Name, tag)
	}
	return name, slices.Contains(strings.Split(options, ","), "omitempty"), nil
}

// collectStructs records every struct reachable from a rule field, failing on
// kinds the renderer does not know how to express.
func (w *tsWriter) collectStructs(t reflect.Type, path string) error {
	switch t.Kind() {
	case reflect.Pointer, reflect.Slice:
		return w.collectStructs(t.Elem(), path)
	case reflect.String:
		return nil
	case reflect.Struct:
		name := structName(t)
		if existing, ok := w.structs[name]; ok {
			if existing != t {
				return fmt.Errorf("%s: two Go types map to TypeScript name %s", path, name)
			}
			return nil
		}
		w.structs[name] = t
		for i := range t.NumField() {
			field := t.Field(i)
			key, _, err := jsonName(field)
			if err != nil {
				return fmt.Errorf("%s: %w", path, err)
			}
			if field.Type == severityType {
				continue
			}
			if err := w.collectStructs(field.Type, path+"."+key); err != nil {
				return err
			}
		}
		return nil
	default:
		return fmt.Errorf("%s has unsupported type %s", path, t)
	}
}

func structName(t reflect.Type) string {
	if strings.HasPrefix(t.Name(), "Rule") {
		return t.Name()
	}
	return "Rule" + t.Name()
}

// tsType renders the decoded (output) or accepted (input) TypeScript type.
func tsType(t reflect.Type, input bool) (string, error) {
	if t == severityType {
		return "RuleSeverity", nil
	}
	switch t.Kind() {
	case reflect.String:
		return "string", nil
	case reflect.Pointer:
		return tsType(t.Elem(), input)
	case reflect.Slice:
		elem, err := tsType(t.Elem(), input)
		if err != nil {
			return "", err
		}
		return elem + "[]", nil
	case reflect.Struct:
		if input {
			return structName(t) + "Input", nil
		}
		return structName(t), nil
	default:
		return "", fmt.Errorf("unsupported type %s", t)
	}
}

// nullable reports whether the Go encoder can emit null (output) or the
// decoder accepts null without error (input) for a struct member.
func nullable(t reflect.Type, omitEmpty, input bool) bool {
	if input {
		// rules.DecodeConfig rejects null severities; everything else below a
		// rule object is ignored or set to nil by encoding/json.
		return t != severityType
	}
	return (t.Kind() == reflect.Pointer || t.Kind() == reflect.Slice) && !omitEmpty
}

var tsStringEscaper = strings.NewReplacer(`\`, `\\`, `'`, `\'`, "\n", `\n`, "\r", `\r`)

// quote renders a single-quoted TypeScript string literal.
func quote(value string) string {
	return "'" + tsStringEscaper.Replace(value) + "'"
}

func (w *tsWriter) writeSeverities() {
	quoted := make([]string, len(Severities))
	for i, severity := range Severities {
		quoted[i] = quote(string(severity))
	}
	w.line("export const ruleSeverities = [%s] as const;", strings.Join(quoted, ", "))
	w.line("")
	w.line("export type RuleSeverity = typeof ruleSeverities[number];")
	w.line("")
	w.line("/* * */")
	w.line("")
}

func (w *tsWriter) writeGroups(groups []tsGroup) {
	w.line("/**")
	w.line(" * Stored configuration keys of every section, in Go declaration order.")
	w.line(" * These are the keys saved in an agency's rules, not the emitted rule ids.")
	w.line(" */")
	w.line("export const ruleConfigKeys = {")
	for _, group := range groups {
		w.line("\t%s: [", group.name)
		for _, key := range group.keys {
			w.line("\t\t%s,", quote(key))
		}
		w.line("\t],")
	}
	w.line("} as const;")
	w.line("")
	w.line("export type RuleGroup = keyof typeof ruleConfigKeys;")
	w.line("")
	w.line("export type RuleConfigKey<G extends RuleGroup = RuleGroup> = typeof ruleConfigKeys[G][number];")
	w.line("")
	w.line("export const ruleGroups = [")
	for _, group := range groups {
		w.line("\t%s,", quote(group.name))
	}
	w.line("] as const satisfies readonly RuleGroup[];")
	w.line("")
	w.line("/* * */")
	w.line("")
}

func (w *tsWriter) writeIDs(catalogue []CatalogueEntry) {
	ids := []string{}
	known := map[string]bool{}
	for _, entry := range catalogue {
		ids = append(ids, entry.ID)
		known[entry.ID] = true
	}
	sort.Strings(ids)
	extra := []string{}
	for _, entry := range catalogue {
		for _, id := range entry.OutputIDs {
			if !known[id] && !slices.Contains(extra, id) {
				extra = append(extra, id)
			}
		}
	}
	sort.Strings(extra)

	w.line("/**")
	w.line(" * Rule ids emitted by the validator, one per catalogue entry.")
	w.line(" */")
	w.line("export const ruleIds = [")
	for _, id := range ids {
		w.line("\t%s,", quote(id))
	}
	w.line("] as const;")
	w.line("")
	w.line("export type RuleId = typeof ruleIds[number];")
	w.line("")
	w.line("/**")
	w.line(" * Rule ids that appear in validator messages, including shared ids that")
	w.line(" * several catalogue entries emit through output_ids.")
	w.line(" */")
	if len(extra) == 0 {
		w.line("export type RuleOutputId = RuleId;")
	} else {
		quoted := make([]string, len(extra))
		for i, id := range extra {
			quoted[i] = quote(id)
		}
		w.line("export type RuleOutputId = %s | RuleId;", strings.Join(quoted, " | "))
	}
	w.line("")
	w.line("/* * */")
	w.line("")
}

func (w *tsWriter) writeInterface(name string, members []string) {
	sort.Strings(members)
	w.line("export interface %s {", name)
	for _, member := range members {
		w.line("\t%s", member)
	}
	w.line("}")
	w.line("")
}

func member(key, value string, optional, isNullable bool) string {
	if isNullable {
		value = "null | " + value
	}
	if optional {
		return key + "?: " + value
	}
	return key + ": " + value
}

func (w *tsWriter) writeStructs(input bool) error {
	names := make([]string, 0, len(w.structs))
	for name := range w.structs {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		t := w.structs[name]
		members := []string{}
		for i := range t.NumField() {
			field := t.Field(i)
			key, omitEmpty, err := jsonName(field)
			if err != nil {
				return err
			}
			value, err := tsType(field.Type, input)
			if err != nil {
				return fmt.Errorf("%s.%s: %w", name, key, err)
			}
			members = append(members, member(key, value, input || omitEmpty, nullable(field.Type, omitEmpty, input)))
		}
		typeName := name
		if input {
			typeName += "Input"
		}
		w.writeInterface(typeName, members)
	}
	w.line("/* * */")
	w.line("")
	return nil
}

func (w *tsWriter) writeGroupTypes(root reflect.Type, groups []tsGroup, input bool) error {
	for _, group := range groups {
		members := []string{}
		for _, field := range group.fields {
			value, err := tsType(field.fieldType, input)
			if err != nil {
				return fmt.Errorf("%s.%s: %w", group.name, field.name, err)
			}
			members = append(members, member(field.name, value, input || field.omitEmpty, false))
		}
		typeName := group.typeName
		if input {
			typeName += "Input"
		}
		w.writeInterface(typeName, members)
	}
	members := []string{}
	for _, group := range groups {
		typeName := group.typeName
		if input {
			typeName += "Input"
		}
		members = append(members, member(group.name, typeName, input, false))
	}
	name := "ValidationRules"
	if input {
		w.line("/**")
		w.line(" * Rules as saved for an agency and accepted by the Go validator.")
		w.line(" */")
		name += "Input"
	} else {
		w.line("/**")
		w.line(" * Rules after the Go validator filled every omitted setting.")
		w.line(" * Source: %s", root.String())
		w.line(" */")
	}
	w.writeInterface(name, members)
	w.line("/* * */")
	w.line("")
	return nil
}

func (w *tsWriter) writeCatalogueTypes() {
	w.line("/**")
	w.line(" * A rule whose severity is stored under config_key in its section.")
	w.line(" * Only real group/key combinations are accepted.")
	w.line(" */")
	w.line("export type EditableRuleCatalogueEntry = {")
	w.line("\t[G in RuleGroup]: {")
	w.line("\t\t[K in RuleConfigKey<G>]: {")
	w.line("\t\t\tconfig_key: K")
	w.line("\t\t\tdepends_on?: readonly string[]")
	w.line("\t\t\teditable: true")
	w.line("\t\t\tgroup: G")
	w.line("\t\t\tid: RuleId")
	w.line("\t\t\tmessage_field?: string")
	w.line("\t\t\toutput_ids?: readonly RuleOutputId[]")
	w.line("\t\t\tseverities?: never")
	w.line("\t\t\tseverity?: never")
	w.line("\t\t}")
	w.line("\t}[RuleConfigKey<G>]")
	w.line("}[RuleGroup];")
	w.line("")
	w.line("/**")
	w.line(" * A technical notice with a severity fixed by the validator.")
	w.line(" */")
	w.line("export interface FixedRuleCatalogueEntry {")
	w.line("\tconfig_key?: never")
	w.line("\teditable: false")
	w.line("\tgroup: RuleGroup")
	w.line("\tid: RuleId")
	w.line("\tmessage_field?: never")
	w.line("\toutput_ids?: never")
	w.line("\tseverities?: readonly RuleSeverity[]")
	w.line("\tseverity?: RuleSeverity")
	w.line("}")
	w.line("")
	w.line("export type RuleCatalogueEntry = EditableRuleCatalogueEntry | FixedRuleCatalogueEntry;")
	w.line("")
	w.line("/* * */")
	w.line("")
}

func (w *tsWriter) writeCatalogue(catalogue []CatalogueEntry) {
	w.line("export const ruleCatalogue: readonly RuleCatalogueEntry[] = [")
	for _, entry := range catalogue {
		// Keys in alphabetical order, matching the lint rules for object literals.
		w.line("\t{")
		if entry.ConfigKey != "" {
			w.line("\t\tconfig_key: %s,", quote(entry.ConfigKey))
		}
		if len(entry.DependsOn) > 0 {
			quoted := make([]string, len(entry.DependsOn))
			for i, id := range entry.DependsOn {
				quoted[i] = quote(id)
			}
			w.line("\t\tdepends_on: [%s],", strings.Join(quoted, ", "))
		}
		w.line("\t\teditable: %t,", entry.Editable)
		w.line("\t\tgroup: %s,", quote(entry.Group))
		w.line("\t\tid: %s,", quote(entry.ID))
		if entry.MessageField != "" {
			w.line("\t\tmessage_field: %s,", quote(entry.MessageField))
		}
		if len(entry.OutputIDs) > 0 {
			quoted := make([]string, len(entry.OutputIDs))
			for i, id := range entry.OutputIDs {
				quoted[i] = quote(id)
			}
			w.line("\t\toutput_ids: [%s],", strings.Join(quoted, ", "))
		}
		if len(entry.Severities) > 0 {
			quoted := make([]string, len(entry.Severities))
			for i, severity := range entry.Severities {
				quoted[i] = quote(string(severity))
			}
			w.line("\t\tseverities: [%s],", strings.Join(quoted, ", "))
		}
		if entry.Severity != "" {
			w.line("\t\tseverity: %s,", quote(string(entry.Severity)))
		}
		w.line("\t},")
	}
	w.line("];")
}
