apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: go-poc
  labels:
    app: gateway
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: go-poc
spec:
  # LoadBalancer: OKE automatically provisions an OCI Load Balancer with a public IP.
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
