/**
 * This file is auto-generated by the rules-catalogue command of the Go validator.
 * Do not edit this file manually. Run `npm run repo:validator-rules` to regenerate.
 *
 * Source: types.GtfsRules, types.RuleConfig and rules.Catalogue() in
 * modules/operation/apps/validator/validator/src
 *
 * Configuration types describe what the Go decoder produces. The *Input types
 * describe what it accepts: every key may be omitted (Go fills the default),
 * and null is allowed where Go ignores it or decodes it to nil. Severities,
 * sections and rule objects reject null, as rules.DecodeConfig does.
 * These are compile-time types only. They do not validate anything at runtime.
 */

/* * */

export const ruleSeverities = ['error', 'warning', 'ignore', 'forbidden'] as const;

export type RuleSeverity = typeof ruleSeverities[number];

/* * */
