/**
 * This file is auto-generated by the rules-catalogue command of the Go validator.
 * Do not edit this file manually. Run `npm run repo:validator-rules` to regenerate.
 *
 * Source: types.GtfsRules, types.RuleConfig and rules.Catalogue() in
 * modules/operation/apps/validator/validator/src
 *
 * Configuration types describe what the Go decoder produces. The *Input types
 * describe what it accepts: every key may be omitted (Go fills the default),
 * and null is allowed where Go ignores it or decodes it to nil. Severities,
 * sections and rule objects reject null, as rules.DecodeConfig does.
 * These are compile-time types only. They do not validate anything at runtime.
 */

/* * */

export const ruleSeverities = ['error', 'warning', 'ignore', 'forbidden'] as const;

export type RuleSeverity = typeof ruleSeverities[number];

/* * */

/**
 * Stored configuration keys of every section, in Go declaration order.
 * These are the keys saved in an agency's rules, not the emitted rule ids.
 */
export const ruleConfigKeys = {
	agency: [
		'_file',
		'agency_id_unique',
		'agency_id_matched_with_agency_name',
		'agency_name_present',
		'agency_url_valid_url',
		'agency_timezone_valid_id',
		'agency_lang_valid_language_tag',
		'agency_phone_valid_phone_number',
		'agency_fare_url_valid_url',
		'agency_email_valid_address',
	],
	attributions: [
		'_file',
		'attribution_id',
		'agency_id',
		'route_id',
		'trip_id',
		'organization_name',
		'is_producer',
		'is_operator',
		'is_authority',
		'attribution_url',
		'attribution_email',
		'attribution_phone',
	],
	calendar: [
		'_file',
		'calendar_service_id_unique_non_empty',
		'monday',
		'tuesday',
		'wednesday',
		'thursday',
		'friday',
		'saturday',
		'sunday',
		'calendar_start_date_valid_yyyymmdd',
		'calendar_end_date_valid_yyyymmdd',
	],
	calendar_dates: [
		'_file',
		'calendar_dates_service_id_references_calendar',
		'exception_date_valid_yyyymmdd',
		'exception_type_add_or_remove_service',
		'day_type',
		'holiday',
		'period',
	],
	fare_attributes: [
		'_file',
		'fare_id_unique',
		'fare_price_valid_non_negative_decimal',
		'currency_type_valid',
		'payment_method_valid_gtfs_enum',
		'transfers_valid_gtfs_enum',
		'fare_attributes_agency_id_references_agency_table',
		'transfer_duration_valid_seconds_range',
	],
	fare_media: [
		'_file',
		'fare_media_id_unique',
		'fare_media_name_non_empty',
		'fare_media_type_valid',
	],
	fare_rules: [
		'_file',
		'fare_rule_fare_id_references_fare_attributes',
		'fare_rule_route_id_references_routes',
		'fare_rule_origin_id_references_zones_stops',
		'fare_rule_destination_id_references_zones_stops',
		'fare_rule_contains_id_references_zones_stops',
	],
	feed_info: [
		'_file',
		'feed_type',
		'feed_publisher_name_non_empty',
		'feed_publisher_url_valid_http_url',
		'feed_lang_valid_tag',
		'default_lang_matches_feed_lang_when_present',
		'feed_start_date_valid_yyyymmdd',
		'feed_end_date_valid_yyyymmdd_not_before_start',
		'feed_version_valid_identifier',
		'feed_remarks',
		'feed_contact_email_valid_address',
		'feed_contact_url_valid_http_url',
	],
	file_validation: [
		'_file',
		'gtfs_feed_file_presence_and_integrity_rule',
	],
	frequencies: [
		'_file',
		'trip_id',
		'start_time',
		'end_time',
		'headway_secs',
		'exact_times',
	],
	levels: [
		'_file',
		'level_id_unique',
		'level_index_required',
		'level_name',
	],
	pathways: [
		'_file',
		'pathway_id_unique',
		'pathway_from_stop_id_references_stops_table',
		'pathway_to_stop_id_references_stops_table',
		'pathway_mode_valid_gtfs_enum',
		'pathway_is_bidirectional_valid_gtfs_enum',
		'pathway_length_non_negative',
		'pathway_traversal_time_non_negative_seconds',
		'pathway_stair_count',
		'pathway_max_slope_allowed_for_pathway_mode',
		'pathway_min_width_positive',
		'pathway_signposted_as',
		'pathway_reversed_signposted_as',
	],
	rider_categories: [
		'_file',
		'rider_category_id_unique',
		'rider_category_name_non_empty',
		'at_most_one_default_fare_category',
		'eligibility_url_valid_http_url',
	],
	routes: [
		'_file',
		'line_id_required',
		'line_short_name_present_when_line_id_present',
		'line_long_name_present_when_line_id_present',
		'route_id_unique',
		'route_agency_id_references_agency_table',
		'route_short_name_or_long_name_present',
		'route_long_name_or_short_name_present',
		'route_desc_per_severity_and_content_rules',
		'route_sort_order_non_negative_integer',
		'route_remarks',
		'network_id_references_networks_table',
		'route_type_valid_gtfs_enum',
		'path_type_valid_enum',
		'circular',
		'school',
		'route_url_valid_http_url',
		'route_color_valid_hex_string',
		'route_text_color_valid_hex_contrast',
		'continuous_pickup_valid_gtfs_enum',
		'continuous_drop_off_valid_gtfs_enum',
	],
	shapes: [
		'_file',
		'shape_id_required',
		'shape_pt_lat_valid_latitude',
		'shape_pt_lon_valid_longitude',
		'shape_pt_sequence_not_repeated_within_shape',
		'shape_dist_traveled_non_negative_monotonic',
		'shape_id_and_point_sequence_required',
		'shape_pt_sequence_strictly_increasing',
		'shape_dist_traveled_non_decreasing_with_sequence',
		'shape_sequence_position_mismatches_cumulative_traveled_distance',
		'shape_dist_traveled_delta_mismatches_haversine_segment',
		'shape_block_distance_rows_aggregated',
		'shape_dist_traveled_delta_mismatches_haversine_block',
	],
	stop_times: [
		'_file',
		'stop_times_trip_id_references_trips_table',
		'arrival_time_ordering_with_departure_and_frequencies',
		'departure_time_ordering_with_arrival_and_timepoint',
		'arrival_departure_time_non_decreasing_by_stop_sequence',
		'stop_times_stop_id_references_stops_table',
		'stop_headsign_present',
		'pickup_type_valid_gtfs_enum',
		'drop_off_type_valid_gtfs_enum',
		'stop_times_continuous_pickup_valid_gtfs_enum',
		'stop_times_continuous_drop_off_valid_gtfs_enum',
		'stop_times_shape_dist_traveled_non_decreasing_on_trip',
		'start_pickup_drop_off_window_valid',
		'end_pickup_drop_off_window_valid',
		'timepoint_valid_gtfs_enum',
		'pickup_booking_rule_id_references_booking_rules',
		'drop_off_booking_rule_id_references_booking_rules_or_empty',
		'location_group_id_consistent_with_trip_id_and_stops',
	],
	stops: [
		'_file',
		'stop_id_unique',
		'stop_code_valid',
		'stop_name_required_by_location_type',
		'stop_short_name_valid',
		'tts_stop_name_valid',
		'stop_desc_valid',
		'stop_lat_valid_latitude_range',
		'stop_lon_valid_longitude_range',
		'zone_id_valid',
		'stop_url_valid_url',
		'location_type_valid_enum',
		'parent_station_id_valid_for_stop_hierarchy',
		'stop_timezone_valid',
		'wheelchair_boarding_valid_enum',
		'level_id_valid_id',
		'platform_code_valid',
		'public_visible_valid_enum',
		'has_stop_sign_valid_enum',
		'has_shelter_valid_enum',
		'shelter_code_valid',
		'shelter_maintainer_valid',
		'has_bench_valid_enum',
		'has_network_map_valid_enum',
		'has_schedules_valid_enum',
		'has_pip_real_time_valid_enum',
		'has_tariffs_information_valid_enum',
		'region_id_valid',
		'municipality_id_valid',
		'parish_id_valid',
		'stop_access',
	],
	transfers: [
		'_file',
		'transfer_from_stop_id_references_stops_table',
		'transfer_from_route_id_references_routes_table',
		'transfer_from_trip_id_references_trips_table',
		'transfer_to_route_id_references_routes_table',
		'transfer_to_stop_id_references_stops_table',
		'transfer_to_trip_id_references_trips_table',
		'transfer_type_valid_gtfs_enum',
		'min_transfer_time_non_negative_seconds',
	],
	translations: [
		'_file',
		'table_name',
		'field_name',
		'language',
		'translation',
		'record_id',
		'record_sub_id',
		'field_value',
	],
	trips: [
		'_file',
		'route_id_references_routes_table',
		'pattern_id_present_and_references_consistent',
		'service_id_references_calendar_service',
		'trip_id_unique',
		'trip_headsign_present_when_short_name_absent',
		'trip_short_name_exclusivity',
		'direction_id_valid_enum',
		'block_id_in_allowed_set',
		'shape_id_references_shapes_table_when_present',
		'wheelchair_accessible_valid_gtfs_enum',
		'bikes_allowed_valid_gtfs_enum',
		'stop_sequence_increasing_by_one_along_trip',
		'direction_id_matches_feed_pattern_direction',
		'trip_id_limit_max_length',
		'pattern_id_matches_feed_pattern_id_syntax',
		'trip_path_stop_coordinates_referenced_from_stops',
		'pattern_id_trip_has_required_fields_for_grouping',
		'pattern_id_single_trip_signature_per_pattern',
		'route_id_consistent_for_all_patterns_in_trips',
		'direction_id_consistent_for_all_patterns_in_trips',
		'one_shape_id_per_pattern_id_group',
		'one_pattern_id_per_shape_id_group',
		'trip_headsign_consistent_for_all_patterns_in_trips',
		'shape_id_needs_to_be_the_same_as_pattern_id',
	],
	vehicles: [
		'_file',
		'vehicle_id_unique',
		'vehicle_agency_id_references_agency_table',
		'license_plate_format_per_market_rules',
		'vehicle_make_required',
		'vehicle_model_required',
		'vehicle_owner_required',
		'registration_date_valid_day_granularity',
		'available_seats_non_negative',
		'available_standing_non_negative',
		'typology_in_allowed_vehicle_types',
		'propulsion_type_valid_enum',
		'emission_code_valid_for_propulsion_type',
		'climatization_valid_enum',
		'wheelchair_spots_valid_enum',
		'lowered_floor_valid_enum',
		'ramp_valid_enum',
		'kneeling_valid_enum',
		'static_information_valid_enum',
		'onboard_monitor_valid_enum',
		'front_display_valid_enum',
		'rear_display_valid_enum',
		'side_display_valid_enum',
		'internal_sound_level_valid_enum',
		'external_sound_valid_enum',
		'consumption_meter_valid_format',
		'bicycles_rack_count_non_negative',
		'passenger_counting_valid_enum',
		'video_surveillance_valid_enum',
	],
} as const;

export type RuleGroup = keyof typeof ruleConfigKeys;

export type RuleConfigKey<G extends RuleGroup = RuleGroup> = typeof ruleConfigKeys[G][number];

export const ruleGroups = [
	'agency',
	'attributions',
	'calendar',
	'calendar_dates',
	'fare_attributes',
	'fare_media',
	'fare_rules',
	'feed_info',
	'file_validation',
	'frequencies',
	'levels',
	'pathways',
	'rider_categories',
	'routes',
	'shapes',
	'stop_times',
	'stops',
	'transfers',
	'translations',
	'trips',
	'vehicles',
] as const satisfies readonly RuleGroup[];

/* * */

/**
 * Rule ids emitted by the validator, one per catalogue entry.
 */
export const ruleIds = [
	'agency_email_valid_address',
	'agency_fare_url_valid_url',
	'agency_file_missing',
	'agency_id',
	'agency_id_matched_with_agency_name',
	'agency_id_unique',
	'agency_lang_valid_language_tag',
	'agency_name_present',
	'agency_phone_valid_phone_number',
	'agency_timezone_valid_id',
	'agency_url_valid_url',
	'agency_values_parse',
	'arrival_departure_time_non_decreasing_by_stop_sequence',
	'arrival_time_ordering_with_departure_and_frequencies',
	'at_most_one_default_fare_category',
	'attribution_email',
	'attribution_id',
	'attribution_phone',
	'attribution_url',
	'attributions_file_missing',
	'available_seats_non_negative',
	'available_standing_non_negative',
	'bicycles_rack_count_non_negative',
	'bikes_allowed_valid_gtfs_enum',
	'block_id_in_allowed_set',
	'calendar_dates_file_missing',
	'calendar_dates_service_id_references_calendar',
	'calendar_dates_values_parse',
	'calendar_end_date_valid_yyyymmdd',
	'calendar_file_missing',
	'calendar_service_id_unique_non_empty',
	'calendar_start_date_valid_yyyymmdd',
	'calendar_values_parse',
	'circular',
	'climatization_valid_enum',
	'consumption_meter_valid_format',
	'continuous_drop_off_valid_gtfs_enum',
	'continuous_pickup_valid_gtfs_enum',
	'currency_type_valid',
	'day_type',
	'default_lang_matches_feed_lang_when_present',
	'departure_time_ordering_with_arrival_and_timepoint',
	'direction_id_consistent_for_all_patterns_in_trips',
	'direction_id_matches_feed_pattern_direction',
	'direction_id_valid_enum',
	'drop_off_booking_rule_id_references_booking_rules_or_empty',
	'drop_off_type_valid_gtfs_enum',
	'eligibility_url_valid_http_url',
	'emission_code_valid_for_propulsion_type',
	'end_pickup_drop_off_window_valid',
	'exact_times_zero_when_timed_trip_uses_frequencies',
	'exception_date_valid_yyyymmdd',
	'exception_type_add_or_remove_service',
	'external_sound_valid_enum',
	'fare_attributes_agency_id_references_agency_table',
	'fare_attributes_file_missing',
	'fare_attributes_values_parse',
	'fare_id_unique',
	'fare_media_file_missing',
	'fare_media_id_unique',
	'fare_media_name_non_empty',
	'fare_media_type_valid',
	'fare_media_values_parse',
	'fare_price_valid_non_negative_decimal',
	'fare_rule_contains_id_references_zones_stops',
	'fare_rule_destination_id_references_zones_stops',
	'fare_rule_fare_id_references_fare_attributes',
	'fare_rule_origin_id_references_zones_stops',
	'fare_rule_route_id_references_routes',
	'fare_rules_file_missing',
	'fare_rules_values_parse',
	'feed_contact_email_valid_address',
	'feed_contact_url_valid_http_url',
	'feed_end_date_valid_yyyymmdd_not_before_start',
	'feed_info_file_missing',
	'feed_info_values_parse',
	'feed_lang_valid_tag',
	'feed_publisher_name_non_empty',
	'feed_publisher_url_valid_http_url',
	'feed_remarks',
	'feed_start_date_valid_yyyymmdd',
	'feed_type',
	'feed_version_valid_identifier',
	'field_name',
	'field_value',
	'file_not_found_in_rules',
	'file_validation',
	'frequencies_file_missing',
	'frequencies_trip_id_references_trips_table',
	'frequencies_values_parse',
	'frequency_end_time_valid',
	'frequency_start_time_valid',
	'friday',
	'front_display_valid_enum',
	'gtfs_feed_file_presence_and_integrity_rule',
	'has_bench_valid_enum',
	'has_network_map_valid_enum',
	'has_pip_real_time_valid_enum',
	'has_schedules_valid_enum',
	'has_shelter_valid_enum',
	'has_stop_sign_valid_enum',
	'has_tariffs_information_valid_enum',
	'headway_secs_positive_and_aligns_trip',
	'holiday',
	'internal_sound_level_valid_enum',
	'is_authority',
	'is_operator',
	'is_producer',
	'kneeling_valid_enum',
	'language',
	'level_id_unique',
	'level_id_valid_id',
	'level_index_required',
	'level_name',
	'levels_file_missing',
	'levels_parse',
	'license_plate_format_per_market_rules',
	'line_id_required',
	'line_long_name_present_when_line_id_present',
	'line_short_name_present_when_line_id_present',
	'location_group_id_consistent_with_trip_id_and_stops',
	'location_type_valid_enum',
	'lowered_floor_valid_enum',
	'min_transfer_time_non_negative_seconds',
	'monday',
	'municipality_id_valid',
	'network_id_references_networks_table',
	'onboard_monitor_valid_enum',
	'one_pattern_id_per_shape_id_group',
	'one_shape_id_per_pattern_id_group',
	'organization_name',
	'parent_station_id_valid_for_stop_hierarchy',
	'parish_id_valid',
	'passenger_counting_valid_enum',
	'path_type_valid_enum',
	'pathway_from_stop_id_references_stops_table',
	'pathway_id_unique',
	'pathway_is_bidirectional_valid_gtfs_enum',
	'pathway_length_non_negative',
	'pathway_max_slope_allowed_for_pathway_mode',
	'pathway_min_width_positive',
	'pathway_mode_valid_gtfs_enum',
	'pathway_reversed_signposted_as',
	'pathway_signposted_as',
	'pathway_stair_count',
	'pathway_to_stop_id_references_stops_table',
	'pathway_traversal_time_non_negative_seconds',
	'pathways_file_missing',
	'pathways_values_parse',
	'pattern_id_matches_feed_pattern_id_syntax',
	'pattern_id_present_and_references_consistent',
	'pattern_id_single_trip_signature_per_pattern',
	'pattern_id_trip_has_required_fields_for_grouping',
	'payment_method_valid_gtfs_enum',
	'period',
	'pickup_booking_rule_id_references_booking_rules',
	'pickup_type_valid_gtfs_enum',
	'platform_code_valid',
	'propulsion_type_valid_enum',
	'public_visible_valid_enum',
	'ramp_valid_enum',
	'rear_display_valid_enum',
	'record_id',
	'record_sub_id',
	'region_id_valid',
	'registration_date_valid_day_granularity',
	'rider_categories_file_missing',
	'rider_categories_values_parse',
	'rider_category_id_unique',
	'rider_category_name_non_empty',
	'route_agency_id_references_agency_table',
	'route_color_valid_hex_string',
	'route_desc_per_severity_and_content_rules',
	'route_id',
	'route_id_consistent_for_all_patterns_in_trips',
	'route_id_references_routes_table',
	'route_id_unique',
	'route_long_name_or_short_name_present',
	'route_remarks',
	'route_short_name_or_long_name_present',
	'route_sort_order_non_negative_integer',
	'route_text_color_valid_hex_contrast',
	'route_type_valid_gtfs_enum',
	'route_url_valid_http_url',
	'routes_file_missing',
	'routes_values_parse',
	'saturday',
	'school',
	'service_id_references_calendar_service',
	'shape_block_distance_rows_aggregated',
	'shape_dist_traveled_delta_mismatches_haversine_block',
	'shape_dist_traveled_delta_mismatches_haversine_segment',
	'shape_dist_traveled_non_decreasing_with_sequence',
	'shape_dist_traveled_non_negative_monotonic',
	'shape_id_and_point_sequence_required',
	'shape_id_needs_to_be_the_same_as_pattern_id',
	'shape_id_references_shapes_table_when_present',
	'shape_id_required',
	'shape_pt_lat_valid_latitude',
	'shape_pt_lon_valid_longitude',
	'shape_pt_sequence_not_repeated_within_shape',
	'shape_pt_sequence_strictly_increasing',
	'shape_sequence_position_mismatches_cumulative_traveled_distance',
	'shapes_file_missing',
	'shapes_values_parse',
	'shelter_code_valid',
	'shelter_maintainer_valid',
	'side_display_valid_enum',
	'start_pickup_drop_off_window_valid',
	'static_information_valid_enum',
	'stop_access_validation',
	'stop_code_valid',
	'stop_desc_valid',
	'stop_headsign_present',
	'stop_id_unique',
	'stop_lat_valid_latitude_range',
	'stop_lon_valid_longitude_range',
	'stop_name_required_by_location_type',
	'stop_sequence_increasing_by_one_along_trip',
	'stop_short_name_valid',
	'stop_times_continuous_drop_off_valid_gtfs_enum',
	'stop_times_continuous_pickup_valid_gtfs_enum',
	'stop_times_file_missing',
	'stop_times_shape_dist_traveled_non_decreasing_on_trip',
	'stop_times_stop_id_references_stops_table',
	'stop_times_trip_id_references_trips_table',
	'stop_times_values_parse',
	'stop_timezone_valid',
	'stop_url_valid_url',
	'stops_file_missing',
	'stops_values_parse',
	'sunday',
	'table_name',
	'thursday',
	'timepoint_valid_gtfs_enum',
	'transfer_duration_valid_seconds_range',
	'transfer_from_route_id_references_routes_table',
	'transfer_from_stop_id_references_stops_table',
	'transfer_from_trip_id_references_trips_table',
	'transfer_to_route_id_references_routes_table',
	'transfer_to_stop_id_references_stops_table',
	'transfer_to_trip_id_references_trips_table',
	'transfer_type_valid_gtfs_enum',
	'transfers_file_missing',
	'transfers_valid_gtfs_enum',
	'transfers_values_parse',
	'translation',
	'translations_file_missing',
	'trip_headsign_consistent_for_all_patterns_in_trips',
	'trip_headsign_present_when_short_name_absent',
	'trip_id',
	'trip_id_limit_max_length',
	'trip_id_unique',
	'trip_path_stop_coordinates_referenced_from_stops',
	'trip_short_name_exclusivity',
	'trips_file_missing',
	'trips_values_parse',
	'tts_stop_name_valid',
	'tuesday',
	'typology_in_allowed_vehicle_types',
	'vehicle_agency_id_references_agency_table',
	'vehicle_id_unique',
	'vehicle_make_required',
	'vehicle_model_required',
	'vehicle_owner_required',
	'vehicles_file_missing',
	'vehicles_values_parse',
	'video_surveillance_valid_enum',
	'wednesday',
	'wheelchair_accessible_valid_gtfs_enum',
	'wheelchair_boarding_valid_enum',
	'wheelchair_spots_valid_enum',
	'zone_id_valid',
] as const;

export type RuleId = typeof ruleIds[number];

/**
 * Rule ids that appear in validator messages, including shared ids that
 * several catalogue entries emit through output_ids.
 */
export type RuleOutputId = 'calendar_start_end_dates_valid_yyyymmdd_order' | RuleId;

/* * */

export interface RuleCompare {
	key: string
	value: string
}

export interface RuleConfig {
	compare?: RuleCompare[]
	depends_on?: string[]
	options?: string[]
	severity: RuleSeverity
}

export interface RuleCompareInput {
	key?: null | string
	value?: null | string
}

export interface RuleConfigInput {
	compare?: null | RuleCompareInput[]
	depends_on?: null | string[]
	options?: null | string[]
	severity?: RuleSeverity
}

/* * */

export interface AgencyRules {
	_file: RuleSeverity
	agency_email_valid_address: RuleConfig
	agency_fare_url_valid_url: RuleConfig
	agency_id_matched_with_agency_name: RuleConfig
	agency_id_unique: RuleConfig
	agency_lang_valid_language_tag: RuleConfig
	agency_name_present: RuleConfig
	agency_phone_valid_phone_number: RuleConfig
	agency_timezone_valid_id: RuleConfig
	agency_url_valid_url: RuleConfig
}

export interface AttributionsRules {
	_file: RuleSeverity
	agency_id: RuleConfig
	attribution_email: RuleConfig
	attribution_id: RuleConfig
	attribution_phone: RuleConfig
	attribution_url: RuleConfig
	is_authority: RuleConfig
	is_operator: RuleConfig
	is_producer: RuleConfig
	organization_name: RuleConfig
	route_id: RuleConfig
	trip_id: RuleConfig
}

export interface CalendarRules {
	_file: RuleSeverity
	calendar_end_date_valid_yyyymmdd: RuleConfig
	calendar_service_id_unique_non_empty: RuleConfig
	calendar_start_date_valid_yyyymmdd: RuleConfig
	friday: RuleConfig
	monday: RuleConfig
	saturday: RuleConfig
	sunday: RuleConfig
	thursday: RuleConfig
	tuesday: RuleConfig
	wednesday: RuleConfig
}

export interface CalendarDatesRules {
	_file: RuleSeverity
	calendar_dates_service_id_references_calendar: RuleConfig
	day_type: RuleConfig
	exception_date_valid_yyyymmdd: RuleConfig
	exception_type_add_or_remove_service: RuleConfig
	holiday: RuleConfig
	period: RuleConfig
}

export interface FareAttributesRules {
	_file: RuleSeverity
	currency_type_valid: RuleConfig
	fare_attributes_agency_id_references_agency_table: RuleConfig
	fare_id_unique: RuleConfig
	fare_price_valid_non_negative_decimal: RuleConfig
	payment_method_valid_gtfs_enum: RuleConfig
	transfer_duration_valid_seconds_range: RuleConfig
	transfers_valid_gtfs_enum: RuleConfig
}

export interface FareMediaRules {
	_file: RuleSeverity
	fare_media_id_unique: RuleConfig
	fare_media_name_non_empty: RuleConfig
	fare_media_type_valid: RuleConfig
}

export interface FareRulesRules {
	_file: RuleSeverity
	fare_rule_contains_id_references_zones_stops: RuleConfig
	fare_rule_destination_id_references_zones_stops: RuleConfig
	fare_rule_fare_id_references_fare_attributes: RuleConfig
	fare_rule_origin_id_references_zones_stops: RuleConfig
	fare_rule_route_id_references_routes: RuleConfig
}

export interface FeedInfoRules {
	_file: RuleSeverity
	default_lang_matches_feed_lang_when_present: RuleConfig
	feed_contact_email_valid_address: RuleConfig
	feed_contact_url_valid_http_url: RuleConfig
	feed_end_date_valid_yyyymmdd_not_before_start: RuleConfig
	feed_lang_valid_tag: RuleConfig
	feed_publisher_name_non_empty: RuleConfig
	feed_publisher_url_valid_http_url: RuleConfig
	feed_remarks: RuleConfig
	feed_start_date_valid_yyyymmdd: RuleConfig
	feed_type: RuleConfig
	feed_version_valid_identifier: RuleConfig
}

export interface FileValidationRules {
	_file: RuleSeverity
	gtfs_feed_file_presence_and_integrity_rule: RuleConfig
}

export interface FrequenciesRules {
	_file: RuleSeverity
	end_time: RuleConfig
	exact_times: RuleConfig
	headway_secs: RuleConfig
	start_time: RuleConfig
	trip_id: RuleConfig
}

export interface LevelsRules {
	_file: RuleSeverity
	level_id_unique: RuleConfig
	level_index_required: RuleConfig
	level_name: RuleConfig
}

export interface PathwaysRules {
	_file: RuleSeverity
	pathway_from_stop_id_references_stops_table: RuleConfig
	pathway_id_unique: RuleConfig
	pathway_is_bidirectional_valid_gtfs_enum: RuleConfig
	pathway_length_non_negative: RuleConfig
	pathway_max_slope_allowed_for_pathway_mode: RuleConfig
	pathway_min_width_positive: RuleConfig
	pathway_mode_valid_gtfs_enum: RuleConfig
	pathway_reversed_signposted_as: RuleConfig
	pathway_signposted_as: RuleConfig
	pathway_stair_count: RuleConfig
	pathway_to_stop_id_references_stops_table: RuleConfig
	pathway_traversal_time_non_negative_seconds: RuleConfig
}

export interface RiderCategoriesRules {
	_file: RuleSeverity
	at_most_one_default_fare_category: RuleConfig
	eligibility_url_valid_http_url: RuleConfig
	rider_category_id_unique: RuleConfig
	rider_category_name_non_empty: RuleConfig
}

export interface RoutesRules {
	_file: RuleSeverity
	circular: RuleConfig
	continuous_drop_off_valid_gtfs_enum: RuleConfig
	continuous_pickup_valid_gtfs_enum: RuleConfig
	line_id_required: RuleConfig
	line_long_name_present_when_line_id_present: RuleConfig
	line_short_name_present_when_line_id_present: RuleConfig
	network_id_references_networks_table: RuleConfig
	path_type_valid_enum: RuleConfig
	route_agency_id_references_agency_table: RuleConfig
	route_color_valid_hex_string: RuleConfig
	route_desc_per_severity_and_content_rules: RuleConfig
	route_id_unique: RuleConfig
	route_long_name_or_short_name_present: RuleConfig
	route_remarks: RuleConfig
	route_short_name_or_long_name_present: RuleConfig
	route_sort_order_non_negative_integer: RuleConfig
	route_text_color_valid_hex_contrast: RuleConfig
	route_type_valid_gtfs_enum: RuleConfig
	route_url_valid_http_url: RuleConfig
	school: RuleConfig
}

export interface ShapesRules {
	_file: RuleSeverity
	shape_block_distance_rows_aggregated: RuleConfig
	shape_dist_traveled_delta_mismatches_haversine_block: RuleConfig
	shape_dist_traveled_delta_mismatches_haversine_segment: RuleConfig
	shape_dist_traveled_non_decreasing_with_sequence: RuleConfig
	shape_dist_traveled_non_negative_monotonic: RuleConfig
	shape_id_and_point_sequence_required: RuleConfig
	shape_id_required: RuleConfig
	shape_pt_lat_valid_latitude: RuleConfig
	shape_pt_lon_valid_longitude: RuleConfig
	shape_pt_sequence_not_repeated_within_shape: RuleConfig
	shape_pt_sequence_strictly_increasing: RuleConfig
	shape_sequence_position_mismatches_cumulative_traveled_distance: RuleConfig
}

export interface StopTimesRules {
	_file: RuleSeverity
	arrival_departure_time_non_decreasing_by_stop_sequence: RuleConfig
	arrival_time_ordering_with_departure_and_frequencies: RuleConfig
	departure_time_ordering_with_arrival_and_timepoint: RuleConfig
	drop_off_booking_rule_id_references_booking_rules_or_empty: RuleConfig
	drop_off_type_valid_gtfs_enum: RuleConfig
	end_pickup_drop_off_window_valid: RuleConfig
	location_group_id_consistent_with_trip_id_and_stops: RuleConfig
	pickup_booking_rule_id_references_booking_rules: RuleConfig
	pickup_type_valid_gtfs_enum: RuleConfig
	start_pickup_drop_off_window_valid: RuleConfig
	stop_headsign_present: RuleConfig
	stop_times_continuous_drop_off_valid_gtfs_enum: RuleConfig
	stop_times_continuous_pickup_valid_gtfs_enum: RuleConfig
	stop_times_shape_dist_traveled_non_decreasing_on_trip: RuleConfig
	stop_times_stop_id_references_stops_table: RuleConfig
	stop_times_trip_id_references_trips_table: RuleConfig
	timepoint_valid_gtfs_enum: RuleConfig
}

export interface StopsRules {
	_file: RuleSeverity
	has_bench_valid_enum: RuleConfig
	has_network_map_valid_enum: RuleConfig
	has_pip_real_time_valid_enum: RuleConfig
	has_schedules_valid_enum: RuleConfig
	has_shelter_valid_enum: RuleConfig
	has_stop_sign_valid_enum: RuleConfig
	has_tariffs_information_valid_enum: RuleConfig
	level_id_valid_id: RuleConfig
	location_type_valid_enum: RuleConfig
	municipality_id_valid: RuleConfig
	parent_station_id_valid_for_stop_hierarchy: RuleConfig
	parish_id_valid: RuleConfig
	platform_code_valid: RuleConfig
	public_visible_valid_enum: RuleConfig
	region_id_valid: RuleConfig
	shelter_code_valid: RuleConfig
	shelter_maintainer_valid: RuleConfig
	stop_access: RuleConfig
	stop_code_valid: RuleConfig
	stop_desc_valid: RuleConfig
	stop_id_unique: RuleConfig
	stop_lat_valid_latitude_range: RuleConfig
	stop_lon_valid_longitude_range: RuleConfig
	stop_name_required_by_location_type: RuleConfig
	stop_short_name_valid: RuleConfig
	stop_timezone_valid: RuleConfig
	stop_url_valid_url: RuleConfig
	tts_stop_name_valid: RuleConfig
	wheelchair_boarding_valid_enum: RuleConfig
	zone_id_valid: RuleConfig
}

export interface TransfersRules {
	_file: RuleSeverity
	min_transfer_time_non_negative_seconds: RuleConfig
	transfer_from_route_id_references_routes_table: RuleConfig
	transfer_from_stop_id_references_stops_table: RuleConfig
	transfer_from_trip_id_references_trips_table: RuleConfig
	transfer_to_route_id_references_routes_table: RuleConfig
	transfer_to_stop_id_references_stops_table: RuleConfig
	transfer_to_trip_id_references_trips_table: RuleConfig
	transfer_type_valid_gtfs_enum: RuleConfig
}

export interface TranslationsRules {
	_file: RuleSeverity
	field_name: RuleConfig
	field_value: RuleConfig
	language: RuleConfig
	record_id: RuleConfig
	record_sub_id: RuleConfig
	table_name: RuleConfig
	translation: RuleConfig
}

export interface TripsRules {
	_file: RuleSeverity
	bikes_allowed_valid_gtfs_enum: RuleConfig
	block_id_in_allowed_set: RuleConfig
	direction_id_consistent_for_all_patterns_in_trips: RuleConfig
	direction_id_matches_feed_pattern_direction: RuleConfig
	direction_id_valid_enum: RuleConfig
	one_pattern_id_per_shape_id_group: RuleConfig
	one_shape_id_per_pattern_id_group: RuleConfig
	pattern_id_matches_feed_pattern_id_syntax: RuleConfig
	pattern_id_present_and_references_consistent: RuleConfig
	pattern_id_single_trip_signature_per_pattern: RuleConfig
	pattern_id_trip_has_required_fields_for_grouping: RuleConfig
	route_id_consistent_for_all_patterns_in_trips: RuleConfig
	route_id_references_routes_table: RuleConfig
	service_id_references_calendar_service: RuleConfig
	shape_id_needs_to_be_the_same_as_pattern_id: RuleConfig
	shape_id_references_shapes_table_when_present: RuleConfig
	stop_sequence_increasing_by_one_along_trip: RuleConfig
	trip_headsign_consistent_for_all_patterns_in_trips: RuleConfig
	trip_headsign_present_when_short_name_absent: RuleConfig
	trip_id_limit_max_length: RuleConfig
	trip_id_unique: RuleConfig
	trip_path_stop_coordinates_referenced_from_stops: RuleConfig
	trip_short_name_exclusivity: RuleConfig
	wheelchair_accessible_valid_gtfs_enum: RuleConfig
}

export interface VehiclesRules {
	_file: RuleSeverity
	available_seats_non_negative: RuleConfig
	available_standing_non_negative: RuleConfig
	bicycles_rack_count_non_negative: RuleConfig
	climatization_valid_enum: RuleConfig
	consumption_meter_valid_format: RuleConfig
	emission_code_valid_for_propulsion_type: RuleConfig
	external_sound_valid_enum: RuleConfig
	front_display_valid_enum: RuleConfig
	internal_sound_level_valid_enum: RuleConfig
	kneeling_valid_enum: RuleConfig
	license_plate_format_per_market_rules: RuleConfig
	lowered_floor_valid_enum: RuleConfig
	onboard_monitor_valid_enum: RuleConfig
	passenger_counting_valid_enum: RuleConfig
	propulsion_type_valid_enum: RuleConfig
	ramp_valid_enum: RuleConfig
	rear_display_valid_enum: RuleConfig
	registration_date_valid_day_granularity: RuleConfig
	side_display_valid_enum: RuleConfig
	static_information_valid_enum: RuleConfig
	typology_in_allowed_vehicle_types: RuleConfig
	vehicle_agency_id_references_agency_table: RuleConfig
	vehicle_id_unique: RuleConfig
	vehicle_make_required: RuleConfig
	vehicle_model_required: RuleConfig
	vehicle_owner_required: RuleConfig
	video_surveillance_valid_enum: RuleConfig
	wheelchair_spots_valid_enum: RuleConfig
}

export interface AgencyRulesInput {
	_file?: RuleSeverity
	agency_email_valid_address?: RuleConfigInput
	agency_fare_url_valid_url?: RuleConfigInput
	agency_id_matched_with_agency_name?: RuleConfigInput
	agency_id_unique?: RuleConfigInput
	agency_lang_valid_language_tag?: RuleConfigInput
	agency_name_present?: RuleConfigInput
	agency_phone_valid_phone_number?: RuleConfigInput
	agency_timezone_valid_id?: RuleConfigInput
	agency_url_valid_url?: RuleConfigInput
}

export interface AttributionsRulesInput {
	_file?: RuleSeverity
	agency_id?: RuleConfigInput
	attribution_email?: RuleConfigInput
	attribution_id?: RuleConfigInput
	attribution_phone?: RuleConfigInput
	attribution_url?: RuleConfigInput
	is_authority?: RuleConfigInput
	is_operator?: RuleConfigInput
	is_producer?: RuleConfigInput
	organization_name?: RuleConfigInput
	route_id?: RuleConfigInput
	trip_id?: RuleConfigInput
}

export interface CalendarRulesInput {
	_file?: RuleSeverity
	calendar_end_date_valid_yyyymmdd?: RuleConfigInput
	calendar_service_id_unique_non_empty?: RuleConfigInput
	calendar_start_date_valid_yyyymmdd?: RuleConfigInput
	friday?: RuleConfigInput
	monday?: RuleConfigInput
	saturday?: RuleConfigInput
	sunday?: RuleConfigInput
	thursday?: RuleConfigInput
	tuesday?: RuleConfigInput
	wednesday?: RuleConfigInput
}

export interface CalendarDatesRulesInput {
	_file?: RuleSeverity
	calendar_dates_service_id_references_calendar?: RuleConfigInput
	day_type?: RuleConfigInput
	exception_date_valid_yyyymmdd?: RuleConfigInput
	exception_type_add_or_remove_service?: RuleConfigInput
	holiday?: RuleConfigInput
	period?: RuleConfigInput
}

export interface FareAttributesRulesInput {
	_file?: RuleSeverity
	currency_type_valid?: RuleConfigInput
	fare_attributes_agency_id_references_agency_table?: RuleConfigInput
	fare_id_unique?: RuleConfigInput
	fare_price_valid_non_negative_decimal?: RuleConfigInput
	payment_method_valid_gtfs_enum?: RuleConfigInput
	transfer_duration_valid_seconds_range?: RuleConfigInput
	transfers_valid_gtfs_enum?: RuleConfigInput
}

export interface FareMediaRulesInput {
	_file?: RuleSeverity
	fare_media_id_unique?: RuleConfigInput
	fare_media_name_non_empty?: RuleConfigInput
	fare_media_type_valid?: RuleConfigInput
}

export interface FareRulesRulesInput {
	_file?: RuleSeverity
	fare_rule_contains_id_references_zones_stops?: RuleConfigInput
	fare_rule_destination_id_references_zones_stops?: RuleConfigInput
	fare_rule_fare_id_references_fare_attributes?: RuleConfigInput
	fare_rule_origin_id_references_zones_stops?: RuleConfigInput
	fare_rule_route_id_references_routes?: RuleConfigInput
}

export interface FeedInfoRulesInput {
	_file?: RuleSeverity
	default_lang_matches_feed_lang_when_present?: RuleConfigInput
	feed_contact_email_valid_address?: RuleConfigInput
	feed_contact_url_valid_http_url?: RuleConfigInput
	feed_end_date_valid_yyyymmdd_not_before_start?: RuleConfigInput
	feed_lang_valid_tag?: RuleConfigInput
	feed_publisher_name_non_empty?: RuleConfigInput
	feed_publisher_url_valid_http_url?: RuleConfigInput
	feed_remarks?: RuleConfigInput
	feed_start_date_valid_yyyymmdd?: RuleConfigInput
	feed_type?: RuleConfigInput
	feed_version_valid_identifier?: RuleConfigInput
}

export interface FileValidationRulesInput {
	_file?: RuleSeverity
	gtfs_feed_file_presence_and_integrity_rule?: RuleConfigInput
}

export interface FrequenciesRulesInput {
	_file?: RuleSeverity
	end_time?: RuleConfigInput
	exact_times?: RuleConfigInput
	headway_secs?: RuleConfigInput
	start_time?: RuleConfigInput
	trip_id?: RuleConfigInput
}

export interface LevelsRulesInput {
	_file?: RuleSeverity
	level_id_unique?: RuleConfigInput
	level_index_required?: RuleConfigInput
	level_name?: RuleConfigInput
}

export interface PathwaysRulesInput {
	_file?: RuleSeverity
	pathway_from_stop_id_references_stops_table?: RuleConfigInput
	pathway_id_unique?: RuleConfigInput
	pathway_is_bidirectional_valid_gtfs_enum?: RuleConfigInput
	pathway_length_non_negative?: RuleConfigInput
	pathway_max_slope_allowed_for_pathway_mode?: RuleConfigInput
	pathway_min_width_positive?: RuleConfigInput
	pathway_mode_valid_gtfs_enum?: RuleConfigInput
	pathway_reversed_signposted_as?: RuleConfigInput
	pathway_signposted_as?: RuleConfigInput
	pathway_stair_count?: RuleConfigInput
	pathway_to_stop_id_references_stops_table?: RuleConfigInput
	pathway_traversal_time_non_negative_seconds?: RuleConfigInput
}

export interface RiderCategoriesRulesInput {
	_file?: RuleSeverity
	at_most_one_default_fare_category?: RuleConfigInput
	eligibility_url_valid_http_url?: RuleConfigInput
	rider_category_id_unique?: RuleConfigInput
	rider_category_name_non_empty?: RuleConfigInput
}

export interface RoutesRulesInput {
	_file?: RuleSeverity
	circular?: RuleConfigInput
	continuous_drop_off_valid_gtfs_enum?: RuleConfigInput
	continuous_pickup_valid_gtfs_enum?: RuleConfigInput
	line_id_required?: RuleConfigInput
	line_long_name_present_when_line_id_present?: RuleConfigInput
	line_short_name_present_when_line_id_present?: RuleConfigInput
	network_id_references_networks_table?: RuleConfigInput
	path_type_valid_enum?: RuleConfigInput
	route_agency_id_references_agency_table?: RuleConfigInput
	route_color_valid_hex_string?: RuleConfigInput
	route_desc_per_severity_and_content_rules?: RuleConfigInput
	route_id_unique?: RuleConfigInput
	route_long_name_or_short_name_present?: RuleConfigInput
	route_remarks?: RuleConfigInput
	route_short_name_or_long_name_present?: RuleConfigInput
	route_sort_order_non_negative_integer?: RuleConfigInput
	route_text_color_valid_hex_contrast?: RuleConfigInput
	route_type_valid_gtfs_enum?: RuleConfigInput
	route_url_valid_http_url?: RuleConfigInput
	school?: RuleConfigInput
}

export interface ShapesRulesInput {
	_file?: RuleSeverity
	shape_block_distance_rows_aggregated?: RuleConfigInput
	shape_dist_traveled_delta_mismatches_haversine_block?: RuleConfigInput
	shape_dist_traveled_delta_mismatches_haversine_segment?: RuleConfigInput
	shape_dist_traveled_non_decreasing_with_sequence?: RuleConfigInput
	shape_dist_traveled_non_negative_monotonic?: RuleConfigInput
	shape_id_and_point_sequence_required?: RuleConfigInput
	shape_id_required?: RuleConfigInput
	shape_pt_lat_valid_latitude?: RuleConfigInput
	shape_pt_lon_valid_longitude?: RuleConfigInput
	shape_pt_sequence_not_repeated_within_shape?: RuleConfigInput
	shape_pt_sequence_strictly_increasing?: RuleConfigInput
	shape_sequence_position_mismatches_cumulative_traveled_distance?: RuleConfigInput
}

export interface StopTimesRulesInput {
	_file?: RuleSeverity
	arrival_departure_time_non_decreasing_by_stop_sequence?: RuleConfigInput
	arrival_time_ordering_with_departure_and_frequencies?: RuleConfigInput
	departure_time_ordering_with_arrival_and_timepoint?: RuleConfigInput
	drop_off_booking_rule_id_references_booking_rules_or_empty?: RuleConfigInput
	drop_off_type_valid_gtfs_enum?: RuleConfigInput
	end_pickup_drop_off_window_valid?: RuleConfigInput
	location_group_id_consistent_with_trip_id_and_stops?: RuleConfigInput
	pickup_booking_rule_id_references_booking_rules?: RuleConfigInput
	pickup_type_valid_gtfs_enum?: RuleConfigInput
	start_pickup_drop_off_window_valid?: RuleConfigInput
	stop_headsign_present?: RuleConfigInput
	stop_times_continuous_drop_off_valid_gtfs_enum?: RuleConfigInput
	stop_times_continuous_pickup_valid_gtfs_enum?: RuleConfigInput
	stop_times_shape_dist_traveled_non_decreasing_on_trip?: RuleConfigInput
	stop_times_stop_id_references_stops_table?: RuleConfigInput
	stop_times_trip_id_references_trips_table?: RuleConfigInput
	timepoint_valid_gtfs_enum?: RuleConfigInput
}

export interface StopsRulesInput {
	_file?: RuleSeverity
	has_bench_valid_enum?: RuleConfigInput
	has_network_map_valid_enum?: RuleConfigInput
	has_pip_real_time_valid_enum?: RuleConfigInput
	has_schedules_valid_enum?: RuleConfigInput
	has_shelter_valid_enum?: RuleConfigInput
	has_stop_sign_valid_enum?: RuleConfigInput
	has_tariffs_information_valid_enum?: RuleConfigInput
	level_id_valid_id?: RuleConfigInput
	location_type_valid_enum?: RuleConfigInput
	municipality_id_valid?: RuleConfigInput
	parent_station_id_valid_for_stop_hierarchy?: RuleConfigInput
	parish_id_valid?: RuleConfigInput
	platform_code_valid?: RuleConfigInput
	public_visible_valid_enum?: RuleConfigInput
	region_id_valid?: RuleConfigInput
	shelter_code_valid?: RuleConfigInput
	shelter_maintainer_valid?: RuleConfigInput
	stop_access?: RuleConfigInput
	stop_code_valid?: RuleConfigInput
	stop_desc_valid?: RuleConfigInput
	stop_id_unique?: RuleConfigInput
	stop_lat_valid_latitude_range?: RuleConfigInput
	stop_lon_valid_longitude_range?: RuleConfigInput
	stop_name_required_by_location_type?: RuleConfigInput
	stop_short_name_valid?: RuleConfigInput
	stop_timezone_valid?: RuleConfigInput
	stop_url_valid_url?: RuleConfigInput
	tts_stop_name_valid?: RuleConfigInput
	wheelchair_boarding_valid_enum?: RuleConfigInput
	zone_id_valid?: RuleConfigInput
}

export interface TransfersRulesInput {
	_file?: RuleSeverity
	min_transfer_time_non_negative_seconds?: RuleConfigInput
	transfer_from_route_id_references_routes_table?: RuleConfigInput
	transfer_from_stop_id_references_stops_table?: RuleConfigInput
	transfer_from_trip_id_references_trips_table?: RuleConfigInput
	transfer_to_route_id_references_routes_table?: RuleConfigInput
	transfer_to_stop_id_references_stops_table?: RuleConfigInput
	transfer_to_trip_id_references_trips_table?: RuleConfigInput
	transfer_type_valid_gtfs_enum?: RuleConfigInput
}

export interface TranslationsRulesInput {
	_file?: RuleSeverity
	field_name?: RuleConfigInput
	field_value?: RuleConfigInput
	language?: RuleConfigInput
	record_id?: RuleConfigInput
	record_sub_id?: RuleConfigInput
	table_name?: RuleConfigInput
	translation?: RuleConfigInput
}

export interface TripsRulesInput {
	_file?: RuleSeverity
	bikes_allowed_valid_gtfs_enum?: RuleConfigInput
	block_id_in_allowed_set?: RuleConfigInput
	direction_id_consistent_for_all_patterns_in_trips?: RuleConfigInput
	direction_id_matches_feed_pattern_direction?: RuleConfigInput
	direction_id_valid_enum?: RuleConfigInput
	one_pattern_id_per_shape_id_group?: RuleConfigInput
	one_shape_id_per_pattern_id_group?: RuleConfigInput
	pattern_id_matches_feed_pattern_id_syntax?: RuleConfigInput
	pattern_id_present_and_references_consistent?: RuleConfigInput
	pattern_id_single_trip_signature_per_pattern?: RuleConfigInput
	pattern_id_trip_has_required_fields_for_grouping?: RuleConfigInput
	route_id_consistent_for_all_patterns_in_trips?: RuleConfigInput
	route_id_references_routes_table?: RuleConfigInput
	service_id_references_calendar_service?: RuleConfigInput
	shape_id_needs_to_be_the_same_as_pattern_id?: RuleConfigInput
	shape_id_references_shapes_table_when_present?: RuleConfigInput
	stop_sequence_increasing_by_one_along_trip?: RuleConfigInput
	trip_headsign_consistent_for_all_patterns_in_trips?: RuleConfigInput
	trip_headsign_present_when_short_name_absent?: RuleConfigInput
	trip_id_limit_max_length?: RuleConfigInput
	trip_id_unique?: RuleConfigInput
	trip_path_stop_coordinates_referenced_from_stops?: RuleConfigInput
	trip_short_name_exclusivity?: RuleConfigInput
	wheelchair_accessible_valid_gtfs_enum?: RuleConfigInput
}

export interface VehiclesRulesInput {
	_file?: RuleSeverity
	available_seats_non_negative?: RuleConfigInput
	available_standing_non_negative?: RuleConfigInput
	bicycles_rack_count_non_negative?: RuleConfigInput
	climatization_valid_enum?: RuleConfigInput
	consumption_meter_valid_format?: RuleConfigInput
	emission_code_valid_for_propulsion_type?: RuleConfigInput
	external_sound_valid_enum?: RuleConfigInput
	front_display_valid_enum?: RuleConfigInput
	internal_sound_level_valid_enum?: RuleConfigInput
	kneeling_valid_enum?: RuleConfigInput
	license_plate_format_per_market_rules?: RuleConfigInput
	lowered_floor_valid_enum?: RuleConfigInput
	onboard_monitor_valid_enum?: RuleConfigInput
	passenger_counting_valid_enum?: RuleConfigInput
	propulsion_type_valid_enum?: RuleConfigInput
	ramp_valid_enum?: RuleConfigInput
	rear_display_valid_enum?: RuleConfigInput
	registration_date_valid_day_granularity?: RuleConfigInput
	side_display_valid_enum?: RuleConfigInput
	static_information_valid_enum?: RuleConfigInput
	typology_in_allowed_vehicle_types?: RuleConfigInput
	vehicle_agency_id_references_agency_table?: RuleConfigInput
	vehicle_id_unique?: RuleConfigInput
	vehicle_make_required?: RuleConfigInput
	vehicle_model_required?: RuleConfigInput
	vehicle_owner_required?: RuleConfigInput
	video_surveillance_valid_enum?: RuleConfigInput
	wheelchair_spots_valid_enum?: RuleConfigInput
}

/**
 * Rules after the Go validator filled every omitted setting.
 * Source: types.GtfsRules
 */
export interface ValidationRules {
	agency: AgencyRules
	attributions: AttributionsRules
	calendar: CalendarRules
	calendar_dates: CalendarDatesRules
	fare_attributes: FareAttributesRules
	fare_media: FareMediaRules
	fare_rules: FareRulesRules
	feed_info: FeedInfoRules
	file_validation: FileValidationRules
	frequencies: FrequenciesRules
	levels: LevelsRules
	pathways: PathwaysRules
	rider_categories: RiderCategoriesRules
	routes: RoutesRules
	shapes: ShapesRules
	stop_times: StopTimesRules
	stops: StopsRules
	transfers: TransfersRules
	translations: TranslationsRules
	trips: TripsRules
	vehicles: VehiclesRules
}

/**
 * Rules as saved for an agency and accepted by the Go validator.
 */
export interface ValidationRulesInput {
	agency?: AgencyRulesInput
	attributions?: AttributionsRulesInput
	calendar?: CalendarRulesInput
	calendar_dates?: CalendarDatesRulesInput
	fare_attributes?: FareAttributesRulesInput
	fare_media?: FareMediaRulesInput
	fare_rules?: FareRulesRulesInput
	feed_info?: FeedInfoRulesInput
	file_validation?: FileValidationRulesInput
	frequencies?: FrequenciesRulesInput
	levels?: LevelsRulesInput
	pathways?: PathwaysRulesInput
	rider_categories?: RiderCategoriesRulesInput
	routes?: RoutesRulesInput
	shapes?: ShapesRulesInput
	stop_times?: StopTimesRulesInput
	stops?: StopsRulesInput
	transfers?: TransfersRulesInput
	translations?: TranslationsRulesInput
	trips?: TripsRulesInput
	vehicles?: VehiclesRulesInput
}

/* * */

/**
 * A rule whose severity is stored under config_key in its section.
 * Only real group/key combinations are accepted.
 */
export type EditableRuleCatalogueEntry = {
	[G in RuleGroup]: {
		[K in RuleConfigKey<G>]: {
			config_key: K
			editable: true
			group: G
			id: RuleId
			message_field?: string
			output_ids?: readonly RuleOutputId[]
			severities?: never
			severity?: never
		}
	}[RuleConfigKey<G>]
}[RuleGroup];

/**
 * A technical notice with a severity fixed by the validator.
 */
export interface FixedRuleCatalogueEntry {
	config_key?: never
	editable: false
	group: RuleGroup
	id: RuleId
	message_field?: never
	output_ids?: never
	severities?: readonly RuleSeverity[]
	severity?: RuleSeverity
}

export type RuleCatalogueEntry = EditableRuleCatalogueEntry | FixedRuleCatalogueEntry;

/* * */

export const ruleCatalogue: readonly RuleCatalogueEntry[] = [
	{
		config_key: 'agency_email_valid_address',
		editable: true,
		group: 'agency',
		id: 'agency_email_valid_address',
	},
	{
		config_key: 'agency_fare_url_valid_url',
		editable: true,
		group: 'agency',
		id: 'agency_fare_url_valid_url',
	},
	{
		config_key: '_file',
		editable: true,
		group: 'agency',
		id: 'agency_file_missing',
	},
	{
		config_key: 'agency_id_matched_with_agency_name',
		editable: true,
		group: 'agency',
		id: 'agency_id_matched_with_agency_name',
	},
	{
		config_key: 'agency_id_unique',
		editable: true,
		group: 'agency',
		id: 'agency_id_unique',
	},
	{
		config_key: 'agency_lang_valid_language_tag',
		editable: true,
		group: 'agency',
		id: 'agency_lang_valid_language_tag',
	},
	{
		config_key: 'agency_name_present',
		editable: true,
		group: 'agency',
		id: 'agency_name_present',
	},
	{
		config_key: 'agency_phone_valid_phone_number',
		editable: true,
		group: 'agency',
		id: 'agency_phone_valid_phone_number',
	},
	{
		config_key: 'agency_timezone_valid_id',
		editable: true,
		group: 'agency',
		id: 'agency_timezone_valid_id',
	},
	{
		config_key: 'agency_url_valid_url',
		editable: true,
		group: 'agency',
		id: 'agency_url_valid_url',
	},
	{
		editable: false,
		group: 'agency',
		id: 'agency_values_parse',
		severity: 'error',
	},
	{
		config_key: 'agency_id',
		editable: true,
		group: 'attributions',
		id: 'agency_id',
	},
	{
		config_key: 'attribution_email',
		editable: true,
		group: 'attributions',
		id: 'attribution_email',
	},
	{
		config_key: 'attribution_id',
		editable: true,
		group: 'attributions',
		id: 'attribution_id',
	},
	{
		config_key: 'attribution_phone',
		editable: true,
		group: 'attributions',
		id: 'attribution_phone',
	},
	{
		config_key: 'attribution_url',
		editable: true,
		group: 'attributions',
		id: 'attribution_url',
	},
	{
		config_key: '_file',
		editable: true,
		group: 'attributions',
		id: 'attributions_file_missing',
	},
	{
		config_key: 'is_authority',
		editable: true,
		group: 'attributions',
		id: 'is_authority',
	},
	{
		config_key: 'is_operator',
		editable: true,
		group: 'attributions',
		id: 'is_operator',
	},
	{
		config_key: 'is_producer',
		editable: true,
		group: 'attributions',
		id: 'is_producer',
	},
	{
		config_key: 'organization_name',
		editable: true,
		group: 'attributions',
		id: 'organization_name',
	},
	{
		config_key: 'route_id',
		editable: true,
		group: 'attributions',
		id: 'route_id',
	},
	{
		config_key: 'trip_id',
		editable: true,
		group: 'attributions',
		id: 'trip_id',
	},
	{
		config_key: 'calendar_end_date_valid_yyyymmdd',
		editable: true,
		group: 'calendar',
		id: 'calendar_end_date_valid_yyyymmdd',
		message_field: 'end_date',
		output_ids: ['calendar_start_end_dates_valid_yyyymmdd_order'],
	},
	{
		config_key: '_file',
		editable: true,
		group: 'calendar',
		id: 'calendar_file_missing',
	},
	{
		config_key: 'calendar_service_id_unique_non_empty',
		editable: true,
		group: 'calendar',
		id: 'calendar_service_id_unique_non_empty',
	},
	{
		config_key: 'calendar_start_date_valid_yyyymmdd',
		editable: true,
		group: 'calendar',
		id: 'calendar_start_date_valid_yyyymmdd',
		message_field: 'start_date',
		output_ids: ['calendar_start_end_dates_valid_yyyymmdd_order'],
	},
	{
		editable: false,
		group: 'calendar',
		id: 'calendar_values_parse',
		severity: 'error',
	},
	{
		config_key: 'friday',
		editable: true,
		group: 'calendar',
		id: 'friday',
	},
	{
		config_key: 'monday',
		editable: true,
		group: 'calendar',
		id: 'monday',
	},
	{
		config_key: 'saturday',
		editable: true,
		group: 'calendar',
		id: 'saturday',
	},
	{
		config_key: 'sunday',
		editable: true,
		group: 'calendar',
		id: 'sunday',
	},
	{
		config_key: 'thursday',
		editable: true,
		group: 'calendar',
		id: 'thursday',
	},
	{
		config_key: 'tuesday',
		editable: true,
		group: 'calendar',
		id: 'tuesday',
	},
	{
		config_key: 'wednesday',
		editable: true,
		group: 'calendar',
		id: 'wednesday',
	},
	{
		config_key: '_file',
		editable: true,
		group: 'calendar_dates',
		id: 'calendar_dates_file_missing',
	},
	{
		config_key: 'calendar_dates_service_id_references_calendar',
		editable: true,
		group: 'calendar_dates',
		id: 'calendar_dates_service_id_references_calendar',
	},
	{
		editable: false,
		group: 'calendar_dates',
		id: 'calendar_dates_values_parse',
		severity: 'error',
	},
	{
		config_key: 'day_type',
		editable: true,
		group: 'calendar_dates',
		id: 'day_type',
	},
	{
		config_key: 'exception_date_valid_yyyymmdd',
		editable: true,
		group: 'calendar_dates',
		id: 'exception_date_valid_yyyymmdd',
	},
	{
		config_key: 'exception_type_add_or_remove_service',
		editable: true,
		group: 'calendar_dates',
		id: 'exception_type_add_or_remove_service',
	},
	{
		config_key: 'holiday',
		editable: true,
		group: 'calendar_dates',
		id: 'holiday',
	},
	{
		config_key: 'period',
		editable: true,
		group: 'calendar_dates',
		id: 'period',
	},
	{
		config_key: 'currency_type_valid',
		editable: true,
		group: 'fare_attributes',
		id: 'currency_type_valid',
	},
	{
		config_key: 'fare_attributes_agency_id_references_agency_table',
		editable: true,
		group: 'fare_attributes',
		id: 'fare_attributes_agency_id_references_agency_table',
	},
	{
		config_key: '_file',
		editable: true,
		group: 'fare_attributes',
		id: 'fare_attributes_file_missing',
	},
	{
		editable: false,
		group: 'fare_attributes',
		id: 'fare_attributes_values_parse',
		severity: 'error',
	},
	{
		config_key: 'fare_id_unique',
		editable: true,
		group: 'fare_attributes',
		id: 'fare_id_unique',
	},
	{
		config_key: 'fare_price_valid_non_negative_decimal',
		editable: true,
		group: 'fare_attributes',
		id: 'fare_price_valid_non_negative_decimal',
	},
	{
		config_key: 'payment_method_valid_gtfs_enum',
		editable: true,
		group: 'fare_attributes',
		id: 'payment_method_valid_gtfs_enum',
	},
	{
		config_key: 'transfer_duration_valid_seconds_range',
		editable: true,
		group: 'fare_attributes',
		id: 'transfer_duration_valid_seconds_range',
	},
	{
		config_key: 'transfers_valid_gtfs_enum',
		editable: true,
		group: 'fare_attributes',
		id: 'transfers_valid_gtfs_enum',
	},
	{
		config_key: '_file',
		editable: true,
		group: 'fare_media',
		id: 'fare_media_file_missing',
	},
	{
		config_key: 'fare_media_id_unique',
		editable: true,
		group: 'fare_media',
		id: 'fare_media_id_unique',
	},
	{
		config_key: 'fare_media_name_non_empty',
		editable: true,
		group: 'fare_media',
		id: 'fare_media_name_non_empty',
	},
	{
		config_key: 'fare_media_type_valid',
		editable: true,
		group: 'fare_media',
		id: 'fare_media_type_valid',
	},
	{
		editable: false,
		group: 'fare_media',
		id: 'fare_media_values_parse',
		severity: 'error',
	},
	{
		config_key: 'fare_rule_contains_id_references_zones_stops',
		editable: true,
		group: 'fare_rules',
		id: 'fare_rule_contains_id_references_zones_stops',
	},
	{
		config_key: 'fare_rule_destination_id_references_zones_stops',
		editable: true,
		group: 'fare_rules',
		id: 'fare_rule_destination_id_references_zones_stops',
	},
	{
		config_key: 'fare_rule_fare_id_references_fare_attributes',
		editable: true,
		group: 'fare_rules',
		id: 'fare_rule_fare_id_references_fare_attributes',
	},
	{
		config_key: 'fare_rule_origin_id_references_zones_stops',
		editable: true,
		group: 'fare_rules',
		id: 'fare_rule_origin_id_references_zones_stops',
	},
	{
		config_key: 'fare_rule_route_id_references_routes',
		editable: true,
		group: 'fare_rules',
		id: 'fare_rule_route_id_references_routes',
	},
	{
		config_key: '_file',
		editable: true,
		group: 'fare_rules',
		id: 'fare_rules_file_missing',
	},
	{
		editable: false,
		group: 'fare_rules',
		id: 'fare_rules_values_parse',
		severity: 'error',
	},
	{
		config_key: 'default_lang_matches_feed_lang_when_present',
		editable: true,
		group: 'feed_info',
		id: 'default_lang_matches_feed_lang_when_present',
	},
	{
		config_key: 'feed_contact_email_valid_address',
		editable: true,
		group: 'feed_info',
		id: 'feed_contact_email_valid_address',
	},
	{
		config_key: 'feed_contact_url_valid_http_url',
		editable: true,
		group: 'feed_info',
		id: 'feed_contact_url_valid_http_url',
	},
	{
		config_key: 'feed_end_date_valid_yyyymmdd_not_before_start',
		editable: true,
		group: 'feed_info',
		id: 'feed_end_date_valid_yyyymmdd_not_before_start',
	},
	{
		config_key: '_file',
		editable: true,
		group: 'feed_info',
		id: 'feed_info_file_missing',
	},
	{
		editable: false,
		group: 'feed_info',
		id: 'feed_info_values_parse',
		severity: 'error',
	},
	{
		config_key: 'feed_lang_valid_tag',
		editable: true,
		group: 'feed_info',
		id: 'feed_lang_valid_tag',
	},
	{
		config_key: 'feed_publisher_name_non_empty',
		editable: true,
		group: 'feed_info',
		id: 'feed_publisher_name_non_empty',
	},
	{
		config_key: 'feed_publisher_url_valid_http_url',
		editable: true,
		group: 'feed_info',
		id: 'feed_publisher_url_valid_http_url',
	},
	{
		config_key: 'feed_remarks',
		editable: true,
		group: 'feed_info',
		id: 'feed_remarks',
	},
	{
		config_key: 'feed_start_date_valid_yyyymmdd',
		editable: true,
		group: 'feed_info',
		id: 'feed_start_date_valid_yyyymmdd',
	},
	{
		config_key: 'feed_type',
		editable: true,
		group: 'feed_info',
		id: 'feed_type',
	},
	{
		config_key: 'feed_version_valid_identifier',
		editable: true,
		group: 'feed_info',
		id: 'feed_version_valid_identifier',
	},
	{
		editable: false,
		group: 'file_validation',
		id: 'file_not_found_in_rules',
		severity: 'warning',
	},
	{
		editable: false,
		group: 'file_validation',
		id: 'file_validation',
		severities: ['error', 'ignore'],
	},
	{
		config_key: 'gtfs_feed_file_presence_and_integrity_rule',
		editable: true,
		group: 'file_validation',
		id: 'gtfs_feed_file_presence_and_integrity_rule',
	},
	{
		config_key: 'exact_times',
		editable: true,
		group: 'frequencies',
		id: 'exact_times_zero_when_timed_trip_uses_frequencies',
	},
	{
		config_key: '_file',
		editable: true,
		group: 'frequencies',
		id: 'frequencies_file_missing',
	},
	{
		config_key: 'trip_id',
		editable: true,
		group: 'frequencies',
		id: 'frequencies_trip_id_references_trips_table',
	},
	{
		editable: false,
		group: 'frequencies',
		id: 'frequencies_values_parse',
		severity: 'error',
	},
	{
		config_key: 'end_time',
		editable: true,
		group: 'frequencies',
		id: 'frequency_end_time_valid',
	},
	{
		config_key: 'start_time',
		editable: true,
		group: 'frequencies',
		id: 'frequency_start_time_valid',
	},
	{
		config_key: 'headway_secs',
		editable: true,
		group: 'frequencies',
		id: 'headway_secs_positive_and_aligns_trip',
	},
	{
		config_key: 'level_id_unique',
		editable: true,
		group: 'levels',
		id: 'level_id_unique',
	},
	{
		config_key: 'level_index_required',
		editable: true,
		group: 'levels',
		id: 'level_index_required',
	},
	{
		config_key: 'level_name',
		editable: true,
		group: 'levels',
		id: 'level_name',
	},
	{
		config_key: '_file',
		editable: true,
		group: 'levels',
		id: 'levels_file_missing',
	},
	{
		editable: false,
		group: 'levels',
		id: 'levels_parse',
		severity: 'error',
	},
	{
		config_key: 'pathway_from_stop_id_references_stops_table',
		editable: true,
		group: 'pathways',
		id: 'pathway_from_stop_id_references_stops_table',
	},
	{
		config_key: 'pathway_id_unique',
		editable: true,
		group: 'pathways',
		id: 'pathway_id_unique',
	},
	{
		config_key: 'pathway_is_bidirectional_valid_gtfs_enum',
		editable: true,
		group: 'pathways',
		id: 'pathway_is_bidirectional_valid_gtfs_enum',
	},
	{
		config_key: 'pathway_length_non_negative',
		editable: true,
		group: 'pathways',
		id: 'pathway_length_non_negative',
	},
	{
		config_key: 'pathway_max_slope_allowed_for_pathway_mode',
		editable: true,
		group: 'pathways',
		id: 'pathway_max_slope_allowed_for_pathway_mode',
	},
	{
		config_key: 'pathway_min_width_positive',
		editable: true,
		group: 'pathways',
		id: 'pathway_min_width_positive',
	},
	{
		config_key: 'pathway_mode_valid_gtfs_enum',
		editable: true,
		group: 'pathways',
		id: 'pathway_mode_valid_gtfs_enum',
	},
	{
		config_key: 'pathway_reversed_signposted_as',
		editable: true,
		group: 'pathways',
		id: 'pathway_reversed_signposted_as',
	},
	{
		config_key: 'pathway_signposted_as',
		editable: true,
		group: 'pathways',
		id: 'pathway_signposted_as',
	},
	{
		config_key: 'pathway_stair_count',
		editable: true,
		group: 'pathways',
		id: 'pathway_stair_count',
	},
	{
		config_key: 'pathway_to_stop_id_references_stops_table',
		editable: true,
		group: 'pathways',
		id: 'pathway_to_stop_id_references_stops_table',
	},
	{
		config_key: 'pathway_traversal_time_non_negative_seconds',
		editable: true,
		group: 'pathways',
		id: 'pathway_traversal_time_non_negative_seconds',
	},
	{
		config_key: '_file',
		editable: true,
		group: 'pathways',
		id: 'pathways_file_missing',
	},
	{
		editable: false,
		group: 'pathways',
		id: 'pathways_values_parse',
		severity: 'error',
	},
	{
		config_key: 'at_most_one_default_fare_category',
		editable: true,
		group: 'rider_categories',
		id: 'at_most_one_default_fare_category',
	},
	{
		config_key: 'eligibility_url_valid_http_url',
		editable: true,
		group: 'rider_categories',
		id: 'eligibility_url_valid_http_url',
	},
	{
		config_key: '_file',
		editable: true,
		group: 'rider_categories',
		id: 'rider_categories_file_missing',
	},
	{
		editable: false,
		group: 'rider_categories',
		id: 'rider_categories_values_parse',
		severity: 'error',
	},
	{
		config_key: 'rider_category_id_unique',
		editable: true,
		group: 'rider_categories',
		id: 'rider_category_id_unique',
	},
	{
		config_key: 'rider_category_name_non_empty',
		editable: true,
		group: 'rider_categories',
		id: 'rider_category_name_non_empty',
	},
	{
		config_key: 'circular',
		editable: true,
		group: 'routes',
		id: 'circular',
	},
	{
		config_key: 'continuous_drop_off_valid_gtfs_enum',
		editable: true,
		group: 'routes',
		id: 'continuous_drop_off_valid_gtfs_enum',
	},
	{
		config_key: 'continuous_pickup_valid_gtfs_enum',
		editable: true,
		group: 'routes',
		id: 'continuous_pickup_valid_gtfs_enum',
	},
	{
		config_key: 'line_id_required',
		editable: true,
		group: 'routes',
		id: 'line_id_required',
	},
	{
		config_key: 'line_long_name_present_when_line_id_present',
		editable: true,
		group: 'routes',
		id: 'line_long_name_present_when_line_id_present',
	},
	{
		config_key: 'line_short_name_present_when_line_id_present',
		editable: true,
		group: 'routes',
		id: 'line_short_name_present_when_line_id_present',
	},
	{
		config_key: 'network_id_references_networks_table',
		editable: true,
		group: 'routes',
		id: 'network_id_references_networks_table',
	},
	{
		config_key: 'path_type_valid_enum',
		editable: true,
		group: 'routes',
		id: 'path_type_valid_enum',
	},
	{
		config_key: 'route_agency_id_references_agency_table',
		editable: true,
		group: 'routes',
		id: 'route_agency_id_references_agency_table',
	},
	{
		config_key: 'route_color_valid_hex_string',
		editable: true,
		group: 'routes',
		id: 'route_color_valid_hex_string',
	},
	{
		config_key: 'route_desc_per_severity_and_content_rules',
		editable: true,
		group: 'routes',
		id: 'route_desc_per_severity_and_content_rules',
	},
	{
		config_key: 'route_id_unique',
		editable: true,
		group: 'routes',
		id: 'route_id_unique',
	},
	{
		config_key: 'route_long_name_or_short_name_present',
		editable: true,
		group: 'routes',
		id: 'route_long_name_or_short_name_present',
	},
	{
		config_key: 'route_remarks',
		editable: true,
		group: 'routes',
		id: 'route_remarks',
	},
	{
		config_key: 'route_short_name_or_long_name_present',
		editable: true,
		group: 'routes',
		id: 'route_short_name_or_long_name_present',
	},
	{
		config_key: 'route_sort_order_non_negative_integer',
		editable: true,
		group: 'routes',
		id: 'route_sort_order_non_negative_integer',
	},
	{
		config_key: 'route_text_color_valid_hex_contrast',
		editable: true,
		group: 'routes',
		id: 'route_text_color_valid_hex_contrast',
	},
	{
		config_key: 'route_type_valid_gtfs_enum',
		editable: true,
		group: 'routes',
		id: 'route_type_valid_gtfs_enum',
	},
	{
		config_key: 'route_url_valid_http_url',
		editable: true,
		group: 'routes',
		id: 'route_url_valid_http_url',
	},
	{
		config_key: '_file',
		editable: true,
		group: 'routes',
		id: 'routes_file_missing',
	},
	{
		editable: false,
		group: 'routes',
		id: 'routes_values_parse',
		severity: 'error',
	},
	{
		config_key: 'school',
		editable: true,
		group: 'routes',
		id: 'school',
	},
	{
		config_key: 'shape_block_distance_rows_aggregated',
		editable: true,
		group: 'shapes',
		id: 'shape_block_distance_rows_aggregated',
	},
	{
		config_key: 'shape_dist_traveled_delta_mismatches_haversine_block',
		editable: true,
		group: 'shapes',
		id: 'shape_dist_traveled_delta_mismatches_haversine_block',
	},
	{
		config_key: 'shape_dist_traveled_delta_mismatches_haversine_segment',
		editable: true,
		group: 'shapes',
		id: 'shape_dist_traveled_delta_mismatches_haversine_segment',
	},
	{
		config_key: 'shape_dist_traveled_non_decreasing_with_sequence',
		editable: true,
		group: 'shapes',
		id: 'shape_dist_traveled_non_decreasing_with_sequence',
	},
	{
		config_key: 'shape_dist_traveled_non_negative_monotonic',
		editable: true,
		group: 'shapes',
		id: 'shape_dist_traveled_non_negative_monotonic',
	},
	{
		config_key: 'shape_id_and_point_sequence_required',
		editable: true,
		group: 'shapes',
		id: 'shape_id_and_point_sequence_required',
	},
	{
		config_key: 'shape_id_required',
		editable: true,
		group: 'shapes',
		id: 'shape_id_required',
	},
	{
		config_key: 'shape_pt_lat_valid_latitude',
		editable: true,
		group: 'shapes',
		id: 'shape_pt_lat_valid_latitude',
	},
	{
		config_key: 'shape_pt_lon_valid_longitude',
		editable: true,
		group: 'shapes',
		id: 'shape_pt_lon_valid_longitude',
	},
	{
		config_key: 'shape_pt_sequence_not_repeated_within_shape',
		editable: true,
		group: 'shapes',
		id: 'shape_pt_sequence_not_repeated_within_shape',
	},
	{
		config_key: 'shape_pt_sequence_strictly_increasing',
		editable: true,
		group: 'shapes',
		id: 'shape_pt_sequence_strictly_increasing',
	},
	{
		config_key: 'shape_sequence_position_mismatches_cumulative_traveled_distance',
		editable: true,
		group: 'shapes',
		id: 'shape_sequence_position_mismatches_cumulative_traveled_distance',
	},
	{
		config_key: '_file',
		editable: true,
		group: 'shapes',
		id: 'shapes_file_missing',
	},
	{
		editable: false,
		group: 'shapes',
		id: 'shapes_values_parse',
		severity: 'error',
	},
	{
		config_key: 'arrival_departure_time_non_decreasing_by_stop_sequence',
		editable: true,
		group: 'stop_times',
		id: 'arrival_departure_time_non_decreasing_by_stop_sequence',
	},
	{
		config_key: 'arrival_time_ordering_with_departure_and_frequencies',
		editable: true,
		group: 'stop_times',
		id: 'arrival_time_ordering_with_departure_and_frequencies',
	},
	{
		config_key: 'departure_time_ordering_with_arrival_and_timepoint',
		editable: true,
		group: 'stop_times',
		id: 'departure_time_ordering_with_arrival_and_timepoint',
	},
	{
		config_key: 'drop_off_booking_rule_id_references_booking_rules_or_empty',
		editable: true,
		group: 'stop_times',
		id: 'drop_off_booking_rule_id_references_booking_rules_or_empty',
	},
	{
		config_key: 'drop_off_type_valid_gtfs_enum',
		editable: true,
		group: 'stop_times',
		id: 'drop_off_type_valid_gtfs_enum',
	},
	{
		config_key: 'end_pickup_drop_off_window_valid',
		editable: true,
		group: 'stop_times',
		id: 'end_pickup_drop_off_window_valid',
	},
	{
		config_key: 'location_group_id_consistent_with_trip_id_and_stops',
		editable: true,
		group: 'stop_times',
		id: 'location_group_id_consistent_with_trip_id_and_stops',
	},
	{
		config_key: 'pickup_booking_rule_id_references_booking_rules',
		editable: true,
		group: 'stop_times',
		id: 'pickup_booking_rule_id_references_booking_rules',
	},
	{
		config_key: 'pickup_type_valid_gtfs_enum',
		editable: true,
		group: 'stop_times',
		id: 'pickup_type_valid_gtfs_enum',
	},
	{
		config_key: 'start_pickup_drop_off_window_valid',
		editable: true,
		group: 'stop_times',
		id: 'start_pickup_drop_off_window_valid',
	},
	{
		config_key: 'stop_headsign_present',
		editable: true,
		group: 'stop_times',
		id: 'stop_headsign_present',
	},
	{
		config_key: 'stop_times_continuous_drop_off_valid_gtfs_enum',
		editable: true,
		group: 'stop_times',
		id: 'stop_times_continuous_drop_off_valid_gtfs_enum',
	},
	{
		config_key: 'stop_times_continuous_pickup_valid_gtfs_enum',
		editable: true,
		group: 'stop_times',
		id: 'stop_times_continuous_pickup_valid_gtfs_enum',
	},
	{
		config_key: '_file',
		editable: true,
		group: 'stop_times',
		id: 'stop_times_file_missing',
	},
	{
		config_key: 'stop_times_shape_dist_traveled_non_decreasing_on_trip',
		editable: true,
		group: 'stop_times',
		id: 'stop_times_shape_dist_traveled_non_decreasing_on_trip',
	},
	{
		config_key: 'stop_times_stop_id_references_stops_table',
		editable: true,
		group: 'stop_times',
		id: 'stop_times_stop_id_references_stops_table',
	},
	{
		config_key: 'stop_times_trip_id_references_trips_table',
		editable: true,
		group: 'stop_times',
		id: 'stop_times_trip_id_references_trips_table',
	},
	{
		editable: false,
		group: 'stop_times',
		id: 'stop_times_values_parse',
		severity: 'error',
	},
	{
		config_key: 'timepoint_valid_gtfs_enum',
		editable: true,
		group: 'stop_times',
		id: 'timepoint_valid_gtfs_enum',
	},
	{
		config_key: 'has_bench_valid_enum',
		editable: true,
		group: 'stops',
		id: 'has_bench_valid_enum',
	},
	{
		config_key: 'has_network_map_valid_enum',
		editable: true,
		group: 'stops',
		id: 'has_network_map_valid_enum',
	},
	{
		config_key: 'has_pip_real_time_valid_enum',
		editable: true,
		group: 'stops',
		id: 'has_pip_real_time_valid_enum',
	},
	{
		config_key: 'has_schedules_valid_enum',
		editable: true,
		group: 'stops',
		id: 'has_schedules_valid_enum',
	},
	{
		config_key: 'has_shelter_valid_enum',
		editable: true,
		group: 'stops',
		id: 'has_shelter_valid_enum',
	},
	{
		config_key: 'has_stop_sign_valid_enum',
		editable: true,
		group: 'stops',
		id: 'has_stop_sign_valid_enum',
	},
	{
		config_key: 'has_tariffs_information_valid_enum',
		editable: true,
		group: 'stops',
		id: 'has_tariffs_information_valid_enum',
	},
	{
		config_key: 'level_id_valid_id',
		editable: true,
		group: 'stops',
		id: 'level_id_valid_id',
	},
	{
		config_key: 'location_type_valid_enum',
		editable: true,
		group: 'stops',
		id: 'location_type_valid_enum',
	},
	{
		config_key: 'municipality_id_valid',
		editable: true,
		group: 'stops',
		id: 'municipality_id_valid',
	},
	{
		config_key: 'parent_station_id_valid_for_stop_hierarchy',
		editable: true,
		group: 'stops',
		id: 'parent_station_id_valid_for_stop_hierarchy',
	},
	{
		config_key: 'parish_id_valid',
		editable: true,
		group: 'stops',
		id: 'parish_id_valid',
	},
	{
		config_key: 'platform_code_valid',
		editable: true,
		group: 'stops',
		id: 'platform_code_valid',
	},
	{
		config_key: 'public_visible_valid_enum',
		editable: true,
		group: 'stops',
		id: 'public_visible_valid_enum',
	},
	{
		config_key: 'region_id_valid',
		editable: true,
		group: 'stops',
		id: 'region_id_valid',
	},
	{
		config_key: 'shelter_code_valid',
		editable: true,
		group: 'stops',
		id: 'shelter_code_valid',
	},
	{
		config_key: 'shelter_maintainer_valid',
		editable: true,
		group: 'stops',
		id: 'shelter_maintainer_valid',
	},
	{
		config_key: 'stop_access',
		editable: true,
		group: 'stops',
		id: 'stop_access_validation',
	},
	{
		config_key: 'stop_code_valid',
		editable: true,
		group: 'stops',
		id: 'stop_code_valid',
	},
	{
		config_key: 'stop_desc_valid',
		editable: true,
		group: 'stops',
		id: 'stop_desc_valid',
	},
	{
		config_key: 'stop_id_unique',
		editable: true,
		group: 'stops',
		id: 'stop_id_unique',
	},
	{
		config_key: 'stop_lat_valid_latitude_range',
		editable: true,
		group: 'stops',
		id: 'stop_lat_valid_latitude_range',
	},
	{
		config_key: 'stop_lon_valid_longitude_range',
		editable: true,
		group: 'stops',
		id: 'stop_lon_valid_longitude_range',
	},
	{
		config_key: 'stop_name_required_by_location_type',
		editable: true,
		group: 'stops',
		id: 'stop_name_required_by_location_type',
	},
	{
		config_key: 'stop_short_name_valid',
		editable: true,
		group: 'stops',
		id: 'stop_short_name_valid',
	},
	{
		config_key: 'stop_timezone_valid',
		editable: true,
		group: 'stops',
		id: 'stop_timezone_valid',
	},
	{
		config_key: 'stop_url_valid_url',
		editable: true,
		group: 'stops',
		id: 'stop_url_valid_url',
	},
	{
		config_key: '_file',
		editable: true,
		group: 'stops',
		id: 'stops_file_missing',
	},
	{
		editable: false,
		group: 'stops',
		id: 'stops_values_parse',
		severity: 'error',
	},
	{
		config_key: 'tts_stop_name_valid',
		editable: true,
		group: 'stops',
		id: 'tts_stop_name_valid',
	},
	{
		config_key: 'wheelchair_boarding_valid_enum',
		editable: true,
		group: 'stops',
		id: 'wheelchair_boarding_valid_enum',
	},
	{
		config_key: 'zone_id_valid',
		editable: true,
		group: 'stops',
		id: 'zone_id_valid',
	},
	{
		config_key: 'min_transfer_time_non_negative_seconds',
		editable: true,
		group: 'transfers',
		id: 'min_transfer_time_non_negative_seconds',
	},
	{
		config_key: 'transfer_from_route_id_references_routes_table',
		editable: true,
		group: 'transfers',
		id: 'transfer_from_route_id_references_routes_table',
	},
	{
		config_key: 'transfer_from_stop_id_references_stops_table',
		editable: true,
		group: 'transfers',
		id: 'transfer_from_stop_id_references_stops_table',
	},
	{
		config_key: 'transfer_from_trip_id_references_trips_table',
		editable: true,
		group: 'transfers',
		id: 'transfer_from_trip_id_references_trips_table',
	},
	{
		config_key: 'transfer_to_route_id_references_routes_table',
		editable: true,
		group: 'transfers',
		id: 'transfer_to_route_id_references_routes_table',
	},
	{
		config_key: 'transfer_to_stop_id_references_stops_table',
		editable: true,
		group: 'transfers',
		id: 'transfer_to_stop_id_references_stops_table',
	},
	{
		config_key: 'transfer_to_trip_id_references_trips_table',
		editable: true,
		group: 'transfers',
		id: 'transfer_to_trip_id_references_trips_table',
	},
	{
		config_key: 'transfer_type_valid_gtfs_enum',
		editable: true,
		group: 'transfers',
		id: 'transfer_type_valid_gtfs_enum',
	},
	{
		config_key: '_file',
		editable: true,
		group: 'transfers',
		id: 'transfers_file_missing',
	},
	{
		editable: false,
		group: 'transfers',
		id: 'transfers_values_parse',
		severity: 'error',
	},
	{
		config_key: 'field_name',
		editable: true,
		group: 'translations',
		id: 'field_name',
	},
	{
		config_key: 'field_value',
		editable: true,
		group: 'translations',
		id: 'field_value',
	},
	{
		config_key: 'language',
		editable: true,
		group: 'translations',
		id: 'language',
	},
	{
		config_key: 'record_id',
		editable: true,
		group: 'translations',
		id: 'record_id',
	},
	{
		config_key: 'record_sub_id',
		editable: true,
		group: 'translations',
		id: 'record_sub_id',
	},
	{
		config_key: 'table_name',
		editable: true,
		group: 'translations',
		id: 'table_name',
	},
	{
		config_key: 'translation',
		editable: true,
		group: 'translations',
		id: 'translation',
	},
	{
		config_key: '_file',
		editable: true,
		group: 'translations',
		id: 'translations_file_missing',
	},
	{
		config_key: 'bikes_allowed_valid_gtfs_enum',
		editable: true,
		group: 'trips',
		id: 'bikes_allowed_valid_gtfs_enum',
	},
	{
		config_key: 'block_id_in_allowed_set',
		editable: true,
		group: 'trips',
		id: 'block_id_in_allowed_set',
	},
	{
		config_key: 'direction_id_consistent_for_all_patterns_in_trips',
		editable: true,
		group: 'trips',
		id: 'direction_id_consistent_for_all_patterns_in_trips',
	},
	{
		config_key: 'direction_id_matches_feed_pattern_direction',
		editable: true,
		group: 'trips',
		id: 'direction_id_matches_feed_pattern_direction',
	},
	{
		config_key: 'direction_id_valid_enum',
		editable: true,
		group: 'trips',
		id: 'direction_id_valid_enum',
	},
	{
		config_key: 'one_pattern_id_per_shape_id_group',
		editable: true,
		group: 'trips',
		id: 'one_pattern_id_per_shape_id_group',
	},
	{
		config_key: 'one_shape_id_per_pattern_id_group',
		editable: true,
		group: 'trips',
		id: 'one_shape_id_per_pattern_id_group',
	},
	{
		config_key: 'pattern_id_matches_feed_pattern_id_syntax',
		editable: true,
		group: 'trips',
		id: 'pattern_id_matches_feed_pattern_id_syntax',
	},
	{
		config_key: 'pattern_id_present_and_references_consistent',
		editable: true,
		group: 'trips',
		id: 'pattern_id_present_and_references_consistent',
	},
	{
		config_key: 'pattern_id_single_trip_signature_per_pattern',
		editable: true,
		group: 'trips',
		id: 'pattern_id_single_trip_signature_per_pattern',
	},
	{
		config_key: 'pattern_id_trip_has_required_fields_for_grouping',
		editable: true,
		group: 'trips',
		id: 'pattern_id_trip_has_required_fields_for_grouping',
	},
	{
		config_key: 'route_id_consistent_for_all_patterns_in_trips',
		editable: true,
		group: 'trips',
		id: 'route_id_consistent_for_all_patterns_in_trips',
	},
	{
		config_key: 'route_id_references_routes_table',
		editable: true,
		group: 'trips',
		id: 'route_id_references_routes_table',
	},
	{
		config_key: 'service_id_references_calendar_service',
		editable: true,
		group: 'trips',
		id: 'service_id_references_calendar_service',
	},
	{
		config_key: 'shape_id_needs_to_be_the_same_as_pattern_id',
		editable: true,
		group: 'trips',
		id: 'shape_id_needs_to_be_the_same_as_pattern_id',
	},
	{
		config_key: 'shape_id_references_shapes_table_when_present',
		editable: true,
		group: 'trips',
		id: 'shape_id_references_shapes_table_when_present',
	},
	{
		config_key: 'stop_sequence_increasing_by_one_along_trip',
		editable: true,
		group: 'trips',
		id: 'stop_sequence_increasing_by_one_along_trip',
	},
	{
		config_key: 'trip_headsign_consistent_for_all_patterns_in_trips',
		editable: true,
		group: 'trips',
		id: 'trip_headsign_consistent_for_all_patterns_in_trips',
	},
	{
		config_key: 'trip_headsign_present_when_short_name_absent',
		editable: true,
		group: 'trips',
		id: 'trip_headsign_present_when_short_name_absent',
	},
	{
		config_key: 'trip_id_limit_max_length',
		editable: true,
		group: 'trips',
		id: 'trip_id_limit_max_length',
	},
	{
		config_key: 'trip_id_unique',
		editable: true,
		group: 'trips',
		id: 'trip_id_unique',
	},
	{
		config_key: 'trip_path_stop_coordinates_referenced_from_stops',
		editable: true,
		group: 'trips',
		id: 'trip_path_stop_coordinates_referenced_from_stops',
	},
	{
		config_key: 'trip_short_name_exclusivity',
		editable: true,
		group: 'trips',
		id: 'trip_short_name_exclusivity',
	},
	{
		config_key: '_file',
		editable: true,
		group: 'trips',
		id: 'trips_file_missing',
	},
	{
		editable: false,
		group: 'trips',
		id: 'trips_values_parse',
		severity: 'error',
	},
	{
		config_key: 'wheelchair_accessible_valid_gtfs_enum',
		editable: true,
		group: 'trips',
		id: 'wheelchair_accessible_valid_gtfs_enum',
	},
	{
		config_key: 'available_seats_non_negative',
		editable: true,
		group: 'vehicles',
		id: 'available_seats_non_negative',
	},
	{
		config_key: 'available_standing_non_negative',
		editable: true,
		group: 'vehicles',
		id: 'available_standing_non_negative',
	},
	{
		config_key: 'bicycles_rack_count_non_negative',
		editable: true,
		group: 'vehicles',
		id: 'bicycles_rack_count_non_negative',
	},
	{
		config_key: 'climatization_valid_enum',
		editable: true,
		group: 'vehicles',
		id: 'climatization_valid_enum',
	},
	{
		config_key: 'consumption_meter_valid_format',
		editable: true,
		group: 'vehicles',
		id: 'consumption_meter_valid_format',
	},
	{
		config_key: 'emission_code_valid_for_propulsion_type',
		editable: true,
		group: 'vehicles',
		id: 'emission_code_valid_for_propulsion_type',
	},
	{
		config_key: 'external_sound_valid_enum',
		editable: true,
		group: 'vehicles',
		id: 'external_sound_valid_enum',
	},
	{
		config_key: 'front_display_valid_enum',
		editable: true,
		group: 'vehicles',
		id: 'front_display_valid_enum',
	},
	{
		config_key: 'internal_sound_level_valid_enum',
		editable: true,
		group: 'vehicles',
		id: 'internal_sound_level_valid_enum',
	},
	{
		config_key: 'kneeling_valid_enum',
		editable: true,
		group: 'vehicles',
		id: 'kneeling_valid_enum',
	},
	{
		config_key: 'license_plate_format_per_market_rules',
		editable: true,
		group: 'vehicles',
		id: 'license_plate_format_per_market_rules',
	},
	{
		config_key: 'lowered_floor_valid_enum',
		editable: true,
		group: 'vehicles',
		id: 'lowered_floor_valid_enum',
	},
	{
		config_key: 'onboard_monitor_valid_enum',
		editable: true,
		group: 'vehicles',
		id: 'onboard_monitor_valid_enum',
	},
	{
		config_key: 'passenger_counting_valid_enum',
		editable: true,
		group: 'vehicles',
		id: 'passenger_counting_valid_enum',
	},
	{
		config_key: 'propulsion_type_valid_enum',
		editable: true,
		group: 'vehicles',
		id: 'propulsion_type_valid_enum',
	},
	{
		config_key: 'ramp_valid_enum',
		editable: true,
		group: 'vehicles',
		id: 'ramp_valid_enum',
	},
	{
		config_key: 'rear_display_valid_enum',
		editable: true,
		group: 'vehicles',
		id: 'rear_display_valid_enum',
	},
	{
		config_key: 'registration_date_valid_day_granularity',
		editable: true,
		group: 'vehicles',
		id: 'registration_date_valid_day_granularity',
	},
	{
		config_key: 'side_display_valid_enum',
		editable: true,
		group: 'vehicles',
		id: 'side_display_valid_enum',
	},
	{
		config_key: 'static_information_valid_enum',
		editable: true,
		group: 'vehicles',
		id: 'static_information_valid_enum',
	},
	{
		config_key: 'typology_in_allowed_vehicle_types',
		editable: true,
		group: 'vehicles',
		id: 'typology_in_allowed_vehicle_types',
	},
	{
		config_key: 'vehicle_agency_id_references_agency_table',
		editable: true,
		group: 'vehicles',
		id: 'vehicle_agency_id_references_agency_table',
	},
	{
		config_key: 'vehicle_id_unique',
		editable: true,
		group: 'vehicles',
		id: 'vehicle_id_unique',
	},
	{
		config_key: 'vehicle_make_required',
		editable: true,
		group: 'vehicles',
		id: 'vehicle_make_required',
	},
	{
		config_key: 'vehicle_model_required',
		editable: true,
		group: 'vehicles',
		id: 'vehicle_model_required',
	},
	{
		config_key: 'vehicle_owner_required',
		editable: true,
		group: 'vehicles',
		id: 'vehicle_owner_required',
	},
	{
		config_key: '_file',
		editable: true,
		group: 'vehicles',
		id: 'vehicles_file_missing',
	},
	{
		editable: false,
		group: 'vehicles',
		id: 'vehicles_values_parse',
		severity: 'error',
	},
	{
		config_key: 'video_surveillance_valid_enum',
		editable: true,
		group: 'vehicles',
		id: 'video_surveillance_valid_enum',
	},
	{
		config_key: 'wheelchair_spots_valid_enum',
		editable: true,
		group: 'vehicles',
		id: 'wheelchair_spots_valid_enum',
	},
];
