/**
 * This file is auto-generated by the rules-catalogue command of the Go validator.
 * Do not edit this file manually. Run `npm run repo:validator-rules` to regenerate.
 *
 * Source: types.GtfsRules, types.RuleConfig and rules.Catalogue() in
 * modules/operation/apps/validator/validator/src
 *
 * Configuration types describe what the Go decoder produces. The *Input types
 * describe what it accepts: every key may be omitted (Go fills the default),
 * and null is allowed where Go ignores it or decodes it to nil. Severities,
 * sections and rule objects reject null, as rules.DecodeConfig does.
 * These are compile-time types only. They do not validate anything at runtime.
 */

import { type RuleSeverity } from './rules-severities.js';

/* * */

export interface RuleCompare {
	key: string
	value: string
}

export interface RuleConfig {
	compare?: RuleCompare[]
	depends_on?: string[]
	options?: string[]
	severity: RuleSeverity
}

/* * */

export interface AgencyRules {
	_file: RuleSeverity
	agency_email_valid_address: RuleConfig
	agency_fare_url_valid_url: RuleConfig
	agency_id_matched_with_agency_name: RuleConfig
	agency_id_unique: RuleConfig
	agency_lang_valid_language_tag: RuleConfig
	agency_name_present: RuleConfig
	agency_phone_valid_phone_number: RuleConfig
	agency_timezone_valid_id: RuleConfig
	agency_url_valid_url: RuleConfig
}

export interface CalendarRules {
	_file: RuleSeverity
	calendar_end_date_valid_yyyymmdd: RuleConfig
	calendar_service_id_unique_non_empty: RuleConfig
	calendar_start_date_valid_yyyymmdd: RuleConfig
	friday: RuleConfig
	monday: RuleConfig
	saturday: RuleConfig
	sunday: RuleConfig
	thursday: RuleConfig
	tuesday: RuleConfig
	wednesday: RuleConfig
}

export interface CalendarDatesRules {
	_file: RuleSeverity
	calendar_dates_service_id_references_calendar: RuleConfig
	day_type: RuleConfig
	exception_date_valid_yyyymmdd: RuleConfig
	exception_type_add_or_remove_service: RuleConfig
	holiday: RuleConfig
	period: RuleConfig
}

export interface FareAttributesRules {
	_file: RuleSeverity
	currency_type_valid: RuleConfig
	fare_attributes_agency_id_references_agency_table: RuleConfig
	fare_id_unique: RuleConfig
	fare_price_valid_non_negative_decimal: RuleConfig
	payment_method_valid_gtfs_enum: RuleConfig
	transfer_duration_valid_seconds_range: RuleConfig
	transfers_valid_gtfs_enum: RuleConfig
}

export interface FareMediaRules {
	_file: RuleSeverity
	fare_media_id_unique: RuleConfig
	fare_media_name_non_empty: RuleConfig
	fare_media_type_valid: RuleConfig
}

export interface FareRulesRules {
	_file: RuleSeverity
	fare_rule_contains_id_references_zones_stops: RuleConfig
	fare_rule_destination_id_references_zones_stops: RuleConfig
	fare_rule_fare_id_references_fare_attributes: RuleConfig
	fare_rule_origin_id_references_zones_stops: RuleConfig
	fare_rule_route_id_references_routes: RuleConfig
}

export interface FeedInfoRules {
	_file: RuleSeverity
	default_lang_matches_feed_lang_when_present: RuleConfig
	feed_contact_email_valid_address: RuleConfig
	feed_contact_url_valid_http_url: RuleConfig
	feed_end_date_valid_yyyymmdd_not_before_start: RuleConfig
	feed_lang_valid_tag: RuleConfig
	feed_publisher_name_non_empty: RuleConfig
	feed_publisher_url_valid_http_url: RuleConfig
	feed_remarks: RuleConfig
	feed_start_date_valid_yyyymmdd: RuleConfig
	feed_type: RuleConfig
	feed_version_valid_identifier: RuleConfig
}

export interface FileValidationRules {
	_file: RuleSeverity
	gtfs_feed_file_presence_and_integrity_rule: RuleConfig
}

export interface FrequenciesRules {
	_file: RuleSeverity
	exact_times_zero_when_timed_trip_uses_frequencies: RuleConfig
	frequencies_trip_id_references_trips_table: RuleConfig
	frequency_end_time_valid: RuleConfig
	frequency_start_time_valid: RuleConfig
	headway_secs_positive_and_aligns_trip: RuleConfig
}

export interface LevelsRules {
	_file: RuleSeverity
	level_id_unique: RuleConfig
	level_index_required: RuleConfig
	level_name: RuleConfig
}

export interface PathwaysRules {
	_file: RuleSeverity
	pathway_from_stop_id_references_stops_table: RuleConfig
	pathway_id_unique: RuleConfig
	pathway_is_bidirectional_valid_gtfs_enum: RuleConfig
	pathway_length_non_negative: RuleConfig
	pathway_max_slope_allowed_for_pathway_mode: RuleConfig
	pathway_min_width_positive: RuleConfig
	pathway_mode_valid_gtfs_enum: RuleConfig
	pathway_reversed_signposted_as: RuleConfig
	pathway_signposted_as: RuleConfig
	pathway_stair_count: RuleConfig
	pathway_to_stop_id_references_stops_table: RuleConfig
	pathway_traversal_time_non_negative_seconds: RuleConfig
}

export interface RiderCategoriesRules {
	_file: RuleSeverity
	at_most_one_default_fare_category: RuleConfig
	eligibility_url_valid_http_url: RuleConfig
	rider_category_id_unique: RuleConfig
	rider_category_name_non_empty: RuleConfig
}

export interface RoutesRules {
	_file: RuleSeverity
	circular: RuleConfig
	continuous_drop_off_valid_gtfs_enum: RuleConfig
	continuous_pickup_valid_gtfs_enum: RuleConfig
	line_id_required: RuleConfig
	line_long_name_present_when_line_id_present: RuleConfig
	line_short_name_present_when_line_id_present: RuleConfig
	network_id_references_networks_table: RuleConfig
	path_type_valid_enum: RuleConfig
	route_agency_id_references_agency_table: RuleConfig
	route_color_valid_hex_string: RuleConfig
	route_desc_per_severity_and_content_rules: RuleConfig
	route_id_unique: RuleConfig
	route_long_name_or_short_name_present: RuleConfig
	route_remarks: RuleConfig
	route_short_name_or_long_name_present: RuleConfig
	route_sort_order_non_negative_integer: RuleConfig
	route_text_color_valid_hex_contrast: RuleConfig
	route_type_valid_gtfs_enum: RuleConfig
	route_url_valid_http_url: RuleConfig
	school: RuleConfig
}

export interface ShapesRules {
	_file: RuleSeverity
	shape_block_distance_rows_aggregated: RuleConfig
	shape_dist_traveled_delta_mismatches_haversine_block: RuleConfig
	shape_dist_traveled_delta_mismatches_haversine_segment: RuleConfig
	shape_dist_traveled_non_decreasing_with_sequence: RuleConfig
	shape_dist_traveled_non_negative_monotonic: RuleConfig
	shape_id_and_point_sequence_required: RuleConfig
	shape_id_required: RuleConfig
	shape_pt_lat_valid_latitude: RuleConfig
	shape_pt_lon_valid_longitude: RuleConfig
	shape_pt_sequence_not_repeated_within_shape: RuleConfig
	shape_pt_sequence_strictly_increasing: RuleConfig
	shape_sequence_position_mismatches_cumulative_traveled_distance: RuleConfig
}

export interface StopTimesRules {
	_file: RuleSeverity
	arrival_departure_time_non_decreasing_by_stop_sequence: RuleConfig
	arrival_time_ordering_with_departure_and_frequencies: RuleConfig
	departure_time_ordering_with_arrival_and_timepoint: RuleConfig
	drop_off_booking_rule_id_references_booking_rules_or_empty: RuleConfig
	drop_off_type_valid_gtfs_enum: RuleConfig
	end_pickup_drop_off_window_valid: RuleConfig
	location_group_id_consistent_with_trip_id_and_stops: RuleConfig
	pickup_booking_rule_id_references_booking_rules: RuleConfig
	pickup_type_valid_gtfs_enum: RuleConfig
	start_pickup_drop_off_window_valid: RuleConfig
	stop_headsign_present: RuleConfig
	stop_times_continuous_drop_off_valid_gtfs_enum: RuleConfig
	stop_times_continuous_pickup_valid_gtfs_enum: RuleConfig
	stop_times_shape_dist_traveled_non_decreasing_on_trip: RuleConfig
	stop_times_stop_id_references_stops_table: RuleConfig
	stop_times_trip_id_references_trips_table: RuleConfig
	timepoint_valid_gtfs_enum: RuleConfig
}

export interface StopsRules {
	_file: RuleSeverity
	has_bench_valid_enum: RuleConfig
	has_network_map_valid_enum: RuleConfig
	has_pip_real_time_valid_enum: RuleConfig
	has_schedules_valid_enum: RuleConfig
	has_shelter_valid_enum: RuleConfig
	has_stop_sign_valid_enum: RuleConfig
	has_tariffs_information_valid_enum: RuleConfig
	level_id_valid_id: RuleConfig
	location_type_valid_enum: RuleConfig
	municipality_id_valid: RuleConfig
	parent_station_id_valid_for_stop_hierarchy: RuleConfig
	parish_id_valid: RuleConfig
	platform_code_valid: RuleConfig
	public_visible_valid_enum: RuleConfig
	region_id_valid: RuleConfig
	shelter_code_valid: RuleConfig
	shelter_maintainer_valid: RuleConfig
	stop_access: RuleConfig
	stop_code_valid: RuleConfig
	stop_desc_valid: RuleConfig
	stop_id_unique: RuleConfig
	stop_lat_valid_latitude_range: RuleConfig
	stop_lon_valid_longitude_range: RuleConfig
	stop_name_required_by_location_type: RuleConfig
	stop_short_name_valid: RuleConfig
	stop_timezone_valid: RuleConfig
	stop_url_valid_url: RuleConfig
	tts_stop_name_valid: RuleConfig
	wheelchair_boarding_valid_enum: RuleConfig
	zone_id_valid: RuleConfig
}

export interface TransfersRules {
	_file: RuleSeverity
	min_transfer_time_non_negative_seconds: RuleConfig
	transfer_from_route_id_references_routes_table: RuleConfig
	transfer_from_stop_id_references_stops_table: RuleConfig
	transfer_from_trip_id_references_trips_table: RuleConfig
	transfer_to_route_id_references_routes_table: RuleConfig
	transfer_to_stop_id_references_stops_table: RuleConfig
	transfer_to_trip_id_references_trips_table: RuleConfig
	transfer_type_valid_gtfs_enum: RuleConfig
}

export interface TripsRules {
	_file: RuleSeverity
	bikes_allowed_valid_gtfs_enum: RuleConfig
	block_id_in_allowed_set: RuleConfig
	direction_id_consistent_for_all_patterns_in_trips: RuleConfig
	direction_id_matches_feed_pattern_direction: RuleConfig
	direction_id_valid_enum: RuleConfig
	one_pattern_id_per_shape_id_group: RuleConfig
	one_shape_id_per_pattern_id_group: RuleConfig
	pattern_id_matches_feed_pattern_id_syntax: RuleConfig
	pattern_id_present_and_references_consistent: RuleConfig
	pattern_id_single_trip_signature_per_pattern: RuleConfig
	pattern_id_trip_has_required_fields_for_grouping: RuleConfig
	route_id_consistent_for_all_patterns_in_trips: RuleConfig
	route_id_references_routes_table: RuleConfig
	service_id_references_calendar_service: RuleConfig
	shape_id_needs_to_be_the_same_as_pattern_id: RuleConfig
	shape_id_references_shapes_table_when_present: RuleConfig
	stop_sequence_increasing_by_one_along_trip: RuleConfig
	trip_headsign_consistent_for_all_patterns_in_trips: RuleConfig
	trip_headsign_present_when_short_name_absent: RuleConfig
	trip_id_limit_max_length: RuleConfig
	trip_id_unique: RuleConfig
	trip_path_stop_coordinates_referenced_from_stops: RuleConfig
	trip_short_name_exclusivity: RuleConfig
	wheelchair_accessible_valid_gtfs_enum: RuleConfig
}

export interface VehiclesRules {
	_file: RuleSeverity
	available_seats_non_negative: RuleConfig
	available_standing_non_negative: RuleConfig
	bicycles_rack_count_non_negative: RuleConfig
	climatization_valid_enum: RuleConfig
	consumption_meter_valid_format: RuleConfig
	emission_code_valid_for_propulsion_type: RuleConfig
	external_sound_valid_enum: RuleConfig
	front_display_valid_enum: RuleConfig
	internal_sound_level_valid_enum: RuleConfig
	kneeling_valid_enum: RuleConfig
	license_plate_format_per_market_rules: RuleConfig
	lowered_floor_valid_enum: RuleConfig
	onboard_monitor_valid_enum: RuleConfig
	passenger_counting_valid_enum: RuleConfig
	propulsion_type_valid_enum: RuleConfig
	ramp_valid_enum: RuleConfig
	rear_display_valid_enum: RuleConfig
	registration_date_valid_day_granularity: RuleConfig
	side_display_valid_enum: RuleConfig
	static_information_valid_enum: RuleConfig
	typology_in_allowed_vehicle_types: RuleConfig
	vehicle_agency_id_references_agency_table: RuleConfig
	vehicle_id_unique: RuleConfig
	vehicle_make_required: RuleConfig
	vehicle_model_required: RuleConfig
	vehicle_owner_required: RuleConfig
	video_surveillance_valid_enum: RuleConfig
	wheelchair_spots_valid_enum: RuleConfig
}

/**
 * Rules after the Go validator filled every omitted setting.
 * Source: types.GtfsRules
 */
export interface ValidationRules {
	agency: AgencyRules
	calendar: CalendarRules
	calendar_dates: CalendarDatesRules
	fare_attributes: FareAttributesRules
	fare_media: FareMediaRules
	fare_rules: FareRulesRules
	feed_info: FeedInfoRules
	file_validation: FileValidationRules
	frequencies: FrequenciesRules
	levels: LevelsRules
	pathways: PathwaysRules
	rider_categories: RiderCategoriesRules
	routes: RoutesRules
	shapes: ShapesRules
	stop_times: StopTimesRules
	stops: StopsRules
	transfers: TransfersRules
	trips: TripsRules
	vehicles: VehiclesRules
}

/* * */
