/**
 * This file is auto-generated by the rules-catalogue command of the Go validator.
 * Do not edit this file manually. Run `npm run repo:validator-rules` to regenerate.
 *
 * Source: types.GtfsRules, types.RuleConfig and rules.Catalogue() in
 * modules/operation/apps/validator/validator/src
 *
 * Configuration types describe what the Go decoder produces. The *Input types
 * describe what it accepts: every key may be omitted (Go fills the default),
 * and null is allowed where Go ignores it or decodes it to nil. Severities,
 * sections and rule objects reject null, as rules.DecodeConfig does.
 * These are compile-time types only. They do not validate anything at runtime.
 */

import { type RuleSeverity } from './rules-severities.js';

/* * */

export interface RuleCompareInput {
	key?: null | string
	value?: null | string
}

export interface RuleConfigInput {
	compare?: null | RuleCompareInput[]
	depends_on?: null | string[]
	options?: null | string[]
	severity?: RuleSeverity
}

/* * */

export interface AgencyRulesInput {
	_file?: RuleSeverity
	agency_email_valid_address?: RuleConfigInput
	agency_fare_url_valid_url?: RuleConfigInput
	agency_id_matched_with_agency_name?: RuleConfigInput
	agency_id_unique?: RuleConfigInput
	agency_lang_valid_language_tag?: RuleConfigInput
	agency_name_present?: RuleConfigInput
	agency_phone_valid_phone_number?: RuleConfigInput
	agency_timezone_valid_id?: RuleConfigInput
	agency_url_valid_url?: RuleConfigInput
}

export interface AttributionsRulesInput {
	_file?: RuleSeverity
	agency_id?: RuleConfigInput
	attribution_email?: RuleConfigInput
	attribution_id?: RuleConfigInput
	attribution_phone?: RuleConfigInput
	attribution_url?: RuleConfigInput
	is_authority?: RuleConfigInput
	is_operator?: RuleConfigInput
	is_producer?: RuleConfigInput
	organization_name?: RuleConfigInput
	route_id?: RuleConfigInput
	trip_id?: RuleConfigInput
}

export interface CalendarRulesInput {
	_file?: RuleSeverity
	calendar_end_date_valid_yyyymmdd?: RuleConfigInput
	calendar_service_id_unique_non_empty?: RuleConfigInput
	calendar_start_date_valid_yyyymmdd?: RuleConfigInput
	friday?: RuleConfigInput
	monday?: RuleConfigInput
	saturday?: RuleConfigInput
	sunday?: RuleConfigInput
	thursday?: RuleConfigInput
	tuesday?: RuleConfigInput
	wednesday?: RuleConfigInput
}

export interface CalendarDatesRulesInput {
	_file?: RuleSeverity
	calendar_dates_service_id_references_calendar?: RuleConfigInput
	day_type?: RuleConfigInput
	exception_date_valid_yyyymmdd?: RuleConfigInput
	exception_type_add_or_remove_service?: RuleConfigInput
	holiday?: RuleConfigInput
	period?: RuleConfigInput
}

export interface FareAttributesRulesInput {
	_file?: RuleSeverity
	currency_type_valid?: RuleConfigInput
	fare_attributes_agency_id_references_agency_table?: RuleConfigInput
	fare_id_unique?: RuleConfigInput
	fare_price_valid_non_negative_decimal?: RuleConfigInput
	payment_method_valid_gtfs_enum?: RuleConfigInput
	transfer_duration_valid_seconds_range?: RuleConfigInput
	transfers_valid_gtfs_enum?: RuleConfigInput
}

export interface FareMediaRulesInput {
	_file?: RuleSeverity
	fare_media_id_unique?: RuleConfigInput
	fare_media_name_non_empty?: RuleConfigInput
	fare_media_type_valid?: RuleConfigInput
}

export interface FareRulesRulesInput {
	_file?: RuleSeverity
	fare_rule_contains_id_references_zones_stops?: RuleConfigInput
	fare_rule_destination_id_references_zones_stops?: RuleConfigInput
	fare_rule_fare_id_references_fare_attributes?: RuleConfigInput
	fare_rule_origin_id_references_zones_stops?: RuleConfigInput
	fare_rule_route_id_references_routes?: RuleConfigInput
}

export interface FeedInfoRulesInput {
	_file?: RuleSeverity
	default_lang_matches_feed_lang_when_present?: RuleConfigInput
	feed_contact_email_valid_address?: RuleConfigInput
	feed_contact_url_valid_http_url?: RuleConfigInput
	feed_end_date_valid_yyyymmdd_not_before_start?: RuleConfigInput
	feed_lang_valid_tag?: RuleConfigInput
	feed_publisher_name_non_empty?: RuleConfigInput
	feed_publisher_url_valid_http_url?: RuleConfigInput
	feed_remarks?: RuleConfigInput
	feed_start_date_valid_yyyymmdd?: RuleConfigInput
	feed_type?: RuleConfigInput
	feed_version_valid_identifier?: RuleConfigInput
}

export interface FileValidationRulesInput {
	_file?: RuleSeverity
	gtfs_feed_file_presence_and_integrity_rule?: RuleConfigInput
}

export interface FrequenciesRulesInput {
	_file?: RuleSeverity
	end_time?: RuleConfigInput
	exact_times?: RuleConfigInput
	headway_secs?: RuleConfigInput
	start_time?: RuleConfigInput
	trip_id?: RuleConfigInput
}

export interface LevelsRulesInput {
	_file?: RuleSeverity
	level_id_unique?: RuleConfigInput
	level_index_required?: RuleConfigInput
	level_name?: RuleConfigInput
}

export interface PathwaysRulesInput {
	_file?: RuleSeverity
	pathway_from_stop_id_references_stops_table?: RuleConfigInput
	pathway_id_unique?: RuleConfigInput
	pathway_is_bidirectional_valid_gtfs_enum?: RuleConfigInput
	pathway_length_non_negative?: RuleConfigInput
	pathway_max_slope_allowed_for_pathway_mode?: RuleConfigInput
	pathway_min_width_positive?: RuleConfigInput
	pathway_mode_valid_gtfs_enum?: RuleConfigInput
	pathway_reversed_signposted_as?: RuleConfigInput
	pathway_signposted_as?: RuleConfigInput
	pathway_stair_count?: RuleConfigInput
	pathway_to_stop_id_references_stops_table?: RuleConfigInput
	pathway_traversal_time_non_negative_seconds?: RuleConfigInput
}

export interface RiderCategoriesRulesInput {
	_file?: RuleSeverity
	at_most_one_default_fare_category?: RuleConfigInput
	eligibility_url_valid_http_url?: RuleConfigInput
	rider_category_id_unique?: RuleConfigInput
	rider_category_name_non_empty?: RuleConfigInput
}

export interface RoutesRulesInput {
	_file?: RuleSeverity
	circular?: RuleConfigInput
	continuous_drop_off_valid_gtfs_enum?: RuleConfigInput
	continuous_pickup_valid_gtfs_enum?: RuleConfigInput
	line_id_required?: RuleConfigInput
	line_long_name_present_when_line_id_present?: RuleConfigInput
	line_short_name_present_when_line_id_present?: RuleConfigInput
	network_id_references_networks_table?: RuleConfigInput
	path_type_valid_enum?: RuleConfigInput
	route_agency_id_references_agency_table?: RuleConfigInput
	route_color_valid_hex_string?: RuleConfigInput
	route_desc_per_severity_and_content_rules?: RuleConfigInput
	route_id_unique?: RuleConfigInput
	route_long_name_or_short_name_present?: RuleConfigInput
	route_remarks?: RuleConfigInput
	route_short_name_or_long_name_present?: RuleConfigInput
	route_sort_order_non_negative_integer?: RuleConfigInput
	route_text_color_valid_hex_contrast?: RuleConfigInput
	route_type_valid_gtfs_enum?: RuleConfigInput
	route_url_valid_http_url?: RuleConfigInput
	school?: RuleConfigInput
}

export interface ShapesRulesInput {
	_file?: RuleSeverity
	shape_block_distance_rows_aggregated?: RuleConfigInput
	shape_dist_traveled_delta_mismatches_haversine_block?: RuleConfigInput
	shape_dist_traveled_delta_mismatches_haversine_segment?: RuleConfigInput
	shape_dist_traveled_non_decreasing_with_sequence?: RuleConfigInput
	shape_dist_traveled_non_negative_monotonic?: RuleConfigInput
	shape_id_and_point_sequence_required?: RuleConfigInput
	shape_id_required?: RuleConfigInput
	shape_pt_lat_valid_latitude?: RuleConfigInput
	shape_pt_lon_valid_longitude?: RuleConfigInput
	shape_pt_sequence_not_repeated_within_shape?: RuleConfigInput
	shape_pt_sequence_strictly_increasing?: RuleConfigInput
	shape_sequence_position_mismatches_cumulative_traveled_distance?: RuleConfigInput
}

export interface StopTimesRulesInput {
	_file?: RuleSeverity
	arrival_departure_time_non_decreasing_by_stop_sequence?: RuleConfigInput
	arrival_time_ordering_with_departure_and_frequencies?: RuleConfigInput
	departure_time_ordering_with_arrival_and_timepoint?: RuleConfigInput
	drop_off_booking_rule_id_references_booking_rules_or_empty?: RuleConfigInput
	drop_off_type_valid_gtfs_enum?: RuleConfigInput
	end_pickup_drop_off_window_valid?: RuleConfigInput
	location_group_id_consistent_with_trip_id_and_stops?: RuleConfigInput
	pickup_booking_rule_id_references_booking_rules?: RuleConfigInput
	pickup_type_valid_gtfs_enum?: RuleConfigInput
	start_pickup_drop_off_window_valid?: RuleConfigInput
	stop_headsign_present?: RuleConfigInput
	stop_times_continuous_drop_off_valid_gtfs_enum?: RuleConfigInput
	stop_times_continuous_pickup_valid_gtfs_enum?: RuleConfigInput
	stop_times_shape_dist_traveled_non_decreasing_on_trip?: RuleConfigInput
	stop_times_stop_id_references_stops_table?: RuleConfigInput
	stop_times_trip_id_references_trips_table?: RuleConfigInput
	timepoint_valid_gtfs_enum?: RuleConfigInput
}

export interface StopsRulesInput {
	_file?: RuleSeverity
	has_bench_valid_enum?: RuleConfigInput
	has_network_map_valid_enum?: RuleConfigInput
	has_pip_real_time_valid_enum?: RuleConfigInput
	has_schedules_valid_enum?: RuleConfigInput
	has_shelter_valid_enum?: RuleConfigInput
	has_stop_sign_valid_enum?: RuleConfigInput
	has_tariffs_information_valid_enum?: RuleConfigInput
	level_id_valid_id?: RuleConfigInput
	location_type_valid_enum?: RuleConfigInput
	municipality_id_valid?: RuleConfigInput
	parent_station_id_valid_for_stop_hierarchy?: RuleConfigInput
	parish_id_valid?: RuleConfigInput
	platform_code_valid?: RuleConfigInput
	public_visible_valid_enum?: RuleConfigInput
	region_id_valid?: RuleConfigInput
	shelter_code_valid?: RuleConfigInput
	shelter_maintainer_valid?: RuleConfigInput
	stop_access?: RuleConfigInput
	stop_code_valid?: RuleConfigInput
	stop_desc_valid?: RuleConfigInput
	stop_id_unique?: RuleConfigInput
	stop_lat_valid_latitude_range?: RuleConfigInput
	stop_lon_valid_longitude_range?: RuleConfigInput
	stop_name_required_by_location_type?: RuleConfigInput
	stop_short_name_valid?: RuleConfigInput
	stop_timezone_valid?: RuleConfigInput
	stop_url_valid_url?: RuleConfigInput
	tts_stop_name_valid?: RuleConfigInput
	wheelchair_boarding_valid_enum?: RuleConfigInput
	zone_id_valid?: RuleConfigInput
}

export interface TransfersRulesInput {
	_file?: RuleSeverity
	min_transfer_time_non_negative_seconds?: RuleConfigInput
	transfer_from_route_id_references_routes_table?: RuleConfigInput
	transfer_from_stop_id_references_stops_table?: RuleConfigInput
	transfer_from_trip_id_references_trips_table?: RuleConfigInput
	transfer_to_route_id_references_routes_table?: RuleConfigInput
	transfer_to_stop_id_references_stops_table?: RuleConfigInput
	transfer_to_trip_id_references_trips_table?: RuleConfigInput
	transfer_type_valid_gtfs_enum?: RuleConfigInput
}

export interface TranslationsRulesInput {
	_file?: RuleSeverity
	field_name?: RuleConfigInput
	field_value?: RuleConfigInput
	language?: RuleConfigInput
	record_id?: RuleConfigInput
	record_sub_id?: RuleConfigInput
	table_name?: RuleConfigInput
	translation?: RuleConfigInput
}

export interface TripsRulesInput {
	_file?: RuleSeverity
	bikes_allowed_valid_gtfs_enum?: RuleConfigInput
	block_id_in_allowed_set?: RuleConfigInput
	direction_id_consistent_for_all_patterns_in_trips?: RuleConfigInput
	direction_id_matches_feed_pattern_direction?: RuleConfigInput
	direction_id_valid_enum?: RuleConfigInput
	one_pattern_id_per_shape_id_group?: RuleConfigInput
	one_shape_id_per_pattern_id_group?: RuleConfigInput
	pattern_id_matches_feed_pattern_id_syntax?: RuleConfigInput
	pattern_id_present_and_references_consistent?: RuleConfigInput
	pattern_id_single_trip_signature_per_pattern?: RuleConfigInput
	pattern_id_trip_has_required_fields_for_grouping?: RuleConfigInput
	route_id_consistent_for_all_patterns_in_trips?: RuleConfigInput
	route_id_references_routes_table?: RuleConfigInput
	service_id_references_calendar_service?: RuleConfigInput
	shape_id_needs_to_be_the_same_as_pattern_id?: RuleConfigInput
	shape_id_references_shapes_table_when_present?: RuleConfigInput
	stop_sequence_increasing_by_one_along_trip?: RuleConfigInput
	trip_headsign_consistent_for_all_patterns_in_trips?: RuleConfigInput
	trip_headsign_present_when_short_name_absent?: RuleConfigInput
	trip_id_limit_max_length?: RuleConfigInput
	trip_id_unique?: RuleConfigInput
	trip_path_stop_coordinates_referenced_from_stops?: RuleConfigInput
	trip_short_name_exclusivity?: RuleConfigInput
	wheelchair_accessible_valid_gtfs_enum?: RuleConfigInput
}

export interface VehiclesRulesInput {
	_file?: RuleSeverity
	available_seats_non_negative?: RuleConfigInput
	available_standing_non_negative?: RuleConfigInput
	bicycles_rack_count_non_negative?: RuleConfigInput
	climatization_valid_enum?: RuleConfigInput
	consumption_meter_valid_format?: RuleConfigInput
	emission_code_valid_for_propulsion_type?: RuleConfigInput
	external_sound_valid_enum?: RuleConfigInput
	front_display_valid_enum?: RuleConfigInput
	internal_sound_level_valid_enum?: RuleConfigInput
	kneeling_valid_enum?: RuleConfigInput
	license_plate_format_per_market_rules?: RuleConfigInput
	lowered_floor_valid_enum?: RuleConfigInput
	onboard_monitor_valid_enum?: RuleConfigInput
	passenger_counting_valid_enum?: RuleConfigInput
	propulsion_type_valid_enum?: RuleConfigInput
	ramp_valid_enum?: RuleConfigInput
	rear_display_valid_enum?: RuleConfigInput
	registration_date_valid_day_granularity?: RuleConfigInput
	side_display_valid_enum?: RuleConfigInput
	static_information_valid_enum?: RuleConfigInput
	typology_in_allowed_vehicle_types?: RuleConfigInput
	vehicle_agency_id_references_agency_table?: RuleConfigInput
	vehicle_id_unique?: RuleConfigInput
	vehicle_make_required?: RuleConfigInput
	vehicle_model_required?: RuleConfigInput
	vehicle_owner_required?: RuleConfigInput
	video_surveillance_valid_enum?: RuleConfigInput
	wheelchair_spots_valid_enum?: RuleConfigInput
}

/**
 * Rules as saved for an agency and accepted by the Go validator.
 */
export interface ValidationRulesInput {
	agency?: AgencyRulesInput
	attributions?: AttributionsRulesInput
	calendar?: CalendarRulesInput
	calendar_dates?: CalendarDatesRulesInput
	fare_attributes?: FareAttributesRulesInput
	fare_media?: FareMediaRulesInput
	fare_rules?: FareRulesRulesInput
	feed_info?: FeedInfoRulesInput
	file_validation?: FileValidationRulesInput
	frequencies?: FrequenciesRulesInput
	levels?: LevelsRulesInput
	pathways?: PathwaysRulesInput
	rider_categories?: RiderCategoriesRulesInput
	routes?: RoutesRulesInput
	shapes?: ShapesRulesInput
	stop_times?: StopTimesRulesInput
	stops?: StopsRulesInput
	transfers?: TransfersRulesInput
	translations?: TranslationsRulesInput
	trips?: TripsRulesInput
	vehicles?: VehiclesRulesInput
}

/* * */
