# # #

services:

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    command: >
      mongod
        --replSet rs0
        --bind_ip_all
        --port 27017
        --keyFile /data/replica.key
    deploy:
      resources:
        limits:
          memory: 10gb
    ulimits:
      nofile:
        soft: 64000
        hard: 64000
    volumes:
      - /opt/app/persistent-data/data:/data/db
      - /opt/app/persistent-data/logs:/var/log/mongodb
      - /opt/app/persistent-data/replica.key:/data/replica.key:ro
    env_file:
      - /opt/app/secrets/.env