/* * */

import { type ClickHouseTableSchema } from '@tmlmobilidade/go-clients-clickhouse';
import { type SimplifiedApexBankingTap, SimplifiedApexInspection, SimplifiedApexInspectionDecision, SimplifiedApexLocation, SimplifiedApexOnBoardRefund, SimplifiedApexOnBoardSale, SimplifiedApexValidation } from '@tmlmobilidade/go-types-apex';

/* * */

export const simplifiedApexBankingTapSchema: ClickHouseTableSchema<SimplifiedApexBankingTap> = {
	_id: { type: 'UUID' },
	agency_id: { type: 'LowCardinality(String)' },
	apex_version: { type: 'LowCardinality(String)' },
	banking_token: { type: 'String' },
	card_brand: { type: 'UInt8' },
	card_pan: { type: 'String' },
	created_at: { type: 'Int64' },
	device_id: { type: 'LowCardinality(String)' },
	event_type: { type: 'UInt8' },
	group_dimension: { type: 'Int32' },
	is_ok: { type: 'Bool' },
	is_ok_pcgi: { type: 'Bool' },
	line_id: { type: 'LowCardinality(String)' },
	mac_ase_counter_value: { type: 'UInt64' },
	mac_sam_serial_number: { type: 'UInt64' },
	operational_date: { type: 'UInt32' },
	pattern_id: { type: 'LowCardinality(String)' },
	product_id: { type: 'LowCardinality(String)' },
	received_at: { type: 'Int64' },
	stop_id: { type: 'LowCardinality(String)' },
	trip_id: { type: 'Nullable(String)' },
	updated_at: { type: 'Int64' },
	vehicle_id: { type: 'LowCardinality(Nullable(String))' },
};

export const simplifiedApexInspectionDecisionSchema: ClickHouseTableSchema<SimplifiedApexInspectionDecision> = {
	_id: { type: 'UUID' },
	agency_id: { type: 'LowCardinality(String)' },
	apex_version: { type: 'LowCardinality(String)' },
	created_at: { type: 'Int64' },
	device_id: { type: 'LowCardinality(String)' },
	final_control_status: { type: 'UInt8' },
	inspection_id: { type: 'Nullable(UUID)' },
	is_ok: { type: 'Bool' },
	is_ok_pcgi: { type: 'Bool' },
	mac_ase_counter_value: { type: 'UInt64' },
	mac_sam_serial_number: { type: 'UInt64' },
	operational_date: { type: 'UInt32' },
	received_at: { type: 'Int64' },
	updated_at: { type: 'Int64' },
};

export const simplifiedApexInspectionSchema: ClickHouseTableSchema<SimplifiedApexInspection> = {
	_id: { type: 'UUID' },
	agency_id: { type: 'LowCardinality(String)' },
	apex_version: { type: 'LowCardinality(String)' },
	card_serial_number: { type: 'Nullable(UInt64)' },
	control_destination_stop_id: { type: 'LowCardinality(Nullable(String))' },
	control_origin_stop_id: { type: 'LowCardinality(Nullable(String))' },
	control_status: { type: 'UInt8' },
	created_at: { type: 'Int64' },
	device_id: { type: 'LowCardinality(String)' },
	environment_status: { type: 'UInt8' },
	inspection_id: { type: 'Nullable(UUID)' },
	is_ok: { type: 'Bool' },
	is_ok_pcgi: { type: 'Bool' },
	line_id: { type: 'LowCardinality(Nullable(String))' },
	mac_ase_counter_value: { type: 'UInt64' },
	mac_sam_serial_number: { type: 'UInt64' },
	operational_date: { type: 'UInt32' },
	pattern_id: { type: 'LowCardinality(Nullable(String))' },
	product_id: { type: 'LowCardinality(Nullable(String))' },
	received_at: { type: 'Int64' },
	trip_id: { type: 'Nullable(String)' },
	updated_at: { type: 'Int64' },
	vehicle_id: { type: 'LowCardinality(Nullable(String))' },
};

export const simplifiedApexLocationSchema: ClickHouseTableSchema<SimplifiedApexLocation> = {
	_id: { type: 'UUID' },
	agency_id: { type: 'LowCardinality(String)' },
	apex_version: { type: 'LowCardinality(String)' },
	created_at: { type: 'Int64' },
	device_id: { type: 'LowCardinality(String)' },
	is_ok: { type: 'Bool' },
	is_ok_pcgi: { type: 'Bool' },
	line_id: { type: 'LowCardinality(Nullable(String))' },
	mac_ase_counter_value: { type: 'UInt64' },
	mac_sam_serial_number: { type: 'UInt64' },
	operational_date: { type: 'UInt32' },
	pattern_id: { type: 'LowCardinality(Nullable(String))' },
	received_at: { type: 'Int64' },
	stop_id: { type: 'LowCardinality(Nullable(String))' },
	trip_id: { type: 'Nullable(String)' },
	updated_at: { type: 'Int64' },
	vehicle_id: { type: 'LowCardinality(Nullable(String))' },
};

export const simplifiedApexOnBoardRefundSchema: ClickHouseTableSchema<SimplifiedApexOnBoardRefund> = {
	_id: { type: 'UUID' },
	agency_id: { type: 'LowCardinality(String)' },
	apex_version: { type: 'LowCardinality(String)' },
	card_physical_type: { type: 'UInt8' },
	card_serial_number: { type: 'Nullable(UInt64)' },
	created_at: { type: 'Int64' },
	device_id: { type: 'LowCardinality(String)' },
	is_ok: { type: 'Bool' },
	is_ok_pcgi: { type: 'Bool' },
	line_id: { type: 'LowCardinality(Nullable(String))' },
	mac_ase_counter_value: { type: 'UInt64' },
	mac_sam_serial_number: { type: 'UInt64' },
	on_board_sale_id: { type: 'Nullable(UUID)' },
	operational_date: { type: 'UInt32' },
	pattern_id: { type: 'LowCardinality(Nullable(String))' },
	payment_method: { type: 'UInt8' },
	price: { type: 'Int32' },
	product_id: { type: 'LowCardinality(Nullable(String))' },
	product_quantity: { type: 'Int32' },
	received_at: { type: 'Int64' },
	stop_id: { type: 'LowCardinality(Nullable(String))' },
	trip_id: { type: 'Nullable(String)' },
	updated_at: { type: 'Int64' },
	validation_id: { type: 'Nullable(UUID)' },
	vehicle_id: { type: 'LowCardinality(Nullable(String))' },
};

export const simplifiedApexOnBoardSaleSchema: ClickHouseTableSchema<SimplifiedApexOnBoardSale> = {
	_id: { type: 'UUID' },
	agency_id: { type: 'LowCardinality(String)' },
	apex_version: { type: 'LowCardinality(String)' },
	card_physical_type: { type: 'UInt8' },
	card_serial_number: { type: 'Nullable(UInt64)' },
	created_at: { type: 'Int64' },
	device_id: { type: 'LowCardinality(String)' },
	is_ok: { type: 'Bool' },
	is_ok_pcgi: { type: 'Bool' },
	is_passenger: { type: 'Bool' },
	line_id: { type: 'LowCardinality(Nullable(String))' },
	mac_ase_counter_value: { type: 'UInt64' },
	mac_sam_serial_number: { type: 'UInt64' },
	on_board_refund_id: { type: 'Nullable(UUID)' },
	operational_date: { type: 'UInt32' },
	pattern_id: { type: 'LowCardinality(Nullable(String))' },
	payment_method: { type: 'UInt8' },
	price: { type: 'Int32' },
	product_id: { type: 'LowCardinality(Nullable(String))' },
	product_quantity: { type: 'Int32' },
	received_at: { type: 'Int64' },
	stop_id: { type: 'LowCardinality(Nullable(String))' },
	trip_id: { type: 'Nullable(String)' },
	updated_at: { type: 'Int64' },
	validation_id: { type: 'Nullable(UUID)' },
	vehicle_id: { type: 'LowCardinality(Nullable(String))' },
};

export const simplifiedApexValidationSchema: ClickHouseTableSchema<SimplifiedApexValidation> = {
	_id: { type: 'UUID' },
	agency_id: { type: 'LowCardinality(String)' },
	apex_version: { type: 'LowCardinality(String)' },
	card_serial_number: { type: 'Nullable(UInt64)' },
	category: { type: 'LowCardinality(String)' },
	created_at: { type: 'Int64' },
	device_id: { type: 'LowCardinality(String)' },
	event_type: { type: 'UInt8' },
	is_ok: { type: 'Bool' },
	is_ok_pcgi: { type: 'Bool' },
	is_passenger: { type: 'Bool' },
	line_id: { type: 'LowCardinality(Nullable(String))' },
	mac_ase_counter_value: { type: 'UInt64' },
	mac_sam_serial_number: { type: 'UInt64' },
	on_board_refund_id: { type: 'Nullable(UUID)' },
	on_board_sale_id: { type: 'Nullable(UUID)' },
	operational_date: { type: 'UInt32' },
	pattern_id: { type: 'LowCardinality(Nullable(String))' },
	product_id: { type: 'LowCardinality(Nullable(String))' },
	received_at: { type: 'Int64' },
	stop_id: { type: 'LowCardinality(Nullable(String))' },
	trip_id: { type: 'Nullable(String)' },
	units_qty: { type: 'Nullable(Int32)' },
	updated_at: { type: 'Int64' },
	validation_status: { type: 'LowCardinality(String)' },
	vehicle_id: { type: 'LowCardinality(Nullable(String))' },
};
