# Massive thank you to @ricardojorgerm and @tiagogaspar8
# for the help in creating this nginx configuration file.



# # #
# USER

user nginx;



# # #
# WORKER PROCESSES

worker_processes auto;



# # #
# DEFAULTS

error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;



# # #
# EVENTS

events {
	 use epoll;
	 worker_connections 8192;
	 multi_accept on;
}



# # #
# HTTP

http {


	# # #
	# MIME TYPES

	include /etc/nginx/mime.types;
	default_type application/octet-stream;


	# # #
	# LOGS

	log_format main '$time_iso8601 | $status | IP $remote_addr | Request: "$request" | Referer: "$http_referer" | User Agent: "$http_user_agent"';

	access_log /var/log/nginx/access.log main buffer=32k flush=3s;


	# # #
	# FILE DESCRIPTOR SETTINGS

	aio threads;
	directio 512M;
	output_buffers 2 1M;
	sendfile on;
	tcp_nopush on;

	keepalive_timeout 65;


	# # #
	# RATE LIMITS

	limit_req_zone global zone=global:10m rate=500r/s;
	limit_req zone=global burst=200 delay=2;

	limit_req_zone $binary_remote_addr zone=ip:10m rate=50r/s;
	limit_req zone=ip burst=50 delay=2;

	limit_req_status 429;


	# # #
	# COMPRESSION

	gzip on;
	gzip_types application/json;


	# # #
	# UPSTREAM

	# Alerts

	upstream alerts_upstream {
		least_conn;
		zone alerts_upstream 64K;
		server 0.0.0.0 max_fails=30 fail_timeout=60s;
		keepalive 10;
	}

	# Auth

	upstream auth_upstream {
		least_conn;
		zone auth_upstream 64K;
		server 10.81.100.83 max_fails=30 fail_timeout=60s;
		keepalive 10;
	}

	# Controller

	upstream controller_upstream {
		least_conn;
		zone controller_upstream 64K;
		server 0.0.0.0 max_fails=30 fail_timeout=60s;
		keepalive 10;
	}

	# Locations

	upstream locations_upstream {
		least_conn;
		zone locations_upstream 64K;
		server 0.0.0.0 max_fails=30 fail_timeout=60s;
		keepalive 10;
	}

	# Performance

	upstream performance_upstream {
		least_conn;
		zone performance_upstream 64K;
		server 0.0.0.0 max_fails=30 fail_timeout=60s;
		keepalive 10;
	}

	# Plans

	upstream plans_upstream {
		least_conn;
		zone plans_upstream 64K;
		server 0.0.0.0 max_fails=30 fail_timeout=60s;
		keepalive 10;
	}

	# Stops

	upstream stops_upstream {
		least_conn;
		zone stops_upstream 64K;
		server 0.0.0.0 max_fails=30 fail_timeout=60s;
		keepalive 10;
	}


	# # #
	# HTTP SERVER
	# Redirect to HTTPS

	server {

		listen 80;
		listen [::]:80;
		server_name ${NGINX_SERVER_NAME};
		server_tokens off;

		location /.well-known/acme-challenge/ {
			root /var/www/certbot;
		}

		location / {
			return 301 https://$host$request_uri;
		}

	}


	# # #
	# HTTPS SERVER

	server {

		listen 443 ssl;
		listen [::]:443 ssl;
		server_name ${NGINX_SERVER_NAME};
		server_tokens off;
		http2 on;

		# Lets Encrypt Certificates
		ssl_certificate /etc/letsencrypt/live/${NGINX_SERVER_NAME}/fullchain.pem;
		ssl_certificate_key /etc/letsencrypt/live/${NGINX_SERVER_NAME}/privkey.pem;
		include /etc/letsencrypt/options-ssl-nginx.conf;
		ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
		ssl_early_data on;

		# Proxy configuration
		proxy_http_version 1.1;
		proxy_connect_timeout 10s;
		proxy_send_timeout 20s;
		proxy_read_timeout 20s;
		proxy_set_header Connection "";
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_next_upstream error timeout http_500;


		# Alerts

		location /alerts {
			proxy_pass http://alerts_upstream;
		}

		# Auth

		location /auth/ {
			proxy_pass http://auth_upstream/;
		}

		# Controller

		location /controller {
			proxy_pass http://controller_upstream;
		}

		# Locations

		location /locations {
			proxy_pass http://locations_upstream;
		}

		# Performance

		location /performance {
			proxy_pass http://performance_upstream;
		}

		# Plans

		location /plans {
			proxy_pass http://plans_upstream;
		}

		# Stops

		location /stops {
			proxy_pass http://stops_upstream;
		}

		# Root

		location / {
			return 302 /auth;
		}

		# Enable for basic statistics
		# location = /basic_status {
		# 	 stub_status;
		# }

	}

}