# # #
# UPSTREAMS

# Alerts

upstream alerts_upstream {
	least_conn;
	zone alerts_upstream 64K;
	server 10.81.100.93 max_fails=999 fail_timeout=30s;
	keepalive 10;
}

# Auth

upstream auth_upstream {
	least_conn;
	zone auth_upstream 64K;
	server 10.81.100.26 max_fails=999 fail_timeout=30s;
	keepalive 10;
}

# Controller

upstream controller_upstream {
	least_conn;
	zone controller_upstream 64K;
	server 10.81.100.54 max_fails=999 fail_timeout=30s;
	keepalive 10;
}

# Dates

upstream dates_upstream {
	least_conn;
	zone dates_upstream 64K;
	server 10.81.100.43 max_fails=999 fail_timeout=30s;
	keepalive 10;
}

# Exporter

upstream exporter_upstream {
	least_conn;
	zone exporter_upstream 64K;
	server 10.81.100.17 max_fails=999 fail_timeout=30s;
	keepalive 10;
}

# Locations

upstream locations_upstream {
	least_conn;
	zone locations_upstream 64K;
	server 10.81.100.90 max_fails=999 fail_timeout=30s;
	keepalive 10;
}

# Offer

upstream offer_upstream {
	least_conn;
	zone offer_upstream 64K;
	server 10.81.100.114 max_fails=999 fail_timeout=30s;
	keepalive 10;
}

# Performance

upstream performance_upstream {
	least_conn;
	zone performance_upstream 64K;
	server 10.81.100.85 max_fails=999 fail_timeout=30s;
	keepalive 10;
}

# Plans

upstream plans_upstream {
	least_conn;
	zone plans_upstream 64K;
	server 10.81.100.6 max_fails=999 fail_timeout=30s;
	keepalive 10;
}

# Stops

upstream stops_upstream {
	least_conn;
	zone stops_upstream 64K;
	server 10.81.100.86 max_fails=999 fail_timeout=30s;
	keepalive 10;
}