# # #
# UPSTREAMS

# Alerts

upstream alerts_upstream {
	least_conn;
	zone alerts_upstream 64K;
	server 10.81.100.38 max_fails=999 fail_timeout=30s;
	keepalive 10;
}

# Auth

upstream auth_upstream {
	least_conn;
	zone auth_upstream 64K;
	server 10.81.100.83 max_fails=999 fail_timeout=30s;
	keepalive 10;
}

# Controller

upstream controller_upstream {
	least_conn;
	zone controller_upstream 64K;
	server 10.81.100.92 max_fails=999 fail_timeout=30s;
	keepalive 10;
}

# Dates

upstream dates_upstream {
	least_conn;
	zone dates_upstream 64K;
	server 10.81.100.57 max_fails=999 fail_timeout=30s;
	keepalive 10;
}

# Exporter

upstream exporter_upstream {
	least_conn;
	zone exporter_upstream 64K;
	server 10.81.100.58 max_fails=999 fail_timeout=30s;
	keepalive 10;
}

# Locations

upstream locations_upstream {
	least_conn;
	zone locations_upstream 64K;
	server 10.81.100.45 max_fails=999 fail_timeout=30s;
	keepalive 10;
}

# Offer

upstream offer_upstream {
	least_conn;
	zone offer_upstream 64K;
	server 10.81.100.23 max_fails=999 fail_timeout=30s;
	keepalive 10;
}

# Performance

upstream performance_upstream {
	least_conn;
	zone performance_upstream 64K;
	server 10.81.100.113 max_fails=999 fail_timeout=30s;
	keepalive 10;
}

# Plans

upstream plans_upstream {
	least_conn;
	zone plans_upstream 64K;
	server 10.81.100.14 max_fails=999 fail_timeout=30s;
	keepalive 10;
}

# Stops

upstream stops_upstream {
	least_conn;
	zone stops_upstream 64K;
	server 10.81.100.35 max_fails=999 fail_timeout=30s;
	keepalive 10;
}