# # #
# Fill in all values before applying.
# Apply with: kubectl apply -f manifests/performance/secret.yaml
# WARNING: Do not commit this file with real values.

apiVersion: v1
kind: Secret
metadata:
  name: performance-secret
  namespace: go-performance
type: Opaque
stringData:
  ENVIRONMENT: "k8s"

  ## DATABASE
  DATABASE_URI: ""
