# # #

name: tmlmobilidade-go-exports-production

services:

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  wud:
    image: getwud/wud
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 100mb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WUD_TRIGGER_DOCKER_DEFAULT_PRUNE=true
      - WUD_WATCHER_LOCAL_WATCHALL=true
      - WUD_WATCHER_LOCAL_CRON=* * * * *

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  nginx:
    image: ghcr.io/tmlmobilidade/go-exports-nginx:production
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 1gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    ports:
      - 80:80
      - 443:443

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  api:
    image: ghcr.io/tmlmobilidade/go-exports-api:production
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 2gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./secrets:/secrets
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  cleaner:
    image: ghcr.io/tmlmobilidade/go-exports-cleaner:production
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 2gb
    volumes:
      - ./secrets:/secrets
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  export-drt:
    image: ghcr.io/tmlmobilidade/go-exports-export-drt:production
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 2gb
    volumes:
      - ./secrets:/secrets
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  export-files:
    image: ghcr.io/tmlmobilidade/go-exports-export-files:production
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 2gb
    volumes:
      - ./secrets:/secrets
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  export-gtfs-merged:
    image: ghcr.io/tmlmobilidade/go-exports-export-gtfs-merged:production
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 2gb
    volumes:
      - ./secrets:/secrets
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  export-posters:
    image: ghcr.io/tmlmobilidade/go-exports-export-posters:production
    deploy:
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          memory: 2gb
    volumes:
      - ./secrets:/secrets
    env_file:
      - ./secrets/.env