name: vehicle-events

# secrets:
#   backupd_config:
#     file: ./backupd.yaml

services:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  watchtower:
    image: nickfedor/watchtower
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
      resources:
        limits:
          memory: 1gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_CLEANUP=TRUE
      - WATCHTOWER_INCLUDE_STOPPED=TRUE
      - WATCHTOWER_REVIVE_STOPPED=TRUE
      - WATCHTOWER_ROLLING_RESTART=TRUE

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  vehicle-events-db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./vehicle-events-entrypoint.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./vehicle-events-keyfile.key:/data/replica.key
      - ./vehicle-events-db-data:/data/db
    env_file:
      - .env
    entrypoint:
      - bash
      - -c
      - |
          chmod 400 /data/replica.key
          chown 999:999 /data/replica.key
          exec docker-entrypoint.sh $$@
    command: mongod --bind_ip_all --auth --replSet rs0 --keyFile /data/replica.key --port 27017

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  # backupd:
  #   image: ghcr.io/tmlmobilidade/backupd:production
  #   secrets:
  #     - backupd_config
