apiVersion: v1
kind: Service
metadata:
  name: auth-frontend
  namespace: go-auth
  labels:
    app: auth-frontend
    app.kubernetes.io/name: auth-frontend
    app.kubernetes.io/part-of: go-auth
spec:
  type: ClusterIP
  selector:
    app: auth-frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
