apiVersion: v1
kind: Namespace
metadata:
  name: go-auth

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: go-auth
  labels:
    app: auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: api
          image: ghcr.io/tmlmobilidade/go-auth-api:production
          imagePullPolicy: Always
          ports:
            - containerPort: 5050
          envFrom:
            - secretRef:
                name: environment-secret
            - secretRef:
                name: database-secret
            - secretRef:
                name: email-secret
            # - secretRef:
            #     name: storage-secret
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi