# # #

name: tmlmobilidade-sae-locations

volumes:
  certbotdata:

services:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  watchtower:
    image: containrrr/watchtower
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
      resources:
        limits:
          memory: 100mb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=10
      - WATCHTOWER_CLEANUP=TRUE
      - WATCHTOWER_INCLUDE_STOPPED=TRUE
      - WATCHTOWER_REVIVE_STOPPED=TRUE
      - WATCHTOWER_ROLLING_RESTART=TRUE

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  nginx:
    image: ghcr.io/tmlmobilidade/sae-locations-nginx:production
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
      resources:
        limits:
          memory: 2gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./letsencrypt:/etc/letsencrypt:ro
      - certbotdata:/var/www/certbot:ro
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    mem_limit: 2g
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - certbotdata:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  locations-db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./locations-entrypoint.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./secrets/locations-keyfile.key:/data/replica.key
      - ./locations-db-data:/data/db
      - ./locations.dump:/dump/db.dump
    env_file:
      - ./secrets/.env
    entrypoint:
      - bash
      - -c
      - |
          chmod 400 /data/replica.key
          chown 999:999 /data/replica.key
          exec docker-entrypoint.sh $$@
    command: mongod --bind_ip_all --auth --replSet rs0 --keyFile /data/replica.key --port 27017

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  api:
    image: ghcr.io/tmlmobilidade/sae-locations-api:production
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
      resources:
        limits:
          memory: 4gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./secrets:/secrets
    env_file:
      - ./secrets/.env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  frontend:
    image: ghcr.io/tmlmobilidade/sae-locations-frontend:production
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
      resources:
        limits:
          memory: 2gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - ./secrets/.env