# # #

name: tmlmobilidade-stops-dev

services:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  stopsdb:
    image: mongo
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    ports:
      - 37002:27017
    volumes:
      - ./stops.dump:/dump/db.dump
      - ./local-setup.sh:/docker-entrypoint-initdb.d/setup.sh
    environment:
      - MONGO_INITDB_DATABASE=production
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
