-- ============================================================================
-- Trip Summary
-- ============================================================================
-- Pre-compute trip-level information:
--   • first_arrival_time = arrival time of the first stop in the trip
--   • last_stop_name     = name of the last stop in the trip (headsign)
-- ============================================================================
WITH trip_summary AS (
    SELECT
        hashed_trip_id,

        -- Scheduled arrival time of the first stop
        argMin(arrival_time, stop_sequence) AS first_arrival_time,

        -- Name of the last stop
        argMax(stop_name, stop_sequence) AS last_stop_name

    FROM eta.curr_waypoints_snapped

    GROUP BY hashed_trip_id
)

SELECT

    -- If a ride instance exists, prefix the trip_id with the ride identifier.
    -- Example:
    --   trip_id = 12345
    --   ride._id = abc-987654
    -- Result:
    --   [987654]12345
    if(
        empty(r._id),
        e.trip_id,
        concat('[', splitByChar('-', r._id)[1], ']', e.trip_id)
    ) AS trip_id,

    -- Vehicle assigned to the trip
    e.vehicle_id AS vehicle_id,

    -- Stop identifier
    e.stop_id AS stop_id,

    -- Stop position within the trip
    e.stop_sequence AS stop_sequence,

    -- Pattern identifier extracted from the trip_id structure.
    -- Example:
    --   4701_470100_0_123|...
    -- Result:
    --   4701_470100_0
    arrayStringConcat(
        arraySlice(
            splitByChar('_', splitByChar('|', substringIndex(e.trip_id, ']', -1))[1]),
            1, 3
        ),
        '_'
    ) AS pattern_id,

    -- Line identifier (first segment of the pattern)
    splitByChar(
        '_',
        splitByChar('|', substringIndex(e.trip_id, ']', -1))[1]
    )[1] AS line_id,

    -- Route identifier (first two segments of the pattern)
    arrayStringConcat(
        arraySlice(
            splitByChar('_', splitByChar('|', substringIndex(e.trip_id, ']', -1))[1]),
            1, 2
        ),
        '_'
    ) AS route_id,

    -- Trip destination (last stop name)
    ts.last_stop_name AS headsign,

    -- Scheduled arrival time from GTFS (HH:MM:SS)
    w.arrival_time AS scheduled_arrival,

    -- Scheduled arrival converted to Unix timestamp.
    --
    -- Calculation:
    --   scheduled_trip_start
    --   + (current_stop_arrival - first_stop_arrival)
    --
    -- This produces an absolute timestamp for the stop arrival.
    if(
        length(w.arrival_time) = 0 OR length(ts.first_arrival_time) = 0,
        NULL,
        toNullable(
            toInt64(intDiv(r.start_time_scheduled, 1000))
            + (
                toInt64(splitByChar(':', w.arrival_time)[1]) * 3600
                + toInt64(splitByChar(':', w.arrival_time)[2]) * 60
                + toInt64(splitByChar(':', w.arrival_time)[3])
                - toInt64(splitByChar(':', ts.first_arrival_time)[1]) * 3600
                - toInt64(splitByChar(':', ts.first_arrival_time)[2]) * 60
                - toInt64(splitByChar(':', ts.first_arrival_time)[3])
            )
        )
    ) AS scheduled_arrival_unix,

    -- Actual arrival time.
    --
    -- A stop is considered reached when the vehicle has passed or reached
    -- the node associated with that stop.
    if(
        e.current_node_index >= e.stop_node_index,
        formatDateTime(
            fromUnixTimestamp64Milli(e.position_created_at),
            '%H:%i:%S',
            'Europe/Lisbon'
        ),
        NULL
    ) AS observed_arrival,

    -- Actual arrival converted to Unix timestamp
    if(
        e.current_node_index >= e.stop_node_index,
        toNullable(toInt64(intDiv(e.position_created_at, 1000))),
        NULL
    ) AS observed_arrival_unix,

    -- Predicted arrival time generated by the ETA engine
    if(
        e.eta_at IS NULL,
        NULL,
        formatDateTime(
            assumeNotNull(e.eta_at),
            '%H:%i:%S',
            'Europe/Lisbon'
        )
    ) AS estimated_arrival,

    -- Predicted arrival converted to Unix timestamp
    if(
        e.eta_at IS NULL,
        NULL,
        toNullable(
            toInt64(
                toUnixTimestamp(
                    assumeNotNull(e.eta_at)
                )
            )
        )
    ) AS estimated_arrival_unix

-- ETA predictions per trip stop
FROM eta.pred_trip_stop_etas AS e

-- Join scheduled stop information from GTFS
LEFT JOIN eta.curr_waypoints_snapped AS w
    ON w.hashed_trip_id = e.hashed_trip_id
    AND w.stop_sequence = e.stop_sequence

-- Join ride instance information
LEFT JOIN eta.curr_rides AS r
    ON r.trip_id = e.trip_id

-- Join trip-level summary information
LEFT JOIN trip_summary AS ts
    ON ts.hashed_trip_id = e.hashed_trip_id

-- Sort output deterministically
ORDER BY
    e.trip_id,
    e.vehicle_id,
    e.stop_sequence

-- Deduplicate records and keep a single row per trip-stop pair
LIMIT 1 BY trip_id, stop_id