# # #

name: tmlmobilidade-plans-dev

services:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  filesdb:
    image: mongo
    deploy:
      restart_policy:
        condition: any
        delay: 30s
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    ports:
      - 37001:27017
    # volumes:
    #   - ./files.dump:/dump/db.dump
    #   - ./local-setup.sh:/docker-entrypoint-initdb.d/setup.sh
    environment:
      - MONGO_INITDB_DATABASE=production
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  plansdb:
    image: mongo
    deploy:
      restart_policy:
        condition: any
        delay: 30s
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    ports:
      - 37004:27017
    volumes:
      - ./plans.dump:/dump/db.dump
      - ./local-setup.sh:/docker-entrypoint-initdb.d/setup.sh
    environment:
      - MONGO_INITDB_DATABASE=production
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root