apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-rides-locker
  namespace: go-controller
  labels:
    app: controller-rides-locker
    app.kubernetes.io/name: controller-rides-locker
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: go-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller-rides-locker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: controller-rides-locker
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: rides-locker
          image: ghcr.io/tmlmobilidade/go-controller-rides-locker:staging
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: controller-secret
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
