apiVersion: v1
kind: Service
metadata:
  name: controller-nginx
  namespace: go-controller
  labels:
    app: controller-nginx
    app.kubernetes.io/name: controller-nginx
    app.kubernetes.io/part-of: go-controller
spec:
  type: NodePort
  selector:
    app: controller-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30092
      protocol: TCP
