apiVersion: v1
kind: Service
metadata:
  name: coordinator
  namespace: go-controller
  labels:
    app: controller-coordinator
    app.kubernetes.io/name: controller-coordinator
    app.kubernetes.io/part-of: go-controller
spec:
  type: ClusterIP
  selector:
    app: controller-coordinator
  ports:
    - name: http
      port: 5050
      targetPort: http
      protocol: TCP
