/* * */

export const PublicFeedbackLineReasonValues = [
	'early',
	'late',
	'detour',
	'long_headway',
	'too_crowded',
	'cancelled_departure',
	'long_queue',
	'interrupted',
	'inaccurate_realtime',
	'wrong_panel_information',
	'did_not_pass',
	'route_changed_without_notice',
	'skipped_stop',
	'damaged',
	'dirty',
	'missing_safety_equipment',
	'door_issue',
	'climate_control_issue',
	'validator_issue',
	'accessibility_issue',
	'lighting_issue',
	'lack_of_passenger_support',
	'rude_staff',
	'driver_bad_conduct',
	'disorganized_boarding',
	'inadequate_service',
	'unsafe_speed',
	'traffic_law_violation',
] as const satisfies readonly string[];
