# # #
# Fill in all values before applying.
# Apply with: kubectl apply -f manifests/dates/secret.yaml
# WARNING: Do not commit this file with real values.

apiVersion: v1
kind: Secret
metadata:
  name: dates-secret
  namespace: go-dates
type: Opaque
stringData:
  ENVIRONMENT: "staging"

  ## DATABASE
  DATABASE_URI: ""
