/* * */

export const PublicFeedbackStopReasonValues = [
	'no_bench',
	'no_shelter',
	'lighting_issue',
	'missing_line_information',
	'dirty',
	'wrong_panel_information',
	'ticket_machine_issue',
	'disorganized_boarding',
	'accessibility_issue',
	'validator_issue',
	'confusing_signage',
	'audio_announcement_issue',
	'display_issue',
	'damaged_bench',
	'shelter_issue',
	'safety_incident',
	'elevator_escalator_issue',
	'sidewalk_issue',
	'no_trash_bin',
	'weather_exposure_issue',
	'other',
] as const satisfies readonly string[];
