apiVersion: apps/v1
kind: Deployment
metadata:
  name: plans-cleaner
  namespace: go-plans
  labels:
    app: plans-cleaner
    app.kubernetes.io/name: plans-cleaner
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: go-plans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plans-cleaner
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: plans-cleaner
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: cleaner
          image: ghcr.io/tmlmobilidade/go-plans-cleaner:staging
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: plans-secret
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
