# # #
# Fill in all values before applying.
# Apply with: kubectl apply -f manifests/plans/secret.yaml
# WARNING: Do not commit this file with real values.

apiVersion: v1
kind: Secret
metadata:
  name: plans-secret
  namespace: go-plans
type: Opaque
stringData:
  ENVIRONMENT: "staging"

  ## DATABASE
  DATABASE_URI: ""

  ## EMAIL
  TML_PROVIDER_EMAIL_SERVER_HOST: ""
  TML_PROVIDER_EMAIL_SERVER_PORT: ""
  TML_PROVIDER_EMAIL_SERVER_USER: ""
  TML_PROVIDER_EMAIL_SERVER_PASSWORD: ""
  TML_PROVIDER_EMAIL_FROM: ""

  ## FILES
  OCI_USER: ""
  OCI_FINGERPRINT: ""
  OCI_TENANCY: ""
  OCI_REGION: ""
  OCI_PRIVATE_KEY: ""
  OCI_NAMESPACE: ""
  OCI_BUCKET_NAME: ""
  STORAGE_TYPE: ""
