CREATE OR REPLACE TABLE performance.itrp_by_pattern (
    agency_id String,
    pattern_id String,
    line_id String,
    route_id String,
    subtipo String,
    designacao String,
    sentido String,
    tipo_transporte String,
    origem_municipio String,
    origem_dtcc String,
    destino_municipio String,
    destino_dtcc String,
    classificacao String,
    extension_scheduled Float64,
    extension_observed Float64,
    circulations_scheduled UInt64,
    circulations_observed UInt64,
    veiculos_km_previsto Float64,
    veiculos_km_produzido Float64,
    passengers UInt64,
    carreiras_servicos_1 UInt64,
    veiculos_km_1 Float64,
    passageiros_1 UInt64,
    carreiras_servicos_2 UInt64,
    veiculos_km_2 Float64,
    passageiros_2 UInt64,
    carreiras_servicos_3 UInt64,
    veiculos_km_3 Float64,
    passageiros_3 UInt64,
    carreiras_servicos_PPM UInt64,
    veiculos_km_PPM Float64,
    passageiros_PPM UInt64,
    carreiras_servicos_PPT UInt64,
    veiculos_km_PPT Float64,
    passageiros_PPT UInt64,
    carreiras_servicos_CD UInt64,
    veiculos_km_CD Float64,
    passageiros_CD UInt64,
    carreiras_servicos_N UInt64,
    veiculos_km_N Float64,
    passageiros_N UInt64
)
ENGINE = ReplacingMergeTree()
ORDER BY (agency_id, pattern_id, line_id);
