#cloud-config

write_files:

  # # #
  # CONSUL

  - path: /etc/consul.d/consul.hcl
    permissions: "0640"
    content: |
      ${indent(6, consul_config)}

  - path: /etc/systemd/system/consul.service
    permissions: "0644"
    content: |
      ${indent(6, consul_service)}

  # # #
  # NOMAD

  - path: /etc/nomad.d/nomad.hcl
    permissions: "0640"
    content: |
      ${indent(6, nomad_config)}

  - path: /etc/systemd/system/nomad.service
    permissions: "0644"
    content: |
      ${indent(6, nomad_service)}

runcmd:
  - systemctl daemon-reload
  - systemctl enable consul vault nomad
  - systemctl start consul
  - systemctl start vault
  - systemctl start nomad