# # #

name: 'Controller - CLI | Build & Test'

# # #

on:

  push:
    paths:
      - 'controller/cli/**'
    branches:
      - production
      - staging
# # #

jobs:

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  legacy-offer:
    name: legacy-offer (NodeJS)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Setup NodeJS
        uses: actions/setup-node@main
        with:
          node-version: 'latest'
          registry-url: 'https://registry.npmjs.org'

      - name: Install NPM dependencies
        run: npm install
        working-directory: .

      - name: Bump package version
        run: npx @helperkits/bumper package.json
        working-directory: .

      - name: Build package
        run: npm run build
        working-directory: .

      - name: Publish package to NPM
        run: npm publish --access public
        working-directory: .
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}