name: 'Performance Explorer | Build & Push'

on:
  workflow_dispatch:
  push:
    branches:
      - production
      - staging
      - 'staging/**'
    paths:
      - 'modules/performance/**'
      - '!modules/performance/environments/**'
      - 'packages/**'
      - '.github/workflows/build-performance.yml'

# # #

jobs:

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  frontend:
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      file: ./modules/performance/apps/frontend/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-performance-frontend:${{ github.ref_name }}
      environment: ${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # #

  api:
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      file: ./modules/performance/apps/api/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-performance-api:${{ github.ref_name }}
      environment: ${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # #

  nginx:
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      file: ./modules/performance/apps/nginx/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-performance-nginx:${{ github.ref_name }}
      environment: ${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  sync-metrics:
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      file: ./modules/performance/apps/sync-metrics/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-performance-sync-metrics:${{ github.ref_name }}
      environment: ${{ github.ref_name }}