# # #

name: 'Replicator | Build & Test'

# # #

on:
  workflow_dispatch:
  push:
    branches:
    #   - production
      - staging
    paths:
      - 'modules/replicator/**'
      - 'packages/**'
      - '.github/workflows/build-replicator.yml'

# # #

jobs:

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  enrich:
    name: enrich (NodeJS)
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      file: ./modules/replicator/apps/enrich/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-replicator-enrich:${{ github.ref_name }}
      environment: ${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  stream:
    name: stream (NodeJS)
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      file: ./modules/replicator/apps/stream/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-replicator-stream:${{ github.ref_name }}
      environment: ${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  sync-apex-locations:
    name: sync-apex-locations (NodeJS)
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      file: ./modules/replicator/apps/sync-apex-locations/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-replicator-sync-apex-locations:${{ github.ref_name }}
      environment: ${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  sync-apex-on-board-refunds:
    name: sync-apex-on-board-refunds (NodeJS)
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      file: ./modules/replicator/apps/sync-apex-on-board-refunds/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-replicator-sync-apex-on-board-refunds:${{ github.ref_name }}
      environment: ${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  sync-apex-on-board-sales:
    name: sync-apex-on-board-sales (NodeJS)
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      file: ./modules/replicator/apps/sync-apex-on-board-sales/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-replicator-sync-apex-on-board-sales:${{ github.ref_name }}
      environment: ${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  sync-apex-validations:
    name: sync-apex-validations (NodeJS)
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      file: ./modules/replicator/apps/sync-apex-validations/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-replicator-sync-apex-validations:${{ github.ref_name }}
      environment: ${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  sync-vehicle-events:
    name: sync-vehicle-events (NodeJS)
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      file: ./modules/replicator/apps/sync-vehicle-events/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-replicator-sync-vehicle-events:${{ github.ref_name }}
      environment: ${{ github.ref_name }}
