name: 'Plans | Build & Push'

on:
  workflow_dispatch:
  push:
    branches:
      - production
      - staging
      - 'staging/**'
    paths:
      - '!modules/plans/environments/**'
      - 'modules/plans/**'
      - 'packages/**'
      - '.github/workflows/build-plans.yml'

# # #

jobs:

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  frontend:
    name: frontend (NextJS)
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      file: ./modules/plans/apps/frontend/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-plans-frontend:${{ github.ref_name }}
      environment: ${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  api:
    name: api (NodeJS)
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      file: ./modules/plans/apps/api/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-plans-api:${{ github.ref_name }}
      environment: ${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  validator:
    name: validator (NodeJS)
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      file: ./modules/plans/apps/validator/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-plans-validator:${{ github.ref_name }}
      environment: ${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  cleaner:
    name: cleaner (NodeJS)
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      file: ./modules/plans/apps/cleaner/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-plans-cleaner:${{ github.ref_name }}
      environment: ${{ github.ref_name }}


  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #
  
  nginx:
    name: nginx (NodeJS)
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      file: ./modules/plans/apps/nginx/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-plans-nginx:${{ github.ref_name }}
      environment: ${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  export-drt:
    name: export-drt (NodeJS)
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      file: ./modules/plans/apps/export-drt/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-plans-export-drt:${{ github.ref_name }}
      environment: ${{ github.ref_name }}