name: 'Alerts | Build & Push'

on:
  workflow_dispatch:
  push:
    branches:
      - production
      - staging
    paths:
      - '!modules/alerts/environments/**'
      - 'modules/alerts/**'
      - 'packages/**'
      - '.github/workflows/build-alerts.yml'

# # #

jobs:

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  check-changes:
    uses: ./.github/workflows/_check-app-changes.yml
    with:
      paths: |
        modules/alerts/apps/frontend/**
        modules/alerts/apps/api/**
        packages/**

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  frontend:
    name: frontend (NextJS)
    needs: check-changes
    if: needs.check-changes.outputs.changed == 'true'
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      file: ./modules/alerts/apps/frontend/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-alerts-frontend:${{ github.ref_name }}
      environment: ${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  api:
    name: api (NodeJS)
    needs: check-changes
    if: needs.check-changes.outputs.changed == 'true'
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      file: ./modules/alerts/apps/api/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-alerts-api:${{ github.ref_name }}
      environment: ${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  nginx:
    name: nginx
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      file: ./modules/alerts/apps/nginx/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-alerts-nginx:${{ github.ref_name }}
      environment: ${{ github.ref_name }}