name: 'Auth | Build & Push'

on:
  workflow_dispatch:
  push:
    branches:
      - production
      - staging
    paths:
      - '!modules/auth/environments/**'
      - 'modules/auth/**'
      - 'packages/**'
      - '.github/workflows/build-auth.yml'


# # #

jobs:

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  check-changes:
    uses: ./.github/workflows/_check-app-changes.yml
    with:
      paths: |
        modules/auth/apps/frontend/**
        modules/auth/apps/api/**

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  frontend:
    needs: check-changes
    if: needs.check-changes.outputs.changed == 'true'
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      context: ./modules/auth/apps/frontend
      file: ./modules/auth/apps/frontend/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-auth-frontend:${{ github.ref_name }}
      environment: ${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  api:
    needs: check-changes
    if: needs.check-changes.outputs.changed == 'true'
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      context: ./modules/auth/apps/api
      file: ./modules/auth/apps/api/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-auth-api:${{ github.ref_name }}
      environment: ${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  cleaner:
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      context: ./modules/auth/apps/cleaner
      file: ./modules/auth/apps/cleaner/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-auth-cleaner:${{ github.ref_name }}
      environment: ${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  file-exporter:
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      context: ./modules/auth/apps/file-exporter
      file: ./modules/auth/apps/file-exporter/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-auth-file-exporter:${{ github.ref_name }}
      environment: ${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # #

  nginx:
    uses: ./.github/workflows/_build-and-publish.yml
    with:
      context: ./modules/auth/apps/nginx
      file: ./modules/auth/apps/nginx/Dockerfile
      tags: ghcr.io/tmlmobilidade/go-auth-nginx:${{ github.ref_name }}
      environment: ${{ github.ref_name }}