name: PR Comment Bot

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Comment PR environment
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `Behold! Your PR has ascended to its own environment:\n\nhttps://pr-${prNumber}.go-stg.tmlmobilidade.pt/\n\nTest wisely, deploy bravely`
            });